syntax = "proto3";

package tenant.api.v1;

import "google/protobuf/timestamp.proto";
import "tenant/api/v1/common.proto";
import "tenant/api/v1/iam.proto";
import "tenant/api/v1/meta.proto";
import "tenant/api/v1/project.proto";

// TenantService provides service methods to work with tenants
service TenantService {
  // Create a tenant
  rpc Create(TenantServiceCreateRequest) returns (TenantServiceCreateResponse);
  // Update a tenant
  rpc Update(TenantServiceUpdateRequest) returns (TenantServiceUpdateResponse);
  // Delete a tenant
  rpc Delete(TenantServiceDeleteRequest) returns (TenantServiceDeleteResponse);
  // Get a tenant
  rpc Get(TenantServiceGetRequest) returns (TenantServiceGetResponse);
  // GetHistory of a tenant
  rpc GetHistory(TenantServiceGetHistoryRequest) returns (TenantServiceGetHistoryResponse);
  // List tenants
  rpc List(TenantServiceListRequest) returns (TenantServiceListResponse);
  // ListTenantMembers list all members of a tenant
  rpc ListTenantMembers(TenantServiceListTenantMembersRequest) returns (TenantServiceListTenantMembersResponse);
  // FindParticipatingProjects returns projects which are participating to the tenant
  rpc FindParticipatingProjects(TenantServiceFindParticipatingProjectsRequest) returns (TenantServiceFindParticipatingProjectsResponse);
  // FindParticipatingTenants returns tenants which are participating to the tenant
  rpc FindParticipatingTenants(TenantServiceFindParticipatingTenantsRequest) returns (TenantServiceFindParticipatingTenantsResponse);
}

// TenantServiceFindParticipatingProjectsRequest is the request payload to find participating projects
message TenantServiceFindParticipatingProjectsRequest {
  // TenantId
  string tenant_id = 1;
  // IncludeInherited
  optional bool include_inherited = 2;
  // Namespace
  string namespace = 3;
}

// TenantServiceFindParticipatingTenantsRequest is the request payload to find participating tenants
message TenantServiceFindParticipatingTenantsRequest {
  // TenantId
  string tenant_id = 1;
  // IncludeInherited
  optional bool include_inherited = 2;
  // Namespace
  string namespace = 3;
}

// TenantServiceListTenantMembersRequest is the request payload to get tenant members
message TenantServiceListTenantMembersRequest {
  // TenantId
  string tenant_id = 1;
  // IncludeInherited
  optional bool include_inherited = 2;
  // Namespace
  string namespace = 3;
}

// TenantServiceListTenantMembersResponse is the response payload to a list tenant member request
message TenantServiceListTenantMembersResponse {
  // Tenants
  repeated TenantWithMembershipAnnotations tenants = 1;
}

// TenantServiceFindParticipatingProjectsResponse is the response payload to a find participating project request
message TenantServiceFindParticipatingProjectsResponse {
  // Projects
  repeated ProjectWithMembershipAnnotations projects = 1;
}

// TenantServiceFindParticipatingTenantsResponse is the response payload to a find participating tenant request
message TenantServiceFindParticipatingTenantsResponse {
  // Tenants
  repeated TenantWithMembershipAnnotations tenants = 1;
}

// ProjectWithMembershipAnnotations
message ProjectWithMembershipAnnotations {
  // Project
  Project project = 1;
  // ProjectAnnotations
  map<string, string> project_annotations = 2;
  // TenantAnnotations
  map<string, string> tenant_annotations = 3;
}

// TenantWithMembershipAnnotations
message TenantWithMembershipAnnotations {
  // Tenant
  Tenant tenant = 1;
  // ProjectAnnotations
  map<string, string> project_annotations = 2;
  // TenantAnnotations
  map<string, string> tenant_annotations = 3;
  // ProjectIDs contains all project IDs of this tenant for which an explicit project membership exists
  repeated string project_ids = 4;
}

// Tenant
message Tenant {
  // Meta for a tenant
  Meta meta = 1;
  // Name of the tenant
  string name = 2;
  // Description of the tenant
  string description = 3;
  // IAMConfig for this tenant
  IAMConfig iam_config = 4;
}

// TenantServiceCreateRequest is the request payload to create a tenant
message TenantServiceCreateRequest {
  // Tenant
  Tenant tenant = 1;
}

// TenantServiceCreateResponse is the response payload of requests
message TenantServiceCreateResponse {
  // Tenant
  Tenant tenant = 1;
}

// TenantServiceUpdateRequest is the request payload to update a tenant
message TenantServiceUpdateRequest {
  // Tenant
  Tenant tenant = 1;
}

// TenantServiceUpdateResponse is the response payload of requests
message TenantServiceUpdateResponse {
  // Tenant
  Tenant tenant = 1;
}

// TenantServiceDeleteRequest is the request payload to delete a tenant
message TenantServiceDeleteRequest {
  // Id of the tenant to delete
  string id = 1;
}

// TenantServiceDeleteResponse is the response payload of requests
message TenantServiceDeleteResponse {
  // Tenant
  Tenant tenant = 1;
}

// TenantServiceGetRequest is the request payload to get a tenant
message TenantServiceGetRequest {
  // Id of the tenant to get
  string id = 1;
}

// TenantServiceGetResponse is the response payload of requests
message TenantServiceGetResponse {
  // Tenant
  Tenant tenant = 1;
}

// TenantServiceGetHistoryRequest is the request payload to get the history of a tenant
message TenantServiceGetHistoryRequest {
  // Id of the tenant
  string id = 1;
  // At timestamp at which the history of the tenant should be returned
  google.protobuf.Timestamp at = 2;
}

// TenantServiceGetHistoryResponse is the response payload of requests
message TenantServiceGetHistoryResponse {
  // Tenant
  Tenant tenant = 1;
}

// TenantServiceListRequest is the request payload to list tenants
message TenantServiceListRequest {
  // Paging spec of this list request
  Paging paging = 1;
  // Annotations of tenants to list
  map<string, string> annotations = 2;

  // Id of the tenant to list
  optional string id = 3;
  // Name of tenants to list
  optional string name = 4;
  // Labels of tenants to list
  repeated string labels = 5;
}

// TenantServiceListResponse is the response payload of tenant list requests
message TenantServiceListResponse {
  // Tenants
  repeated Tenant tenants = 1;
  // next_page is used for pagination, returns the next page to be fetched and must then be provided in the list request.
  optional uint64 next_page = 2;
}
