syntax = "proto3";

package tenant.api.v1;

// VersionService provides service methods to version information
service VersionService {
  // Get the version of this server
  rpc Get(VersionServiceGetRequest) returns (VersionServiceGetResponse);
}

// VersionServiceGetRequest is the request payload to get the server version
message VersionServiceGetRequest {}

// VersionServiceGetResponse is the response payload with all version details
message VersionServiceGetResponse {
  // Version
  string version = 1;
  // Revision
  string revision = 2;
  // GitSha1
  string git_sha1 = 3;
  // BuildDate
  string build_date = 4;
}
