// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv1connect

import (
	"context"

	"github.com/metal-stack/tenant-api/go/tenant/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewTenantMemberServiceHandler creates a new instance of TenantMemberServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTenantMemberServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenantMemberServiceHandler {
	mock := &TenantMemberServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TenantMemberServiceHandler is an autogenerated mock type for the TenantMemberServiceHandler type
type TenantMemberServiceHandler struct {
	mock.Mock
}

type TenantMemberServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *TenantMemberServiceHandler) EXPECT() *TenantMemberServiceHandler_Expecter {
	return &TenantMemberServiceHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TenantMemberServiceHandler
func (_mock *TenantMemberServiceHandler) Create(context1 context.Context, tenantMemberServiceCreateRequest *apiv1.TenantMemberServiceCreateRequest) (*apiv1.TenantMemberServiceCreateResponse, error) {
	ret := _mock.Called(context1, tenantMemberServiceCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apiv1.TenantMemberServiceCreateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceCreateRequest) (*apiv1.TenantMemberServiceCreateResponse, error)); ok {
		return returnFunc(context1, tenantMemberServiceCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceCreateRequest) *apiv1.TenantMemberServiceCreateResponse); ok {
		r0 = returnFunc(context1, tenantMemberServiceCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberServiceCreateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberServiceCreateRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberServiceCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TenantMemberServiceHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberServiceCreateRequest *apiv1.TenantMemberServiceCreateRequest
func (_e *TenantMemberServiceHandler_Expecter) Create(context1 any, tenantMemberServiceCreateRequest any) *TenantMemberServiceHandler_Create_Call {
	return &TenantMemberServiceHandler_Create_Call{Call: _e.mock.On("Create", context1, tenantMemberServiceCreateRequest)}
}

func (_c *TenantMemberServiceHandler_Create_Call) Run(run func(context1 context.Context, tenantMemberServiceCreateRequest *apiv1.TenantMemberServiceCreateRequest)) *TenantMemberServiceHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberServiceCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberServiceCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceHandler_Create_Call) Return(tenantMemberServiceCreateResponse *apiv1.TenantMemberServiceCreateResponse, err error) *TenantMemberServiceHandler_Create_Call {
	_c.Call.Return(tenantMemberServiceCreateResponse, err)
	return _c
}

func (_c *TenantMemberServiceHandler_Create_Call) RunAndReturn(run func(context1 context.Context, tenantMemberServiceCreateRequest *apiv1.TenantMemberServiceCreateRequest) (*apiv1.TenantMemberServiceCreateResponse, error)) *TenantMemberServiceHandler_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TenantMemberServiceHandler
func (_mock *TenantMemberServiceHandler) Delete(context1 context.Context, tenantMemberServiceDeleteRequest *apiv1.TenantMemberServiceDeleteRequest) (*apiv1.TenantMemberServiceDeleteResponse, error) {
	ret := _mock.Called(context1, tenantMemberServiceDeleteRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *apiv1.TenantMemberServiceDeleteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceDeleteRequest) (*apiv1.TenantMemberServiceDeleteResponse, error)); ok {
		return returnFunc(context1, tenantMemberServiceDeleteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceDeleteRequest) *apiv1.TenantMemberServiceDeleteResponse); ok {
		r0 = returnFunc(context1, tenantMemberServiceDeleteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberServiceDeleteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberServiceDeleteRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberServiceDeleteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TenantMemberServiceHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberServiceDeleteRequest *apiv1.TenantMemberServiceDeleteRequest
func (_e *TenantMemberServiceHandler_Expecter) Delete(context1 any, tenantMemberServiceDeleteRequest any) *TenantMemberServiceHandler_Delete_Call {
	return &TenantMemberServiceHandler_Delete_Call{Call: _e.mock.On("Delete", context1, tenantMemberServiceDeleteRequest)}
}

func (_c *TenantMemberServiceHandler_Delete_Call) Run(run func(context1 context.Context, tenantMemberServiceDeleteRequest *apiv1.TenantMemberServiceDeleteRequest)) *TenantMemberServiceHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberServiceDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberServiceDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceHandler_Delete_Call) Return(tenantMemberServiceDeleteResponse *apiv1.TenantMemberServiceDeleteResponse, err error) *TenantMemberServiceHandler_Delete_Call {
	_c.Call.Return(tenantMemberServiceDeleteResponse, err)
	return _c
}

func (_c *TenantMemberServiceHandler_Delete_Call) RunAndReturn(run func(context1 context.Context, tenantMemberServiceDeleteRequest *apiv1.TenantMemberServiceDeleteRequest) (*apiv1.TenantMemberServiceDeleteResponse, error)) *TenantMemberServiceHandler_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TenantMemberServiceHandler
func (_mock *TenantMemberServiceHandler) Get(context1 context.Context, tenantMemberServiceGetRequest *apiv1.TenantMemberServiceGetRequest) (*apiv1.TenantMemberServiceGetResponse, error) {
	ret := _mock.Called(context1, tenantMemberServiceGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv1.TenantMemberServiceGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceGetRequest) (*apiv1.TenantMemberServiceGetResponse, error)); ok {
		return returnFunc(context1, tenantMemberServiceGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceGetRequest) *apiv1.TenantMemberServiceGetResponse); ok {
		r0 = returnFunc(context1, tenantMemberServiceGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberServiceGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberServiceGetRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberServiceGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TenantMemberServiceHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberServiceGetRequest *apiv1.TenantMemberServiceGetRequest
func (_e *TenantMemberServiceHandler_Expecter) Get(context1 any, tenantMemberServiceGetRequest any) *TenantMemberServiceHandler_Get_Call {
	return &TenantMemberServiceHandler_Get_Call{Call: _e.mock.On("Get", context1, tenantMemberServiceGetRequest)}
}

func (_c *TenantMemberServiceHandler_Get_Call) Run(run func(context1 context.Context, tenantMemberServiceGetRequest *apiv1.TenantMemberServiceGetRequest)) *TenantMemberServiceHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberServiceGetRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberServiceGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceHandler_Get_Call) Return(tenantMemberServiceGetResponse *apiv1.TenantMemberServiceGetResponse, err error) *TenantMemberServiceHandler_Get_Call {
	_c.Call.Return(tenantMemberServiceGetResponse, err)
	return _c
}

func (_c *TenantMemberServiceHandler_Get_Call) RunAndReturn(run func(context1 context.Context, tenantMemberServiceGetRequest *apiv1.TenantMemberServiceGetRequest) (*apiv1.TenantMemberServiceGetResponse, error)) *TenantMemberServiceHandler_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type TenantMemberServiceHandler
func (_mock *TenantMemberServiceHandler) List(context1 context.Context, tenantMemberServiceListRequest *apiv1.TenantMemberServiceListRequest) (*apiv1.TenantMemberServiceListResponse, error) {
	ret := _mock.Called(context1, tenantMemberServiceListRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *apiv1.TenantMemberServiceListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceListRequest) (*apiv1.TenantMemberServiceListResponse, error)); ok {
		return returnFunc(context1, tenantMemberServiceListRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceListRequest) *apiv1.TenantMemberServiceListResponse); ok {
		r0 = returnFunc(context1, tenantMemberServiceListRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberServiceListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberServiceListRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberServiceListRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceHandler_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TenantMemberServiceHandler_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberServiceListRequest *apiv1.TenantMemberServiceListRequest
func (_e *TenantMemberServiceHandler_Expecter) List(context1 any, tenantMemberServiceListRequest any) *TenantMemberServiceHandler_List_Call {
	return &TenantMemberServiceHandler_List_Call{Call: _e.mock.On("List", context1, tenantMemberServiceListRequest)}
}

func (_c *TenantMemberServiceHandler_List_Call) Run(run func(context1 context.Context, tenantMemberServiceListRequest *apiv1.TenantMemberServiceListRequest)) *TenantMemberServiceHandler_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberServiceListRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberServiceListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceHandler_List_Call) Return(tenantMemberServiceListResponse *apiv1.TenantMemberServiceListResponse, err error) *TenantMemberServiceHandler_List_Call {
	_c.Call.Return(tenantMemberServiceListResponse, err)
	return _c
}

func (_c *TenantMemberServiceHandler_List_Call) RunAndReturn(run func(context1 context.Context, tenantMemberServiceListRequest *apiv1.TenantMemberServiceListRequest) (*apiv1.TenantMemberServiceListResponse, error)) *TenantMemberServiceHandler_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TenantMemberServiceHandler
func (_mock *TenantMemberServiceHandler) Update(context1 context.Context, tenantMemberServiceUpdateRequest *apiv1.TenantMemberServiceUpdateRequest) (*apiv1.TenantMemberServiceUpdateResponse, error) {
	ret := _mock.Called(context1, tenantMemberServiceUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *apiv1.TenantMemberServiceUpdateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceUpdateRequest) (*apiv1.TenantMemberServiceUpdateResponse, error)); ok {
		return returnFunc(context1, tenantMemberServiceUpdateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceUpdateRequest) *apiv1.TenantMemberServiceUpdateResponse); ok {
		r0 = returnFunc(context1, tenantMemberServiceUpdateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberServiceUpdateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberServiceUpdateRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberServiceUpdateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TenantMemberServiceHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberServiceUpdateRequest *apiv1.TenantMemberServiceUpdateRequest
func (_e *TenantMemberServiceHandler_Expecter) Update(context1 any, tenantMemberServiceUpdateRequest any) *TenantMemberServiceHandler_Update_Call {
	return &TenantMemberServiceHandler_Update_Call{Call: _e.mock.On("Update", context1, tenantMemberServiceUpdateRequest)}
}

func (_c *TenantMemberServiceHandler_Update_Call) Run(run func(context1 context.Context, tenantMemberServiceUpdateRequest *apiv1.TenantMemberServiceUpdateRequest)) *TenantMemberServiceHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberServiceUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberServiceUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceHandler_Update_Call) Return(tenantMemberServiceUpdateResponse *apiv1.TenantMemberServiceUpdateResponse, err error) *TenantMemberServiceHandler_Update_Call {
	_c.Call.Return(tenantMemberServiceUpdateResponse, err)
	return _c
}

func (_c *TenantMemberServiceHandler_Update_Call) RunAndReturn(run func(context1 context.Context, tenantMemberServiceUpdateRequest *apiv1.TenantMemberServiceUpdateRequest) (*apiv1.TenantMemberServiceUpdateResponse, error)) *TenantMemberServiceHandler_Update_Call {
	_c.Call.Return(run)
	return _c
}
