// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv1connect

import (
	"context"

	"github.com/metal-stack/tenant-api/go/tenant/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewTenantServiceClient creates a new instance of TenantServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTenantServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenantServiceClient {
	mock := &TenantServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TenantServiceClient is an autogenerated mock type for the TenantServiceClient type
type TenantServiceClient struct {
	mock.Mock
}

type TenantServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TenantServiceClient) EXPECT() *TenantServiceClient_Expecter {
	return &TenantServiceClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) Create(context1 context.Context, tenantServiceCreateRequest *apiv1.TenantServiceCreateRequest) (*apiv1.TenantServiceCreateResponse, error) {
	ret := _mock.Called(context1, tenantServiceCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apiv1.TenantServiceCreateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceCreateRequest) (*apiv1.TenantServiceCreateResponse, error)); ok {
		return returnFunc(context1, tenantServiceCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceCreateRequest) *apiv1.TenantServiceCreateResponse); ok {
		r0 = returnFunc(context1, tenantServiceCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantServiceCreateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceCreateRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TenantServiceClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceCreateRequest *apiv1.TenantServiceCreateRequest
func (_e *TenantServiceClient_Expecter) Create(context1 any, tenantServiceCreateRequest any) *TenantServiceClient_Create_Call {
	return &TenantServiceClient_Create_Call{Call: _e.mock.On("Create", context1, tenantServiceCreateRequest)}
}

func (_c *TenantServiceClient_Create_Call) Run(run func(context1 context.Context, tenantServiceCreateRequest *apiv1.TenantServiceCreateRequest)) *TenantServiceClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_Create_Call) Return(tenantServiceCreateResponse *apiv1.TenantServiceCreateResponse, err error) *TenantServiceClient_Create_Call {
	_c.Call.Return(tenantServiceCreateResponse, err)
	return _c
}

func (_c *TenantServiceClient_Create_Call) RunAndReturn(run func(context1 context.Context, tenantServiceCreateRequest *apiv1.TenantServiceCreateRequest) (*apiv1.TenantServiceCreateResponse, error)) *TenantServiceClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) Delete(context1 context.Context, tenantServiceDeleteRequest *apiv1.TenantServiceDeleteRequest) (*apiv1.TenantServiceDeleteResponse, error) {
	ret := _mock.Called(context1, tenantServiceDeleteRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *apiv1.TenantServiceDeleteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceDeleteRequest) (*apiv1.TenantServiceDeleteResponse, error)); ok {
		return returnFunc(context1, tenantServiceDeleteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceDeleteRequest) *apiv1.TenantServiceDeleteResponse); ok {
		r0 = returnFunc(context1, tenantServiceDeleteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantServiceDeleteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceDeleteRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceDeleteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TenantServiceClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceDeleteRequest *apiv1.TenantServiceDeleteRequest
func (_e *TenantServiceClient_Expecter) Delete(context1 any, tenantServiceDeleteRequest any) *TenantServiceClient_Delete_Call {
	return &TenantServiceClient_Delete_Call{Call: _e.mock.On("Delete", context1, tenantServiceDeleteRequest)}
}

func (_c *TenantServiceClient_Delete_Call) Run(run func(context1 context.Context, tenantServiceDeleteRequest *apiv1.TenantServiceDeleteRequest)) *TenantServiceClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_Delete_Call) Return(tenantServiceDeleteResponse *apiv1.TenantServiceDeleteResponse, err error) *TenantServiceClient_Delete_Call {
	_c.Call.Return(tenantServiceDeleteResponse, err)
	return _c
}

func (_c *TenantServiceClient_Delete_Call) RunAndReturn(run func(context1 context.Context, tenantServiceDeleteRequest *apiv1.TenantServiceDeleteRequest) (*apiv1.TenantServiceDeleteResponse, error)) *TenantServiceClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindParticipatingProjects provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) FindParticipatingProjects(context1 context.Context, tenantServiceFindParticipatingProjectsRequest *apiv1.TenantServiceFindParticipatingProjectsRequest) (*apiv1.TenantServiceFindParticipatingProjectsResponse, error) {
	ret := _mock.Called(context1, tenantServiceFindParticipatingProjectsRequest)

	if len(ret) == 0 {
		panic("no return value specified for FindParticipatingProjects")
	}

	var r0 *apiv1.TenantServiceFindParticipatingProjectsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceFindParticipatingProjectsRequest) (*apiv1.TenantServiceFindParticipatingProjectsResponse, error)); ok {
		return returnFunc(context1, tenantServiceFindParticipatingProjectsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceFindParticipatingProjectsRequest) *apiv1.TenantServiceFindParticipatingProjectsResponse); ok {
		r0 = returnFunc(context1, tenantServiceFindParticipatingProjectsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantServiceFindParticipatingProjectsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceFindParticipatingProjectsRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceFindParticipatingProjectsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_FindParticipatingProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindParticipatingProjects'
type TenantServiceClient_FindParticipatingProjects_Call struct {
	*mock.Call
}

// FindParticipatingProjects is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceFindParticipatingProjectsRequest *apiv1.TenantServiceFindParticipatingProjectsRequest
func (_e *TenantServiceClient_Expecter) FindParticipatingProjects(context1 any, tenantServiceFindParticipatingProjectsRequest any) *TenantServiceClient_FindParticipatingProjects_Call {
	return &TenantServiceClient_FindParticipatingProjects_Call{Call: _e.mock.On("FindParticipatingProjects", context1, tenantServiceFindParticipatingProjectsRequest)}
}

func (_c *TenantServiceClient_FindParticipatingProjects_Call) Run(run func(context1 context.Context, tenantServiceFindParticipatingProjectsRequest *apiv1.TenantServiceFindParticipatingProjectsRequest)) *TenantServiceClient_FindParticipatingProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceFindParticipatingProjectsRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceFindParticipatingProjectsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_FindParticipatingProjects_Call) Return(tenantServiceFindParticipatingProjectsResponse *apiv1.TenantServiceFindParticipatingProjectsResponse, err error) *TenantServiceClient_FindParticipatingProjects_Call {
	_c.Call.Return(tenantServiceFindParticipatingProjectsResponse, err)
	return _c
}

func (_c *TenantServiceClient_FindParticipatingProjects_Call) RunAndReturn(run func(context1 context.Context, tenantServiceFindParticipatingProjectsRequest *apiv1.TenantServiceFindParticipatingProjectsRequest) (*apiv1.TenantServiceFindParticipatingProjectsResponse, error)) *TenantServiceClient_FindParticipatingProjects_Call {
	_c.Call.Return(run)
	return _c
}

// FindParticipatingTenants provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) FindParticipatingTenants(context1 context.Context, tenantServiceFindParticipatingTenantsRequest *apiv1.TenantServiceFindParticipatingTenantsRequest) (*apiv1.TenantServiceFindParticipatingTenantsResponse, error) {
	ret := _mock.Called(context1, tenantServiceFindParticipatingTenantsRequest)

	if len(ret) == 0 {
		panic("no return value specified for FindParticipatingTenants")
	}

	var r0 *apiv1.TenantServiceFindParticipatingTenantsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceFindParticipatingTenantsRequest) (*apiv1.TenantServiceFindParticipatingTenantsResponse, error)); ok {
		return returnFunc(context1, tenantServiceFindParticipatingTenantsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceFindParticipatingTenantsRequest) *apiv1.TenantServiceFindParticipatingTenantsResponse); ok {
		r0 = returnFunc(context1, tenantServiceFindParticipatingTenantsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantServiceFindParticipatingTenantsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceFindParticipatingTenantsRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceFindParticipatingTenantsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_FindParticipatingTenants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindParticipatingTenants'
type TenantServiceClient_FindParticipatingTenants_Call struct {
	*mock.Call
}

// FindParticipatingTenants is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceFindParticipatingTenantsRequest *apiv1.TenantServiceFindParticipatingTenantsRequest
func (_e *TenantServiceClient_Expecter) FindParticipatingTenants(context1 any, tenantServiceFindParticipatingTenantsRequest any) *TenantServiceClient_FindParticipatingTenants_Call {
	return &TenantServiceClient_FindParticipatingTenants_Call{Call: _e.mock.On("FindParticipatingTenants", context1, tenantServiceFindParticipatingTenantsRequest)}
}

func (_c *TenantServiceClient_FindParticipatingTenants_Call) Run(run func(context1 context.Context, tenantServiceFindParticipatingTenantsRequest *apiv1.TenantServiceFindParticipatingTenantsRequest)) *TenantServiceClient_FindParticipatingTenants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceFindParticipatingTenantsRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceFindParticipatingTenantsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_FindParticipatingTenants_Call) Return(tenantServiceFindParticipatingTenantsResponse *apiv1.TenantServiceFindParticipatingTenantsResponse, err error) *TenantServiceClient_FindParticipatingTenants_Call {
	_c.Call.Return(tenantServiceFindParticipatingTenantsResponse, err)
	return _c
}

func (_c *TenantServiceClient_FindParticipatingTenants_Call) RunAndReturn(run func(context1 context.Context, tenantServiceFindParticipatingTenantsRequest *apiv1.TenantServiceFindParticipatingTenantsRequest) (*apiv1.TenantServiceFindParticipatingTenantsResponse, error)) *TenantServiceClient_FindParticipatingTenants_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) Get(context1 context.Context, tenantServiceGetRequest *apiv1.TenantServiceGetRequest) (*apiv1.TenantServiceGetResponse, error) {
	ret := _mock.Called(context1, tenantServiceGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv1.TenantServiceGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceGetRequest) (*apiv1.TenantServiceGetResponse, error)); ok {
		return returnFunc(context1, tenantServiceGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceGetRequest) *apiv1.TenantServiceGetResponse); ok {
		r0 = returnFunc(context1, tenantServiceGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantServiceGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceGetRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TenantServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceGetRequest *apiv1.TenantServiceGetRequest
func (_e *TenantServiceClient_Expecter) Get(context1 any, tenantServiceGetRequest any) *TenantServiceClient_Get_Call {
	return &TenantServiceClient_Get_Call{Call: _e.mock.On("Get", context1, tenantServiceGetRequest)}
}

func (_c *TenantServiceClient_Get_Call) Run(run func(context1 context.Context, tenantServiceGetRequest *apiv1.TenantServiceGetRequest)) *TenantServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceGetRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_Get_Call) Return(tenantServiceGetResponse *apiv1.TenantServiceGetResponse, err error) *TenantServiceClient_Get_Call {
	_c.Call.Return(tenantServiceGetResponse, err)
	return _c
}

func (_c *TenantServiceClient_Get_Call) RunAndReturn(run func(context1 context.Context, tenantServiceGetRequest *apiv1.TenantServiceGetRequest) (*apiv1.TenantServiceGetResponse, error)) *TenantServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistory provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) GetHistory(context1 context.Context, tenantServiceGetHistoryRequest *apiv1.TenantServiceGetHistoryRequest) (*apiv1.TenantServiceGetHistoryResponse, error) {
	ret := _mock.Called(context1, tenantServiceGetHistoryRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 *apiv1.TenantServiceGetHistoryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceGetHistoryRequest) (*apiv1.TenantServiceGetHistoryResponse, error)); ok {
		return returnFunc(context1, tenantServiceGetHistoryRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceGetHistoryRequest) *apiv1.TenantServiceGetHistoryResponse); ok {
		r0 = returnFunc(context1, tenantServiceGetHistoryRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantServiceGetHistoryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceGetHistoryRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceGetHistoryRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type TenantServiceClient_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceGetHistoryRequest *apiv1.TenantServiceGetHistoryRequest
func (_e *TenantServiceClient_Expecter) GetHistory(context1 any, tenantServiceGetHistoryRequest any) *TenantServiceClient_GetHistory_Call {
	return &TenantServiceClient_GetHistory_Call{Call: _e.mock.On("GetHistory", context1, tenantServiceGetHistoryRequest)}
}

func (_c *TenantServiceClient_GetHistory_Call) Run(run func(context1 context.Context, tenantServiceGetHistoryRequest *apiv1.TenantServiceGetHistoryRequest)) *TenantServiceClient_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceGetHistoryRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceGetHistoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_GetHistory_Call) Return(tenantServiceGetHistoryResponse *apiv1.TenantServiceGetHistoryResponse, err error) *TenantServiceClient_GetHistory_Call {
	_c.Call.Return(tenantServiceGetHistoryResponse, err)
	return _c
}

func (_c *TenantServiceClient_GetHistory_Call) RunAndReturn(run func(context1 context.Context, tenantServiceGetHistoryRequest *apiv1.TenantServiceGetHistoryRequest) (*apiv1.TenantServiceGetHistoryResponse, error)) *TenantServiceClient_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) List(context1 context.Context, tenantServiceListRequest *apiv1.TenantServiceListRequest) (*apiv1.TenantServiceListResponse, error) {
	ret := _mock.Called(context1, tenantServiceListRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *apiv1.TenantServiceListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceListRequest) (*apiv1.TenantServiceListResponse, error)); ok {
		return returnFunc(context1, tenantServiceListRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceListRequest) *apiv1.TenantServiceListResponse); ok {
		r0 = returnFunc(context1, tenantServiceListRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantServiceListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceListRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceListRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type TenantServiceClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceListRequest *apiv1.TenantServiceListRequest
func (_e *TenantServiceClient_Expecter) List(context1 any, tenantServiceListRequest any) *TenantServiceClient_List_Call {
	return &TenantServiceClient_List_Call{Call: _e.mock.On("List", context1, tenantServiceListRequest)}
}

func (_c *TenantServiceClient_List_Call) Run(run func(context1 context.Context, tenantServiceListRequest *apiv1.TenantServiceListRequest)) *TenantServiceClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceListRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_List_Call) Return(tenantServiceListResponse *apiv1.TenantServiceListResponse, err error) *TenantServiceClient_List_Call {
	_c.Call.Return(tenantServiceListResponse, err)
	return _c
}

func (_c *TenantServiceClient_List_Call) RunAndReturn(run func(context1 context.Context, tenantServiceListRequest *apiv1.TenantServiceListRequest) (*apiv1.TenantServiceListResponse, error)) *TenantServiceClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListTenantMembers provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) ListTenantMembers(context1 context.Context, tenantServiceListTenantMembersRequest *apiv1.TenantServiceListTenantMembersRequest) (*apiv1.TenantServiceListTenantMembersResponse, error) {
	ret := _mock.Called(context1, tenantServiceListTenantMembersRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListTenantMembers")
	}

	var r0 *apiv1.TenantServiceListTenantMembersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceListTenantMembersRequest) (*apiv1.TenantServiceListTenantMembersResponse, error)); ok {
		return returnFunc(context1, tenantServiceListTenantMembersRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceListTenantMembersRequest) *apiv1.TenantServiceListTenantMembersResponse); ok {
		r0 = returnFunc(context1, tenantServiceListTenantMembersRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantServiceListTenantMembersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceListTenantMembersRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceListTenantMembersRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_ListTenantMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTenantMembers'
type TenantServiceClient_ListTenantMembers_Call struct {
	*mock.Call
}

// ListTenantMembers is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceListTenantMembersRequest *apiv1.TenantServiceListTenantMembersRequest
func (_e *TenantServiceClient_Expecter) ListTenantMembers(context1 any, tenantServiceListTenantMembersRequest any) *TenantServiceClient_ListTenantMembers_Call {
	return &TenantServiceClient_ListTenantMembers_Call{Call: _e.mock.On("ListTenantMembers", context1, tenantServiceListTenantMembersRequest)}
}

func (_c *TenantServiceClient_ListTenantMembers_Call) Run(run func(context1 context.Context, tenantServiceListTenantMembersRequest *apiv1.TenantServiceListTenantMembersRequest)) *TenantServiceClient_ListTenantMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceListTenantMembersRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceListTenantMembersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_ListTenantMembers_Call) Return(tenantServiceListTenantMembersResponse *apiv1.TenantServiceListTenantMembersResponse, err error) *TenantServiceClient_ListTenantMembers_Call {
	_c.Call.Return(tenantServiceListTenantMembersResponse, err)
	return _c
}

func (_c *TenantServiceClient_ListTenantMembers_Call) RunAndReturn(run func(context1 context.Context, tenantServiceListTenantMembersRequest *apiv1.TenantServiceListTenantMembersRequest) (*apiv1.TenantServiceListTenantMembersResponse, error)) *TenantServiceClient_ListTenantMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) Update(context1 context.Context, tenantServiceUpdateRequest *apiv1.TenantServiceUpdateRequest) (*apiv1.TenantServiceUpdateResponse, error) {
	ret := _mock.Called(context1, tenantServiceUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *apiv1.TenantServiceUpdateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceUpdateRequest) (*apiv1.TenantServiceUpdateResponse, error)); ok {
		return returnFunc(context1, tenantServiceUpdateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceUpdateRequest) *apiv1.TenantServiceUpdateResponse); ok {
		r0 = returnFunc(context1, tenantServiceUpdateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantServiceUpdateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceUpdateRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceUpdateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TenantServiceClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceUpdateRequest *apiv1.TenantServiceUpdateRequest
func (_e *TenantServiceClient_Expecter) Update(context1 any, tenantServiceUpdateRequest any) *TenantServiceClient_Update_Call {
	return &TenantServiceClient_Update_Call{Call: _e.mock.On("Update", context1, tenantServiceUpdateRequest)}
}

func (_c *TenantServiceClient_Update_Call) Run(run func(context1 context.Context, tenantServiceUpdateRequest *apiv1.TenantServiceUpdateRequest)) *TenantServiceClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_Update_Call) Return(tenantServiceUpdateResponse *apiv1.TenantServiceUpdateResponse, err error) *TenantServiceClient_Update_Call {
	_c.Call.Return(tenantServiceUpdateResponse, err)
	return _c
}

func (_c *TenantServiceClient_Update_Call) RunAndReturn(run func(context1 context.Context, tenantServiceUpdateRequest *apiv1.TenantServiceUpdateRequest) (*apiv1.TenantServiceUpdateResponse, error)) *TenantServiceClient_Update_Call {
	_c.Call.Return(run)
	return _c
}
