// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tenant/api/v1/project_member.proto

package apiv1connect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	v1 "github.com/metal-stack/tenant-api/go/tenant/api/v1"
	sync "sync"
)

const (
	// ProjectMemberServiceName is the fully-qualified name of the ProjectMemberService service.
	ProjectMemberServiceName = "tenant.api.v1.ProjectMemberService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProjectMemberServiceCreateProcedure is the procedure name of the ProjectMemberService's Create
	// RPC.
	ProjectMemberServiceCreateProcedure = "/tenant.api.v1.ProjectMemberService/Create"
	// ProjectMemberServiceUpdateProcedure is the procedure name of the ProjectMemberService's Update
	// RPC.
	ProjectMemberServiceUpdateProcedure = "/tenant.api.v1.ProjectMemberService/Update"
	// ProjectMemberServiceDeleteProcedure is the procedure name of the ProjectMemberService's Delete
	// RPC.
	ProjectMemberServiceDeleteProcedure = "/tenant.api.v1.ProjectMemberService/Delete"
	// ProjectMemberServiceGetProcedure is the procedure name of the ProjectMemberService's Get RPC.
	ProjectMemberServiceGetProcedure = "/tenant.api.v1.ProjectMemberService/Get"
	// ProjectMemberServiceListProcedure is the procedure name of the ProjectMemberService's List RPC.
	ProjectMemberServiceListProcedure = "/tenant.api.v1.ProjectMemberService/List"
)

var (
	projectMemberServiceCreateSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_tenant_api_v1_project_member_proto.Services().ByName("ProjectMemberService").Methods().ByName("Create"),
			Procedure:  ProjectMemberServiceCreateProcedure,
		}
	})
	projectMemberServiceUpdateSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_tenant_api_v1_project_member_proto.Services().ByName("ProjectMemberService").Methods().ByName("Update"),
			Procedure:  ProjectMemberServiceUpdateProcedure,
		}
	})
	projectMemberServiceDeleteSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_tenant_api_v1_project_member_proto.Services().ByName("ProjectMemberService").Methods().ByName("Delete"),
			Procedure:  ProjectMemberServiceDeleteProcedure,
		}
	})
	projectMemberServiceGetSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_tenant_api_v1_project_member_proto.Services().ByName("ProjectMemberService").Methods().ByName("Get"),
			Procedure:  ProjectMemberServiceGetProcedure,
		}
	})
	projectMemberServiceListSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_tenant_api_v1_project_member_proto.Services().ByName("ProjectMemberService").Methods().ByName("List"),
			Procedure:  ProjectMemberServiceListProcedure,
		}
	})
)

// ProjectMemberServiceClient is a client for the tenant.api.v1.ProjectMemberService service.
type ProjectMemberServiceClient interface {
	// Create a project member ship
	Create(context.Context, *v1.ProjectMemberServiceCreateRequest) (*v1.ProjectMemberServiceCreateResponse, error)
	// Update a project member ship
	Update(context.Context, *v1.ProjectMemberServiceUpdateRequest) (*v1.ProjectMemberServiceUpdateResponse, error)
	// Delete a project member ship
	Delete(context.Context, *v1.ProjectMemberServiceDeleteRequest) (*v1.ProjectMemberServiceDeleteResponse, error)
	// Get a project member ship
	Get(context.Context, *v1.ProjectMemberServiceGetRequest) (*v1.ProjectMemberServiceGetResponse, error)
	// List project member ships
	List(context.Context, *v1.ProjectMemberServiceListRequest) (*v1.ProjectMemberServiceListResponse, error)
}

// NewProjectMemberServiceClient constructs a client for the tenant.api.v1.ProjectMemberService
// service. Multiple service clients may share a single connect.Client.
func NewProjectMemberServiceClient(client *connect.Client) ProjectMemberServiceClient {
	return &projectMemberServiceClient{client: client}
}

// ProjectMemberServiceHandler is an implementation of the tenant.api.v1.ProjectMemberService
// service.
type ProjectMemberServiceHandler interface {
	// Create a project member ship
	Create(context.Context, *v1.ProjectMemberServiceCreateRequest) (*v1.ProjectMemberServiceCreateResponse, error)
	// Update a project member ship
	Update(context.Context, *v1.ProjectMemberServiceUpdateRequest) (*v1.ProjectMemberServiceUpdateResponse, error)
	// Delete a project member ship
	Delete(context.Context, *v1.ProjectMemberServiceDeleteRequest) (*v1.ProjectMemberServiceDeleteResponse, error)
	// Get a project member ship
	Get(context.Context, *v1.ProjectMemberServiceGetRequest) (*v1.ProjectMemberServiceGetResponse, error)
	// List project member ships
	List(context.Context, *v1.ProjectMemberServiceListRequest) (*v1.ProjectMemberServiceListResponse, error)
}

// RegisterProjectMemberServiceHandler registers svc as the tenant.api.v1.ProjectMemberService
// implementation on server.
func RegisterProjectMemberServiceHandler(server *connect.Server, svc ProjectMemberServiceHandler) {
	adapter := projectMemberServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: projectMemberServiceCreateSpec(), Handler: adapter.create},
		connect.Method{Spec: projectMemberServiceUpdateSpec(), Handler: adapter.update},
		connect.Method{Spec: projectMemberServiceDeleteSpec(), Handler: adapter.delete},
		connect.Method{Spec: projectMemberServiceGetSpec(), Handler: adapter.get},
		connect.Method{Spec: projectMemberServiceListSpec(), Handler: adapter.list},
	)
}

// UnimplementedProjectMemberServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectMemberServiceHandler struct{}

func (UnimplementedProjectMemberServiceHandler) Create(context.Context, *v1.ProjectMemberServiceCreateRequest) (*v1.ProjectMemberServiceCreateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "tenant.api.v1.ProjectMemberService.Create is not implemented")
}

func (UnimplementedProjectMemberServiceHandler) Update(context.Context, *v1.ProjectMemberServiceUpdateRequest) (*v1.ProjectMemberServiceUpdateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "tenant.api.v1.ProjectMemberService.Update is not implemented")
}

func (UnimplementedProjectMemberServiceHandler) Delete(context.Context, *v1.ProjectMemberServiceDeleteRequest) (*v1.ProjectMemberServiceDeleteResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "tenant.api.v1.ProjectMemberService.Delete is not implemented")
}

func (UnimplementedProjectMemberServiceHandler) Get(context.Context, *v1.ProjectMemberServiceGetRequest) (*v1.ProjectMemberServiceGetResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "tenant.api.v1.ProjectMemberService.Get is not implemented")
}

func (UnimplementedProjectMemberServiceHandler) List(context.Context, *v1.ProjectMemberServiceListRequest) (*v1.ProjectMemberServiceListResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "tenant.api.v1.ProjectMemberService.List is not implemented")
}

type projectMemberServiceClient struct {
	client *connect.Client
}

func (c *projectMemberServiceClient) Create(ctx context.Context, req *v1.ProjectMemberServiceCreateRequest) (*v1.ProjectMemberServiceCreateResponse, error) {
	var res v1.ProjectMemberServiceCreateResponse
	if err := c.client.CallUnary(ctx, projectMemberServiceCreateSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *projectMemberServiceClient) Update(ctx context.Context, req *v1.ProjectMemberServiceUpdateRequest) (*v1.ProjectMemberServiceUpdateResponse, error) {
	var res v1.ProjectMemberServiceUpdateResponse
	if err := c.client.CallUnary(ctx, projectMemberServiceUpdateSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *projectMemberServiceClient) Delete(ctx context.Context, req *v1.ProjectMemberServiceDeleteRequest) (*v1.ProjectMemberServiceDeleteResponse, error) {
	var res v1.ProjectMemberServiceDeleteResponse
	if err := c.client.CallUnary(ctx, projectMemberServiceDeleteSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *projectMemberServiceClient) Get(ctx context.Context, req *v1.ProjectMemberServiceGetRequest) (*v1.ProjectMemberServiceGetResponse, error) {
	var res v1.ProjectMemberServiceGetResponse
	if err := c.client.CallUnary(ctx, projectMemberServiceGetSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *projectMemberServiceClient) List(ctx context.Context, req *v1.ProjectMemberServiceListRequest) (*v1.ProjectMemberServiceListResponse, error) {
	var res v1.ProjectMemberServiceListResponse
	if err := c.client.CallUnary(ctx, projectMemberServiceListSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type projectMemberServiceHandler struct{ svc ProjectMemberServiceHandler }

func (h projectMemberServiceHandler) create(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ProjectMemberServiceCreateRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Create(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h projectMemberServiceHandler) update(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ProjectMemberServiceUpdateRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Update(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h projectMemberServiceHandler) delete(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ProjectMemberServiceDeleteRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Delete(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h projectMemberServiceHandler) get(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ProjectMemberServiceGetRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Get(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h projectMemberServiceHandler) list(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.ProjectMemberServiceListRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.List(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
