// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tenant/api/v1/tenant_member.proto

package apiv1connect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	v1 "github.com/metal-stack/tenant-api/go/tenant/api/v1"
	sync "sync"
)

const (
	// TenantMemberServiceName is the fully-qualified name of the TenantMemberService service.
	TenantMemberServiceName = "tenant.api.v1.TenantMemberService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TenantMemberServiceCreateProcedure is the procedure name of the TenantMemberService's Create RPC.
	TenantMemberServiceCreateProcedure = "/tenant.api.v1.TenantMemberService/Create"
	// TenantMemberServiceUpdateProcedure is the procedure name of the TenantMemberService's Update RPC.
	TenantMemberServiceUpdateProcedure = "/tenant.api.v1.TenantMemberService/Update"
	// TenantMemberServiceDeleteProcedure is the procedure name of the TenantMemberService's Delete RPC.
	TenantMemberServiceDeleteProcedure = "/tenant.api.v1.TenantMemberService/Delete"
	// TenantMemberServiceGetProcedure is the procedure name of the TenantMemberService's Get RPC.
	TenantMemberServiceGetProcedure = "/tenant.api.v1.TenantMemberService/Get"
	// TenantMemberServiceListProcedure is the procedure name of the TenantMemberService's List RPC.
	TenantMemberServiceListProcedure = "/tenant.api.v1.TenantMemberService/List"
)

var (
	tenantMemberServiceCreateSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_tenant_api_v1_tenant_member_proto.Services().ByName("TenantMemberService").Methods().ByName("Create"),
			Procedure:  TenantMemberServiceCreateProcedure,
		}
	})
	tenantMemberServiceUpdateSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_tenant_api_v1_tenant_member_proto.Services().ByName("TenantMemberService").Methods().ByName("Update"),
			Procedure:  TenantMemberServiceUpdateProcedure,
		}
	})
	tenantMemberServiceDeleteSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_tenant_api_v1_tenant_member_proto.Services().ByName("TenantMemberService").Methods().ByName("Delete"),
			Procedure:  TenantMemberServiceDeleteProcedure,
		}
	})
	tenantMemberServiceGetSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_tenant_api_v1_tenant_member_proto.Services().ByName("TenantMemberService").Methods().ByName("Get"),
			Procedure:  TenantMemberServiceGetProcedure,
		}
	})
	tenantMemberServiceListSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_tenant_api_v1_tenant_member_proto.Services().ByName("TenantMemberService").Methods().ByName("List"),
			Procedure:  TenantMemberServiceListProcedure,
		}
	})
)

// TenantMemberServiceClient is a client for the tenant.api.v1.TenantMemberService service.
type TenantMemberServiceClient interface {
	// Create a tenant member
	Create(context.Context, *v1.TenantMemberServiceCreateRequest) (*v1.TenantMemberServiceCreateResponse, error)
	// Update a tenant member
	Update(context.Context, *v1.TenantMemberServiceUpdateRequest) (*v1.TenantMemberServiceUpdateResponse, error)
	// Delete a tenant member
	Delete(context.Context, *v1.TenantMemberServiceDeleteRequest) (*v1.TenantMemberServiceDeleteResponse, error)
	// Get a tenant member
	Get(context.Context, *v1.TenantMemberServiceGetRequest) (*v1.TenantMemberServiceGetResponse, error)
	// List tenant members
	List(context.Context, *v1.TenantMemberServiceListRequest) (*v1.TenantMemberServiceListResponse, error)
}

// NewTenantMemberServiceClient constructs a client for the tenant.api.v1.TenantMemberService
// service. Multiple service clients may share a single connect.Client.
func NewTenantMemberServiceClient(client *connect.Client) TenantMemberServiceClient {
	return &tenantMemberServiceClient{client: client}
}

// TenantMemberServiceHandler is an implementation of the tenant.api.v1.TenantMemberService service.
type TenantMemberServiceHandler interface {
	// Create a tenant member
	Create(context.Context, *v1.TenantMemberServiceCreateRequest) (*v1.TenantMemberServiceCreateResponse, error)
	// Update a tenant member
	Update(context.Context, *v1.TenantMemberServiceUpdateRequest) (*v1.TenantMemberServiceUpdateResponse, error)
	// Delete a tenant member
	Delete(context.Context, *v1.TenantMemberServiceDeleteRequest) (*v1.TenantMemberServiceDeleteResponse, error)
	// Get a tenant member
	Get(context.Context, *v1.TenantMemberServiceGetRequest) (*v1.TenantMemberServiceGetResponse, error)
	// List tenant members
	List(context.Context, *v1.TenantMemberServiceListRequest) (*v1.TenantMemberServiceListResponse, error)
}

// RegisterTenantMemberServiceHandler registers svc as the tenant.api.v1.TenantMemberService
// implementation on server.
func RegisterTenantMemberServiceHandler(server *connect.Server, svc TenantMemberServiceHandler) {
	adapter := tenantMemberServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: tenantMemberServiceCreateSpec(), Handler: adapter.create},
		connect.Method{Spec: tenantMemberServiceUpdateSpec(), Handler: adapter.update},
		connect.Method{Spec: tenantMemberServiceDeleteSpec(), Handler: adapter.delete},
		connect.Method{Spec: tenantMemberServiceGetSpec(), Handler: adapter.get},
		connect.Method{Spec: tenantMemberServiceListSpec(), Handler: adapter.list},
	)
}

// UnimplementedTenantMemberServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTenantMemberServiceHandler struct{}

func (UnimplementedTenantMemberServiceHandler) Create(context.Context, *v1.TenantMemberServiceCreateRequest) (*v1.TenantMemberServiceCreateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "tenant.api.v1.TenantMemberService.Create is not implemented")
}

func (UnimplementedTenantMemberServiceHandler) Update(context.Context, *v1.TenantMemberServiceUpdateRequest) (*v1.TenantMemberServiceUpdateResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "tenant.api.v1.TenantMemberService.Update is not implemented")
}

func (UnimplementedTenantMemberServiceHandler) Delete(context.Context, *v1.TenantMemberServiceDeleteRequest) (*v1.TenantMemberServiceDeleteResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "tenant.api.v1.TenantMemberService.Delete is not implemented")
}

func (UnimplementedTenantMemberServiceHandler) Get(context.Context, *v1.TenantMemberServiceGetRequest) (*v1.TenantMemberServiceGetResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "tenant.api.v1.TenantMemberService.Get is not implemented")
}

func (UnimplementedTenantMemberServiceHandler) List(context.Context, *v1.TenantMemberServiceListRequest) (*v1.TenantMemberServiceListResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "tenant.api.v1.TenantMemberService.List is not implemented")
}

type tenantMemberServiceClient struct {
	client *connect.Client
}

func (c *tenantMemberServiceClient) Create(ctx context.Context, req *v1.TenantMemberServiceCreateRequest) (*v1.TenantMemberServiceCreateResponse, error) {
	var res v1.TenantMemberServiceCreateResponse
	if err := c.client.CallUnary(ctx, tenantMemberServiceCreateSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *tenantMemberServiceClient) Update(ctx context.Context, req *v1.TenantMemberServiceUpdateRequest) (*v1.TenantMemberServiceUpdateResponse, error) {
	var res v1.TenantMemberServiceUpdateResponse
	if err := c.client.CallUnary(ctx, tenantMemberServiceUpdateSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *tenantMemberServiceClient) Delete(ctx context.Context, req *v1.TenantMemberServiceDeleteRequest) (*v1.TenantMemberServiceDeleteResponse, error) {
	var res v1.TenantMemberServiceDeleteResponse
	if err := c.client.CallUnary(ctx, tenantMemberServiceDeleteSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *tenantMemberServiceClient) Get(ctx context.Context, req *v1.TenantMemberServiceGetRequest) (*v1.TenantMemberServiceGetResponse, error) {
	var res v1.TenantMemberServiceGetResponse
	if err := c.client.CallUnary(ctx, tenantMemberServiceGetSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *tenantMemberServiceClient) List(ctx context.Context, req *v1.TenantMemberServiceListRequest) (*v1.TenantMemberServiceListResponse, error) {
	var res v1.TenantMemberServiceListResponse
	if err := c.client.CallUnary(ctx, tenantMemberServiceListSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type tenantMemberServiceHandler struct{ svc TenantMemberServiceHandler }

func (h tenantMemberServiceHandler) create(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.TenantMemberServiceCreateRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Create(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h tenantMemberServiceHandler) update(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.TenantMemberServiceUpdateRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Update(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h tenantMemberServiceHandler) delete(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.TenantMemberServiceDeleteRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Delete(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h tenantMemberServiceHandler) get(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.TenantMemberServiceGetRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Get(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h tenantMemberServiceHandler) list(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.TenantMemberServiceListRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.List(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
