// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tenant/api/v1/version.proto

package apiv1connect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	v1 "github.com/metal-stack/tenant-api/go/tenant/api/v1"
	sync "sync"
)

const (
	// VersionServiceName is the fully-qualified name of the VersionService service.
	VersionServiceName = "tenant.api.v1.VersionService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// VersionServiceGetProcedure is the procedure name of the VersionService's Get RPC.
	VersionServiceGetProcedure = "/tenant.api.v1.VersionService/Get"
)

var (
	versionServiceGetSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     v1.File_tenant_api_v1_version_proto.Services().ByName("VersionService").Methods().ByName("Get"),
			Procedure:  VersionServiceGetProcedure,
		}
	})
)

// VersionServiceClient is a client for the tenant.api.v1.VersionService service.
type VersionServiceClient interface {
	// Get the version of this server
	Get(context.Context, *v1.VersionServiceGetRequest) (*v1.VersionServiceGetResponse, error)
}

// NewVersionServiceClient constructs a client for the tenant.api.v1.VersionService service.
// Multiple service clients may share a single connect.Client.
func NewVersionServiceClient(client *connect.Client) VersionServiceClient {
	return &versionServiceClient{client: client}
}

// VersionServiceHandler is an implementation of the tenant.api.v1.VersionService service.
type VersionServiceHandler interface {
	// Get the version of this server
	Get(context.Context, *v1.VersionServiceGetRequest) (*v1.VersionServiceGetResponse, error)
}

// RegisterVersionServiceHandler registers svc as the tenant.api.v1.VersionService implementation on
// server.
func RegisterVersionServiceHandler(server *connect.Server, svc VersionServiceHandler) {
	adapter := versionServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: versionServiceGetSpec(), Handler: adapter.get},
	)
}

// UnimplementedVersionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedVersionServiceHandler struct{}

func (UnimplementedVersionServiceHandler) Get(context.Context, *v1.VersionServiceGetRequest) (*v1.VersionServiceGetResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "tenant.api.v1.VersionService.Get is not implemented")
}

type versionServiceClient struct {
	client *connect.Client
}

func (c *versionServiceClient) Get(ctx context.Context, req *v1.VersionServiceGetRequest) (*v1.VersionServiceGetResponse, error) {
	var res v1.VersionServiceGetResponse
	if err := c.client.CallUnary(ctx, versionServiceGetSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type versionServiceHandler struct{ svc VersionServiceHandler }

func (h versionServiceHandler) get(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req v1.VersionServiceGetRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.Get(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
