syntax = "proto3";

package api.v1;

import "api/v1/meta.proto";

// ProjectMemberService provides service methods to work with project members
service ProjectMemberService {
  // Create a project member ship
  rpc Create(ProjectMemberServiceCreateRequest) returns (ProjectMemberServiceCreateResponse);
  // Update a project member ship
  rpc Update(ProjectMemberServiceUpdateRequest) returns (ProjectMemberServiceUpdateResponse);
  // Delete a project member ship
  rpc Delete(ProjectMemberServiceDeleteRequest) returns (ProjectMemberServiceDeleteResponse);
  // Get a project member ship
  rpc Get(ProjectMemberServiceGetRequest) returns (ProjectMemberServiceGetResponse);
  // List project member ships
  rpc List(ProjectMemberServiceListRequest) returns (ProjectMemberServiceListResponse);
}

// ProjectMember is the database model
message ProjectMember {
  // Meta for a project member
  Meta meta = 1;
  // ProjectId of this project member
  string project_id = 2;
  // TenantId of this project member
  string tenant_id = 3;
  // Namespace introduces the possibility to associate memberships for different applications that use the masterdata-api as a backend.
  string namespace = 4;
}

// ProjectMemberServiceCreateRequest is the request payload to create a new project member
message ProjectMemberServiceCreateRequest {
  // ProjectMember to create
  ProjectMember project_member = 1;
}

// ProjectMemberServiceCreateResponse contains the project member
message ProjectMemberServiceCreateResponse {
  // ProjectMember is the response
  ProjectMember project_member = 1;
}

// ProjectMemberServiceUpdateRequest is the request payload to Update a project member
message ProjectMemberServiceUpdateRequest {
  // ProjectMember to update
  ProjectMember project_member = 1;
}

// ProjectMemberServiceUpdateResponse contains the project member
message ProjectMemberServiceUpdateResponse {
  // ProjectMember is the response
  ProjectMember project_member = 1;
}

// ProjectMemberServiceDeleteRequest is the request payload to delete a project member
message ProjectMemberServiceDeleteRequest {
  // Id of the project member to delete
  string id = 1;
}

// ProjectMemberServiceDeleteResponse contains the project member
message ProjectMemberServiceDeleteResponse {
  // ProjectMember is the response
  ProjectMember project_member = 1;
}

// ProjectMemberServiceGetRequest is the request payload to get a project member
message ProjectMemberServiceGetRequest {
  // Id of the project member to get
  string id = 1;
}

// ProjectMemberServiceGetResponse contains the project member
message ProjectMemberServiceGetResponse {
  // ProjectMember is the response
  ProjectMember project_member = 1;
}

// ProjectMemberServiceListRequest is the request payload to list project members
message ProjectMemberServiceListRequest {
  // ProjectId of project members to list
  optional string project_id = 1;
  // TenantId of project members to list
  optional string tenant_id = 2;
  // Annotations of project members to list
  map<string, string> annotations = 3;
  // Namespace of project members to list
  string namespace = 4;
}

// ProjectMemberServiceListResponse contains the project members
message ProjectMemberServiceListResponse {
  // ProjectMembers is the response
  repeated ProjectMember project_members = 1;
}
