syntax = "proto3";

package api.v1;

import "api/v1/meta.proto";

// ProjectMemberService provides service methods to work with project members
service ProjectMemberService {
  // Create a project member ship
  rpc Create(ProjectMemberCreateRequest) returns (ProjectMemberResponse);
  // Update a project member ship
  rpc Update(ProjectMemberUpdateRequest) returns (ProjectMemberResponse);
  // Delete a project member ship
  rpc Delete(ProjectMemberDeleteRequest) returns (ProjectMemberResponse);
  // Get a project member ship
  rpc Get(ProjectMemberGetRequest) returns (ProjectMemberResponse);
  // Find project member ships
  rpc Find(ProjectMemberFindRequest) returns (ProjectMemberListResponse);
}

// ProjectMember is the database model
message ProjectMember {
  // Meta for a project member
  Meta meta = 1;
  // ProjectId of this project member
  string project_id = 2;
  // TenantId of this project member
  string tenant_id = 3;
  // Namespace introduces the possibility to associate memberships for different applications that use the masterdata-api as a backend.
  string namespace = 4;
}

// ProjectMemberCreateRequest is the request payload to create a new project member
message ProjectMemberCreateRequest {
  // ProjectMember to create
  ProjectMember project_member = 1;
}

// ProjectMemberUpdateRequest is the request payload to Update a project member
message ProjectMemberUpdateRequest {
  // ProjectMember to update
  ProjectMember project_member = 1;
}

// ProjectMemberDeleteRequest is the request payload to delete a project member
message ProjectMemberDeleteRequest {
  // Id of the project member to delete
  string id = 1;
}

// ProjectMemberGetRequest is the request payload to get a project member
message ProjectMemberGetRequest {
  // Id of the project member to get
  string id = 1;
}

// ProjectMemberFindRequest is the request payload to find project members
message ProjectMemberFindRequest {
  // ProjectId of project members to find
  optional string project_id = 1;
  // TenantId of project members to find
  optional string tenant_id = 2;
  // Annotations of project members to find
  map<string, string> annotations = 3;
  // Namespace of project members to find
  string namespace = 4;
}

// ProjectMemberResponse contains the project member
message ProjectMemberResponse {
  // ProjectMember is the response
  ProjectMember project_member = 1;
}

// ProjectMemberListResponse contains the project members
message ProjectMemberListResponse {
  // ProjectMembers is the response
  repeated ProjectMember project_members = 1;
}
