syntax = "proto3";

package api.v1;

import "api/v1/meta.proto";

// TenantMemberService provides service methods to work with tenant members
service TenantMemberService {
  // Create a tenant member
  rpc Create(TenantMemberServiceCreateRequest) returns (TenantMemberResponse);
  // Update a tenant member
  rpc Update(TenantMemberServiceUpdateRequest) returns (TenantMemberResponse);
  // Delete a tenant member
  rpc Delete(TenantMemberServiceDeleteRequest) returns (TenantMemberResponse);
  // Get a tenant member
  rpc Get(TenantMemberServiceGetRequest) returns (TenantMemberResponse);
  // Find tenant members
  rpc Find(TenantMemberServiceFindRequest) returns (TenantMemberListResponse);
}

// TenantMember is the database model
message TenantMember {
  // Meta of the tenant member
  Meta meta = 1;
  // TenantId is the id of the parent tenant
  string tenant_id = 2;
  // MemberId is the id of the member tenant
  string member_id = 3;
  // Namespace introduces the possibility to associate memberships for different applications that use the masterdata-api as a backend.
  string namespace = 4;
}

// TenantMemberServiceCreateRequest is the request payload to create a tenant member
message TenantMemberServiceCreateRequest {
  // TenantMember to create
  TenantMember tenant_member = 1;
}

// TenantMemberServiceUpdateRequest is the request payload to update a tenant member
message TenantMemberServiceUpdateRequest {
  // TenantMember to update
  TenantMember tenant_member = 1;
}

// TenantMemberServiceDeleteRequest is the request payload to delete a tenant member
message TenantMemberServiceDeleteRequest {
  // Id of the tenant member to delete
  string id = 1;
}

// TenantMemberServiceGetRequest is the request payload to get a tenant member
message TenantMemberServiceGetRequest {
  // Id of the tenant member to get
  string id = 1;
}

// TenantMemberServiceFindRequest is the request payload to find tenant members
message TenantMemberServiceFindRequest {
  // TenantId of tenant members to find
  optional string tenant_id = 1;
  // MemberId of this tenant member to find
  optional string member_id = 2;
  // Annotations of tenant members to find
  map<string, string> annotations = 3;
  // Namespace
  string namespace = 4;
}

// TenantMemberResponse is the response payload of requests
message TenantMemberResponse {
  // TenantMember
  TenantMember tenant_member = 1;
}

// TenantMemberListResponse is the response payload of find requests
message TenantMemberListResponse {
  // TenantMembers
  repeated TenantMember tenant_members = 1;
}
