// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	"github.com/metal-stack/tenant-api/go/api/v1/apiv1connect"
	mock "github.com/stretchr/testify/mock"
)

// NewApiv1 creates a new instance of Apiv1. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApiv1(t interface {
	mock.TestingT
	Cleanup(func())
}) *Apiv1 {
	mock := &Apiv1{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Apiv1 is an autogenerated mock type for the Apiv1 type
type Apiv1 struct {
	mock.Mock
}

type Apiv1_Expecter struct {
	mock *mock.Mock
}

func (_m *Apiv1) EXPECT() *Apiv1_Expecter {
	return &Apiv1_Expecter{mock: &_m.Mock}
}

// Health provides a mock function for the type Apiv1
func (_mock *Apiv1) Health() apiv1connect.HealthServiceClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 apiv1connect.HealthServiceClient
	if returnFunc, ok := ret.Get(0).(func() apiv1connect.HealthServiceClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apiv1connect.HealthServiceClient)
		}
	}
	return r0
}

// Apiv1_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type Apiv1_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
func (_e *Apiv1_Expecter) Health() *Apiv1_Health_Call {
	return &Apiv1_Health_Call{Call: _e.mock.On("Health")}
}

func (_c *Apiv1_Health_Call) Run(run func()) *Apiv1_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Apiv1_Health_Call) Return(healthServiceClient apiv1connect.HealthServiceClient) *Apiv1_Health_Call {
	_c.Call.Return(healthServiceClient)
	return _c
}

func (_c *Apiv1_Health_Call) RunAndReturn(run func() apiv1connect.HealthServiceClient) *Apiv1_Health_Call {
	_c.Call.Return(run)
	return _c
}

// Project provides a mock function for the type Apiv1
func (_mock *Apiv1) Project() apiv1connect.ProjectServiceClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Project")
	}

	var r0 apiv1connect.ProjectServiceClient
	if returnFunc, ok := ret.Get(0).(func() apiv1connect.ProjectServiceClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apiv1connect.ProjectServiceClient)
		}
	}
	return r0
}

// Apiv1_Project_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Project'
type Apiv1_Project_Call struct {
	*mock.Call
}

// Project is a helper method to define mock.On call
func (_e *Apiv1_Expecter) Project() *Apiv1_Project_Call {
	return &Apiv1_Project_Call{Call: _e.mock.On("Project")}
}

func (_c *Apiv1_Project_Call) Run(run func()) *Apiv1_Project_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Apiv1_Project_Call) Return(projectServiceClient apiv1connect.ProjectServiceClient) *Apiv1_Project_Call {
	_c.Call.Return(projectServiceClient)
	return _c
}

func (_c *Apiv1_Project_Call) RunAndReturn(run func() apiv1connect.ProjectServiceClient) *Apiv1_Project_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectMember provides a mock function for the type Apiv1
func (_mock *Apiv1) ProjectMember() apiv1connect.ProjectMemberServiceClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProjectMember")
	}

	var r0 apiv1connect.ProjectMemberServiceClient
	if returnFunc, ok := ret.Get(0).(func() apiv1connect.ProjectMemberServiceClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apiv1connect.ProjectMemberServiceClient)
		}
	}
	return r0
}

// Apiv1_ProjectMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectMember'
type Apiv1_ProjectMember_Call struct {
	*mock.Call
}

// ProjectMember is a helper method to define mock.On call
func (_e *Apiv1_Expecter) ProjectMember() *Apiv1_ProjectMember_Call {
	return &Apiv1_ProjectMember_Call{Call: _e.mock.On("ProjectMember")}
}

func (_c *Apiv1_ProjectMember_Call) Run(run func()) *Apiv1_ProjectMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Apiv1_ProjectMember_Call) Return(projectMemberServiceClient apiv1connect.ProjectMemberServiceClient) *Apiv1_ProjectMember_Call {
	_c.Call.Return(projectMemberServiceClient)
	return _c
}

func (_c *Apiv1_ProjectMember_Call) RunAndReturn(run func() apiv1connect.ProjectMemberServiceClient) *Apiv1_ProjectMember_Call {
	_c.Call.Return(run)
	return _c
}

// Tenant provides a mock function for the type Apiv1
func (_mock *Apiv1) Tenant() apiv1connect.TenantServiceClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tenant")
	}

	var r0 apiv1connect.TenantServiceClient
	if returnFunc, ok := ret.Get(0).(func() apiv1connect.TenantServiceClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apiv1connect.TenantServiceClient)
		}
	}
	return r0
}

// Apiv1_Tenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tenant'
type Apiv1_Tenant_Call struct {
	*mock.Call
}

// Tenant is a helper method to define mock.On call
func (_e *Apiv1_Expecter) Tenant() *Apiv1_Tenant_Call {
	return &Apiv1_Tenant_Call{Call: _e.mock.On("Tenant")}
}

func (_c *Apiv1_Tenant_Call) Run(run func()) *Apiv1_Tenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Apiv1_Tenant_Call) Return(tenantServiceClient apiv1connect.TenantServiceClient) *Apiv1_Tenant_Call {
	_c.Call.Return(tenantServiceClient)
	return _c
}

func (_c *Apiv1_Tenant_Call) RunAndReturn(run func() apiv1connect.TenantServiceClient) *Apiv1_Tenant_Call {
	_c.Call.Return(run)
	return _c
}

// TenantMember provides a mock function for the type Apiv1
func (_mock *Apiv1) TenantMember() apiv1connect.TenantMemberServiceClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TenantMember")
	}

	var r0 apiv1connect.TenantMemberServiceClient
	if returnFunc, ok := ret.Get(0).(func() apiv1connect.TenantMemberServiceClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apiv1connect.TenantMemberServiceClient)
		}
	}
	return r0
}

// Apiv1_TenantMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TenantMember'
type Apiv1_TenantMember_Call struct {
	*mock.Call
}

// TenantMember is a helper method to define mock.On call
func (_e *Apiv1_Expecter) TenantMember() *Apiv1_TenantMember_Call {
	return &Apiv1_TenantMember_Call{Call: _e.mock.On("TenantMember")}
}

func (_c *Apiv1_TenantMember_Call) Run(run func()) *Apiv1_TenantMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Apiv1_TenantMember_Call) Return(tenantMemberServiceClient apiv1connect.TenantMemberServiceClient) *Apiv1_TenantMember_Call {
	_c.Call.Return(tenantMemberServiceClient)
	return _c
}

func (_c *Apiv1_TenantMember_Call) RunAndReturn(run func() apiv1connect.TenantMemberServiceClient) *Apiv1_TenantMember_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type Apiv1
func (_mock *Apiv1) Version() apiv1connect.VersionServiceClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 apiv1connect.VersionServiceClient
	if returnFunc, ok := ret.Get(0).(func() apiv1connect.VersionServiceClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(apiv1connect.VersionServiceClient)
		}
	}
	return r0
}

// Apiv1_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type Apiv1_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *Apiv1_Expecter) Version() *Apiv1_Version_Call {
	return &Apiv1_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *Apiv1_Version_Call) Run(run func()) *Apiv1_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Apiv1_Version_Call) Return(versionServiceClient apiv1connect.VersionServiceClient) *Apiv1_Version_Call {
	_c.Call.Return(versionServiceClient)
	return _c
}

func (_c *Apiv1_Version_Call) RunAndReturn(run func() apiv1connect.VersionServiceClient) *Apiv1_Version_Call {
	_c.Call.Return(run)
	return _c
}
