// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tenant/api/v1/project_member.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProjectMember is the database model
type ProjectMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Meta for a project member
	Meta *Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// ProjectId of this project member
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// TenantId of this project member
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Namespace introduces the possibility to associate memberships for different applications that use the masterdata-api as a backend.
	Namespace     string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMember) Reset() {
	*x = ProjectMember{}
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMember) ProtoMessage() {}

func (x *ProjectMember) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMember.ProtoReflect.Descriptor instead.
func (*ProjectMember) Descriptor() ([]byte, []int) {
	return file_tenant_api_v1_project_member_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectMember) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ProjectMember) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectMember) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ProjectMember) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// ProjectMemberServiceCreateRequest is the request payload to create a new project member
type ProjectMemberServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectMember to create
	ProjectMember *ProjectMember `protobuf:"bytes,1,opt,name=project_member,json=projectMember,proto3" json:"project_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceCreateRequest) Reset() {
	*x = ProjectMemberServiceCreateRequest{}
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceCreateRequest) ProtoMessage() {}

func (x *ProjectMemberServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_tenant_api_v1_project_member_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectMemberServiceCreateRequest) GetProjectMember() *ProjectMember {
	if x != nil {
		return x.ProjectMember
	}
	return nil
}

// ProjectMemberServiceCreateResponse contains the project member
type ProjectMemberServiceCreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectMember is the response
	ProjectMember *ProjectMember `protobuf:"bytes,1,opt,name=project_member,json=projectMember,proto3" json:"project_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceCreateResponse) Reset() {
	*x = ProjectMemberServiceCreateResponse{}
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceCreateResponse) ProtoMessage() {}

func (x *ProjectMemberServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_tenant_api_v1_project_member_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectMemberServiceCreateResponse) GetProjectMember() *ProjectMember {
	if x != nil {
		return x.ProjectMember
	}
	return nil
}

// ProjectMemberServiceUpdateRequest is the request payload to Update a project member
type ProjectMemberServiceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectMember to update
	ProjectMember *ProjectMember `protobuf:"bytes,1,opt,name=project_member,json=projectMember,proto3" json:"project_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceUpdateRequest) Reset() {
	*x = ProjectMemberServiceUpdateRequest{}
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceUpdateRequest) ProtoMessage() {}

func (x *ProjectMemberServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_tenant_api_v1_project_member_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectMemberServiceUpdateRequest) GetProjectMember() *ProjectMember {
	if x != nil {
		return x.ProjectMember
	}
	return nil
}

// ProjectMemberServiceUpdateResponse contains the project member
type ProjectMemberServiceUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectMember is the response
	ProjectMember *ProjectMember `protobuf:"bytes,1,opt,name=project_member,json=projectMember,proto3" json:"project_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceUpdateResponse) Reset() {
	*x = ProjectMemberServiceUpdateResponse{}
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceUpdateResponse) ProtoMessage() {}

func (x *ProjectMemberServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_tenant_api_v1_project_member_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectMemberServiceUpdateResponse) GetProjectMember() *ProjectMember {
	if x != nil {
		return x.ProjectMember
	}
	return nil
}

// ProjectMemberServiceDeleteRequest is the request payload to delete a project member
type ProjectMemberServiceDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the project member to delete
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceDeleteRequest) Reset() {
	*x = ProjectMemberServiceDeleteRequest{}
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceDeleteRequest) ProtoMessage() {}

func (x *ProjectMemberServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_tenant_api_v1_project_member_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectMemberServiceDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ProjectMemberServiceDeleteResponse contains the project member
type ProjectMemberServiceDeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectMember is the response
	ProjectMember *ProjectMember `protobuf:"bytes,1,opt,name=project_member,json=projectMember,proto3" json:"project_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceDeleteResponse) Reset() {
	*x = ProjectMemberServiceDeleteResponse{}
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceDeleteResponse) ProtoMessage() {}

func (x *ProjectMemberServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_tenant_api_v1_project_member_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectMemberServiceDeleteResponse) GetProjectMember() *ProjectMember {
	if x != nil {
		return x.ProjectMember
	}
	return nil
}

// ProjectMemberServiceGetRequest is the request payload to get a project member
type ProjectMemberServiceGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the project member to get
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceGetRequest) Reset() {
	*x = ProjectMemberServiceGetRequest{}
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceGetRequest) ProtoMessage() {}

func (x *ProjectMemberServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceGetRequest.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_tenant_api_v1_project_member_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectMemberServiceGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ProjectMemberServiceGetResponse contains the project member
type ProjectMemberServiceGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectMember is the response
	ProjectMember *ProjectMember `protobuf:"bytes,1,opt,name=project_member,json=projectMember,proto3" json:"project_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceGetResponse) Reset() {
	*x = ProjectMemberServiceGetResponse{}
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceGetResponse) ProtoMessage() {}

func (x *ProjectMemberServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceGetResponse.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_tenant_api_v1_project_member_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectMemberServiceGetResponse) GetProjectMember() *ProjectMember {
	if x != nil {
		return x.ProjectMember
	}
	return nil
}

// ProjectMemberServiceListRequest is the request payload to list project members
type ProjectMemberServiceListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectId of project members to list
	ProjectId *string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	// TenantId of project members to list
	TenantId *string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Annotations of project members to list
	Annotations map[string]string `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Namespace of project members to list
	Namespace     string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceListRequest) Reset() {
	*x = ProjectMemberServiceListRequest{}
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceListRequest) ProtoMessage() {}

func (x *ProjectMemberServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceListRequest.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceListRequest) Descriptor() ([]byte, []int) {
	return file_tenant_api_v1_project_member_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectMemberServiceListRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *ProjectMemberServiceListRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *ProjectMemberServiceListRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ProjectMemberServiceListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// ProjectMemberServiceListResponse contains the project members
type ProjectMemberServiceListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectMembers is the response
	ProjectMembers []*ProjectMember `protobuf:"bytes,1,rep,name=project_members,json=projectMembers,proto3" json:"project_members,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectMemberServiceListResponse) Reset() {
	*x = ProjectMemberServiceListResponse{}
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceListResponse) ProtoMessage() {}

func (x *ProjectMemberServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_api_v1_project_member_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceListResponse.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceListResponse) Descriptor() ([]byte, []int) {
	return file_tenant_api_v1_project_member_proto_rawDescGZIP(), []int{10}
}

func (x *ProjectMemberServiceListResponse) GetProjectMembers() []*ProjectMember {
	if x != nil {
		return x.ProjectMembers
	}
	return nil
}

var File_tenant_api_v1_project_member_proto protoreflect.FileDescriptor

const file_tenant_api_v1_project_member_proto_rawDesc = "" +
	"\n" +
	"\"tenant/api/v1/project_member.proto\x12\rtenant.api.v1\x1a\x18tenant/api/v1/meta.proto\"\x92\x01\n" +
	"\rProjectMember\x12'\n" +
	"\x04meta\x18\x01 \x01(\v2\x13.tenant.api.v1.MetaR\x04meta\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"h\n" +
	"!ProjectMemberServiceCreateRequest\x12C\n" +
	"\x0eproject_member\x18\x01 \x01(\v2\x1c.tenant.api.v1.ProjectMemberR\rprojectMember\"i\n" +
	"\"ProjectMemberServiceCreateResponse\x12C\n" +
	"\x0eproject_member\x18\x01 \x01(\v2\x1c.tenant.api.v1.ProjectMemberR\rprojectMember\"h\n" +
	"!ProjectMemberServiceUpdateRequest\x12C\n" +
	"\x0eproject_member\x18\x01 \x01(\v2\x1c.tenant.api.v1.ProjectMemberR\rprojectMember\"i\n" +
	"\"ProjectMemberServiceUpdateResponse\x12C\n" +
	"\x0eproject_member\x18\x01 \x01(\v2\x1c.tenant.api.v1.ProjectMemberR\rprojectMember\"3\n" +
	"!ProjectMemberServiceDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"i\n" +
	"\"ProjectMemberServiceDeleteResponse\x12C\n" +
	"\x0eproject_member\x18\x01 \x01(\v2\x1c.tenant.api.v1.ProjectMemberR\rprojectMember\"0\n" +
	"\x1eProjectMemberServiceGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"f\n" +
	"\x1fProjectMemberServiceGetResponse\x12C\n" +
	"\x0eproject_member\x18\x01 \x01(\v2\x1c.tenant.api.v1.ProjectMemberR\rprojectMember\"\xc5\x02\n" +
	"\x1fProjectMemberServiceListRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tH\x00R\tprojectId\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x02 \x01(\tH\x01R\btenantId\x88\x01\x01\x12a\n" +
	"\vannotations\x18\x03 \x03(\v2?.tenant.api.v1.ProjectMemberServiceListRequest.AnnotationsEntryR\vannotations\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_project_idB\f\n" +
	"\n" +
	"_tenant_id\"i\n" +
	" ProjectMemberServiceListResponse\x12E\n" +
	"\x0fproject_members\x18\x01 \x03(\v2\x1c.tenant.api.v1.ProjectMemberR\x0eprojectMembers2\xb2\x04\n" +
	"\x14ProjectMemberService\x12m\n" +
	"\x06Create\x120.tenant.api.v1.ProjectMemberServiceCreateRequest\x1a1.tenant.api.v1.ProjectMemberServiceCreateResponse\x12m\n" +
	"\x06Update\x120.tenant.api.v1.ProjectMemberServiceUpdateRequest\x1a1.tenant.api.v1.ProjectMemberServiceUpdateResponse\x12m\n" +
	"\x06Delete\x120.tenant.api.v1.ProjectMemberServiceDeleteRequest\x1a1.tenant.api.v1.ProjectMemberServiceDeleteResponse\x12d\n" +
	"\x03Get\x12-.tenant.api.v1.ProjectMemberServiceGetRequest\x1a..tenant.api.v1.ProjectMemberServiceGetResponse\x12g\n" +
	"\x04List\x12..tenant.api.v1.ProjectMemberServiceListRequest\x1a/.tenant.api.v1.ProjectMemberServiceListResponseB\xb7\x01\n" +
	"\x11com.tenant.api.v1B\x12ProjectMemberProtoP\x01Z8github.com/metal-stack/tenant-api/go/tenant/api/v1;apiv1\xa2\x02\x03TAX\xaa\x02\rTenant.Api.V1\xca\x02\rTenant\\Api\\V1\xe2\x02\x19Tenant\\Api\\V1\\GPBMetadata\xea\x02\x0fTenant::Api::V1b\x06proto3"

var (
	file_tenant_api_v1_project_member_proto_rawDescOnce sync.Once
	file_tenant_api_v1_project_member_proto_rawDescData []byte
)

func file_tenant_api_v1_project_member_proto_rawDescGZIP() []byte {
	file_tenant_api_v1_project_member_proto_rawDescOnce.Do(func() {
		file_tenant_api_v1_project_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_api_v1_project_member_proto_rawDesc), len(file_tenant_api_v1_project_member_proto_rawDesc)))
	})
	return file_tenant_api_v1_project_member_proto_rawDescData
}

var file_tenant_api_v1_project_member_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tenant_api_v1_project_member_proto_goTypes = []any{
	(*ProjectMember)(nil),                      // 0: tenant.api.v1.ProjectMember
	(*ProjectMemberServiceCreateRequest)(nil),  // 1: tenant.api.v1.ProjectMemberServiceCreateRequest
	(*ProjectMemberServiceCreateResponse)(nil), // 2: tenant.api.v1.ProjectMemberServiceCreateResponse
	(*ProjectMemberServiceUpdateRequest)(nil),  // 3: tenant.api.v1.ProjectMemberServiceUpdateRequest
	(*ProjectMemberServiceUpdateResponse)(nil), // 4: tenant.api.v1.ProjectMemberServiceUpdateResponse
	(*ProjectMemberServiceDeleteRequest)(nil),  // 5: tenant.api.v1.ProjectMemberServiceDeleteRequest
	(*ProjectMemberServiceDeleteResponse)(nil), // 6: tenant.api.v1.ProjectMemberServiceDeleteResponse
	(*ProjectMemberServiceGetRequest)(nil),     // 7: tenant.api.v1.ProjectMemberServiceGetRequest
	(*ProjectMemberServiceGetResponse)(nil),    // 8: tenant.api.v1.ProjectMemberServiceGetResponse
	(*ProjectMemberServiceListRequest)(nil),    // 9: tenant.api.v1.ProjectMemberServiceListRequest
	(*ProjectMemberServiceListResponse)(nil),   // 10: tenant.api.v1.ProjectMemberServiceListResponse
	nil,                                        // 11: tenant.api.v1.ProjectMemberServiceListRequest.AnnotationsEntry
	(*Meta)(nil),                               // 12: tenant.api.v1.Meta
}
var file_tenant_api_v1_project_member_proto_depIdxs = []int32{
	12, // 0: tenant.api.v1.ProjectMember.meta:type_name -> tenant.api.v1.Meta
	0,  // 1: tenant.api.v1.ProjectMemberServiceCreateRequest.project_member:type_name -> tenant.api.v1.ProjectMember
	0,  // 2: tenant.api.v1.ProjectMemberServiceCreateResponse.project_member:type_name -> tenant.api.v1.ProjectMember
	0,  // 3: tenant.api.v1.ProjectMemberServiceUpdateRequest.project_member:type_name -> tenant.api.v1.ProjectMember
	0,  // 4: tenant.api.v1.ProjectMemberServiceUpdateResponse.project_member:type_name -> tenant.api.v1.ProjectMember
	0,  // 5: tenant.api.v1.ProjectMemberServiceDeleteResponse.project_member:type_name -> tenant.api.v1.ProjectMember
	0,  // 6: tenant.api.v1.ProjectMemberServiceGetResponse.project_member:type_name -> tenant.api.v1.ProjectMember
	11, // 7: tenant.api.v1.ProjectMemberServiceListRequest.annotations:type_name -> tenant.api.v1.ProjectMemberServiceListRequest.AnnotationsEntry
	0,  // 8: tenant.api.v1.ProjectMemberServiceListResponse.project_members:type_name -> tenant.api.v1.ProjectMember
	1,  // 9: tenant.api.v1.ProjectMemberService.Create:input_type -> tenant.api.v1.ProjectMemberServiceCreateRequest
	3,  // 10: tenant.api.v1.ProjectMemberService.Update:input_type -> tenant.api.v1.ProjectMemberServiceUpdateRequest
	5,  // 11: tenant.api.v1.ProjectMemberService.Delete:input_type -> tenant.api.v1.ProjectMemberServiceDeleteRequest
	7,  // 12: tenant.api.v1.ProjectMemberService.Get:input_type -> tenant.api.v1.ProjectMemberServiceGetRequest
	9,  // 13: tenant.api.v1.ProjectMemberService.List:input_type -> tenant.api.v1.ProjectMemberServiceListRequest
	2,  // 14: tenant.api.v1.ProjectMemberService.Create:output_type -> tenant.api.v1.ProjectMemberServiceCreateResponse
	4,  // 15: tenant.api.v1.ProjectMemberService.Update:output_type -> tenant.api.v1.ProjectMemberServiceUpdateResponse
	6,  // 16: tenant.api.v1.ProjectMemberService.Delete:output_type -> tenant.api.v1.ProjectMemberServiceDeleteResponse
	8,  // 17: tenant.api.v1.ProjectMemberService.Get:output_type -> tenant.api.v1.ProjectMemberServiceGetResponse
	10, // 18: tenant.api.v1.ProjectMemberService.List:output_type -> tenant.api.v1.ProjectMemberServiceListResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_tenant_api_v1_project_member_proto_init() }
func file_tenant_api_v1_project_member_proto_init() {
	if File_tenant_api_v1_project_member_proto != nil {
		return
	}
	file_tenant_api_v1_meta_proto_init()
	file_tenant_api_v1_project_member_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_api_v1_project_member_proto_rawDesc), len(file_tenant_api_v1_project_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenant_api_v1_project_member_proto_goTypes,
		DependencyIndexes: file_tenant_api_v1_project_member_proto_depIdxs,
		MessageInfos:      file_tenant_api_v1_project_member_proto_msgTypes,
	}.Build()
	File_tenant_api_v1_project_member_proto = out.File
	file_tenant_api_v1_project_member_proto_goTypes = nil
	file_tenant_api_v1_project_member_proto_depIdxs = nil
}
