// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/project.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Project is the database model
type Project struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Meta for a project
	Meta *Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Name of the project
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description of this project
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// TenantId to which this project belongs to
	TenantId      string `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_api_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// ProjectServiceCreateRequest is the request payload to create a new project
type ProjectServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project to create
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceCreateRequest) Reset() {
	*x = ProjectServiceCreateRequest{}
	mi := &file_api_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceCreateRequest) ProtoMessage() {}

func (x *ProjectServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectServiceCreateRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceCreateResponse contains the response payload of a project create request
type ProjectServiceCreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the response
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceCreateResponse) Reset() {
	*x = ProjectServiceCreateResponse{}
	mi := &file_api_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceCreateResponse) ProtoMessage() {}

func (x *ProjectServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectServiceCreateResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceUpdateRequest is the request payload to update a project
type ProjectServiceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project to update
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceUpdateRequest) Reset() {
	*x = ProjectServiceUpdateRequest{}
	mi := &file_api_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceUpdateRequest) ProtoMessage() {}

func (x *ProjectServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectServiceUpdateRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceUpdateResponse contains the response payload of a project update request
type ProjectServiceUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the response
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceUpdateResponse) Reset() {
	*x = ProjectServiceUpdateResponse{}
	mi := &file_api_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceUpdateResponse) ProtoMessage() {}

func (x *ProjectServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectServiceUpdateResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceDeleteRequest is the request payload to delete a project
type ProjectServiceDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the project to delete
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceDeleteRequest) Reset() {
	*x = ProjectServiceDeleteRequest{}
	mi := &file_api_v1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceDeleteRequest) ProtoMessage() {}

func (x *ProjectServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectServiceDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ProjectServiceDeleteResponse contains the response payload of a project delete request
type ProjectServiceDeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the response
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceDeleteResponse) Reset() {
	*x = ProjectServiceDeleteResponse{}
	mi := &file_api_v1_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceDeleteResponse) ProtoMessage() {}

func (x *ProjectServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectServiceDeleteResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceGetRequest is the request payload to get a project
type ProjectServiceGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the project to get
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceGetRequest) Reset() {
	*x = ProjectServiceGetRequest{}
	mi := &file_api_v1_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceGetRequest) ProtoMessage() {}

func (x *ProjectServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceGetRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectServiceGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ProjectServiceGetResponse contains the response payload of a project get request
type ProjectServiceGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the response
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceGetResponse) Reset() {
	*x = ProjectServiceGetResponse{}
	mi := &file_api_v1_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceGetResponse) ProtoMessage() {}

func (x *ProjectServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceGetResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectServiceGetResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceGetHistoryRequest is the request payload to get the history of a project
type ProjectServiceGetHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the project to get the history for
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// At the timestamp at which the history should get returned
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceGetHistoryRequest) Reset() {
	*x = ProjectServiceGetHistoryRequest{}
	mi := &file_api_v1_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceGetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceGetHistoryRequest) ProtoMessage() {}

func (x *ProjectServiceGetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceGetHistoryRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceGetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectServiceGetHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectServiceGetHistoryRequest) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

// ProjectServiceGetHistoryResponse contains the response payload of a project get history request
type ProjectServiceGetHistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Project is the response
	Project       *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceGetHistoryResponse) Reset() {
	*x = ProjectServiceGetHistoryResponse{}
	mi := &file_api_v1_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceGetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceGetHistoryResponse) ProtoMessage() {}

func (x *ProjectServiceGetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceGetHistoryResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceGetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{10}
}

func (x *ProjectServiceGetHistoryResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

// ProjectServiceListRequest is the request payload to list projects
type ProjectServiceListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Paging spec of this find request
	Paging *Paging `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	// Annotations of projects to find
	Annotations map[string]string `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Id of the project to find
	Id *string `protobuf:"bytes,3,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Name of the project to find
	Name *string `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Description of the project to find
	Description *string `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// TenantId of the projects to find
	TenantId *string `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Labels of the projects to find
	Labels        []string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceListRequest) Reset() {
	*x = ProjectServiceListRequest{}
	mi := &file_api_v1_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceListRequest) ProtoMessage() {}

func (x *ProjectServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceListRequest.ProtoReflect.Descriptor instead.
func (*ProjectServiceListRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{11}
}

func (x *ProjectServiceListRequest) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ProjectServiceListRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ProjectServiceListRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ProjectServiceListRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ProjectServiceListRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ProjectServiceListRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *ProjectServiceListRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ProjectListResponse contains the projects
type ProjectServiceListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Projects is the response
	Projects []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	// next_page_token is used for pagination, returns the next page to be fetched and must then be provided in the list request.
	NextPage      *uint64 `protobuf:"varint,2,opt,name=next_page,json=nextPage,proto3,oneof" json:"next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectServiceListResponse) Reset() {
	*x = ProjectServiceListResponse{}
	mi := &file_api_v1_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectServiceListResponse) ProtoMessage() {}

func (x *ProjectServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectServiceListResponse.ProtoReflect.Descriptor instead.
func (*ProjectServiceListResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{12}
}

func (x *ProjectServiceListResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ProjectServiceListResponse) GetNextPage() uint64 {
	if x != nil && x.NextPage != nil {
		return *x.NextPage
	}
	return 0
}

var File_api_v1_project_proto protoreflect.FileDescriptor

const file_api_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/project.proto\x12\x06api.v1\x1a\x13api/v1/common.proto\x1a\x11api/v1/meta.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n" +
	"\aProject\x12 \n" +
	"\x04meta\x18\x01 \x01(\v2\f.api.v1.MetaR\x04meta\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"H\n" +
	"\x1bProjectServiceCreateRequest\x12)\n" +
	"\aproject\x18\x01 \x01(\v2\x0f.api.v1.ProjectR\aproject\"I\n" +
	"\x1cProjectServiceCreateResponse\x12)\n" +
	"\aproject\x18\x01 \x01(\v2\x0f.api.v1.ProjectR\aproject\"H\n" +
	"\x1bProjectServiceUpdateRequest\x12)\n" +
	"\aproject\x18\x01 \x01(\v2\x0f.api.v1.ProjectR\aproject\"I\n" +
	"\x1cProjectServiceUpdateResponse\x12)\n" +
	"\aproject\x18\x01 \x01(\v2\x0f.api.v1.ProjectR\aproject\"-\n" +
	"\x1bProjectServiceDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x1cProjectServiceDeleteResponse\x12)\n" +
	"\aproject\x18\x01 \x01(\v2\x0f.api.v1.ProjectR\aproject\"*\n" +
	"\x18ProjectServiceGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x19ProjectServiceGetResponse\x12)\n" +
	"\aproject\x18\x01 \x01(\v2\x0f.api.v1.ProjectR\aproject\"]\n" +
	"\x1fProjectServiceGetHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"M\n" +
	" ProjectServiceGetHistoryResponse\x12)\n" +
	"\aproject\x18\x01 \x01(\v2\x0f.api.v1.ProjectR\aproject\"\x96\x03\n" +
	"\x19ProjectServiceListRequest\x12&\n" +
	"\x06paging\x18\x01 \x01(\v2\x0e.api.v1.PagingR\x06paging\x12T\n" +
	"\vannotations\x18\x02 \x03(\v22.api.v1.ProjectServiceListRequest.AnnotationsEntryR\vannotations\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x02R\vdescription\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x06 \x01(\tH\x03R\btenantId\x88\x01\x01\x12\x16\n" +
	"\x06labels\x18\a \x03(\tR\x06labels\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_tenant_id\"y\n" +
	"\x1aProjectServiceListResponse\x12+\n" +
	"\bprojects\x18\x01 \x03(\v2\x0f.api.v1.ProjectR\bprojects\x12 \n" +
	"\tnext_page\x18\x02 \x01(\x04H\x00R\bnextPage\x88\x01\x01B\f\n" +
	"\n" +
	"_next_page2\x8b\x04\n" +
	"\x0eProjectService\x12S\n" +
	"\x06Create\x12#.api.v1.ProjectServiceCreateRequest\x1a$.api.v1.ProjectServiceCreateResponse\x12S\n" +
	"\x06Update\x12#.api.v1.ProjectServiceUpdateRequest\x1a$.api.v1.ProjectServiceUpdateResponse\x12S\n" +
	"\x06Delete\x12#.api.v1.ProjectServiceDeleteRequest\x1a$.api.v1.ProjectServiceDeleteResponse\x12J\n" +
	"\x03Get\x12 .api.v1.ProjectServiceGetRequest\x1a!.api.v1.ProjectServiceGetResponse\x12_\n" +
	"\n" +
	"GetHistory\x12'.api.v1.ProjectServiceGetHistoryRequest\x1a(.api.v1.ProjectServiceGetHistoryResponse\x12M\n" +
	"\x04List\x12!.api.v1.ProjectServiceListRequest\x1a\".api.v1.ProjectServiceListResponseB\x86\x01\n" +
	"\n" +
	"com.api.v1B\fProjectProtoP\x01Z1github.com/metal-stack/tenant-api/go/api/v1;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var (
	file_api_v1_project_proto_rawDescOnce sync.Once
	file_api_v1_project_proto_rawDescData []byte
)

func file_api_v1_project_proto_rawDescGZIP() []byte {
	file_api_v1_project_proto_rawDescOnce.Do(func() {
		file_api_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_project_proto_rawDesc), len(file_api_v1_project_proto_rawDesc)))
	})
	return file_api_v1_project_proto_rawDescData
}

var file_api_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_v1_project_proto_goTypes = []any{
	(*Project)(nil),                          // 0: api.v1.Project
	(*ProjectServiceCreateRequest)(nil),      // 1: api.v1.ProjectServiceCreateRequest
	(*ProjectServiceCreateResponse)(nil),     // 2: api.v1.ProjectServiceCreateResponse
	(*ProjectServiceUpdateRequest)(nil),      // 3: api.v1.ProjectServiceUpdateRequest
	(*ProjectServiceUpdateResponse)(nil),     // 4: api.v1.ProjectServiceUpdateResponse
	(*ProjectServiceDeleteRequest)(nil),      // 5: api.v1.ProjectServiceDeleteRequest
	(*ProjectServiceDeleteResponse)(nil),     // 6: api.v1.ProjectServiceDeleteResponse
	(*ProjectServiceGetRequest)(nil),         // 7: api.v1.ProjectServiceGetRequest
	(*ProjectServiceGetResponse)(nil),        // 8: api.v1.ProjectServiceGetResponse
	(*ProjectServiceGetHistoryRequest)(nil),  // 9: api.v1.ProjectServiceGetHistoryRequest
	(*ProjectServiceGetHistoryResponse)(nil), // 10: api.v1.ProjectServiceGetHistoryResponse
	(*ProjectServiceListRequest)(nil),        // 11: api.v1.ProjectServiceListRequest
	(*ProjectServiceListResponse)(nil),       // 12: api.v1.ProjectServiceListResponse
	nil,                                      // 13: api.v1.ProjectServiceListRequest.AnnotationsEntry
	(*Meta)(nil),                             // 14: api.v1.Meta
	(*timestamppb.Timestamp)(nil),            // 15: google.protobuf.Timestamp
	(*Paging)(nil),                           // 16: api.v1.Paging
}
var file_api_v1_project_proto_depIdxs = []int32{
	14, // 0: api.v1.Project.meta:type_name -> api.v1.Meta
	0,  // 1: api.v1.ProjectServiceCreateRequest.project:type_name -> api.v1.Project
	0,  // 2: api.v1.ProjectServiceCreateResponse.project:type_name -> api.v1.Project
	0,  // 3: api.v1.ProjectServiceUpdateRequest.project:type_name -> api.v1.Project
	0,  // 4: api.v1.ProjectServiceUpdateResponse.project:type_name -> api.v1.Project
	0,  // 5: api.v1.ProjectServiceDeleteResponse.project:type_name -> api.v1.Project
	0,  // 6: api.v1.ProjectServiceGetResponse.project:type_name -> api.v1.Project
	15, // 7: api.v1.ProjectServiceGetHistoryRequest.at:type_name -> google.protobuf.Timestamp
	0,  // 8: api.v1.ProjectServiceGetHistoryResponse.project:type_name -> api.v1.Project
	16, // 9: api.v1.ProjectServiceListRequest.paging:type_name -> api.v1.Paging
	13, // 10: api.v1.ProjectServiceListRequest.annotations:type_name -> api.v1.ProjectServiceListRequest.AnnotationsEntry
	0,  // 11: api.v1.ProjectServiceListResponse.projects:type_name -> api.v1.Project
	1,  // 12: api.v1.ProjectService.Create:input_type -> api.v1.ProjectServiceCreateRequest
	3,  // 13: api.v1.ProjectService.Update:input_type -> api.v1.ProjectServiceUpdateRequest
	5,  // 14: api.v1.ProjectService.Delete:input_type -> api.v1.ProjectServiceDeleteRequest
	7,  // 15: api.v1.ProjectService.Get:input_type -> api.v1.ProjectServiceGetRequest
	9,  // 16: api.v1.ProjectService.GetHistory:input_type -> api.v1.ProjectServiceGetHistoryRequest
	11, // 17: api.v1.ProjectService.List:input_type -> api.v1.ProjectServiceListRequest
	2,  // 18: api.v1.ProjectService.Create:output_type -> api.v1.ProjectServiceCreateResponse
	4,  // 19: api.v1.ProjectService.Update:output_type -> api.v1.ProjectServiceUpdateResponse
	6,  // 20: api.v1.ProjectService.Delete:output_type -> api.v1.ProjectServiceDeleteResponse
	8,  // 21: api.v1.ProjectService.Get:output_type -> api.v1.ProjectServiceGetResponse
	10, // 22: api.v1.ProjectService.GetHistory:output_type -> api.v1.ProjectServiceGetHistoryResponse
	12, // 23: api.v1.ProjectService.List:output_type -> api.v1.ProjectServiceListResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_v1_project_proto_init() }
func file_api_v1_project_proto_init() {
	if File_api_v1_project_proto != nil {
		return
	}
	file_api_v1_common_proto_init()
	file_api_v1_meta_proto_init()
	file_api_v1_project_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_v1_project_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_project_proto_rawDesc), len(file_api_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_project_proto_goTypes,
		DependencyIndexes: file_api_v1_project_proto_depIdxs,
		MessageInfos:      file_api_v1_project_proto_msgTypes,
	}.Build()
	File_api_v1_project_proto = out.File
	file_api_v1_project_proto_goTypes = nil
	file_api_v1_project_proto_depIdxs = nil
}
