// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/project_member.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProjectMember is the database model
type ProjectMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Meta for a project member
	Meta *Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// ProjectId of this project member
	ProjectId string `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// TenantId of this project member
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Namespace introduces the possibility to associate memberships for different applications that use the masterdata-api as a backend.
	Namespace     string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMember) Reset() {
	*x = ProjectMember{}
	mi := &file_api_v1_project_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMember) ProtoMessage() {}

func (x *ProjectMember) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMember.ProtoReflect.Descriptor instead.
func (*ProjectMember) Descriptor() ([]byte, []int) {
	return file_api_v1_project_member_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectMember) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *ProjectMember) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectMember) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ProjectMember) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// ProjectMemberServiceCreateRequest is the request payload to create a new project member
type ProjectMemberServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectMember to create
	ProjectMember *ProjectMember `protobuf:"bytes,1,opt,name=project_member,json=projectMember,proto3" json:"project_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceCreateRequest) Reset() {
	*x = ProjectMemberServiceCreateRequest{}
	mi := &file_api_v1_project_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceCreateRequest) ProtoMessage() {}

func (x *ProjectMemberServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_member_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectMemberServiceCreateRequest) GetProjectMember() *ProjectMember {
	if x != nil {
		return x.ProjectMember
	}
	return nil
}

// ProjectMemberServiceUpdateRequest is the request payload to Update a project member
type ProjectMemberServiceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectMember to update
	ProjectMember *ProjectMember `protobuf:"bytes,1,opt,name=project_member,json=projectMember,proto3" json:"project_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceUpdateRequest) Reset() {
	*x = ProjectMemberServiceUpdateRequest{}
	mi := &file_api_v1_project_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceUpdateRequest) ProtoMessage() {}

func (x *ProjectMemberServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_member_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectMemberServiceUpdateRequest) GetProjectMember() *ProjectMember {
	if x != nil {
		return x.ProjectMember
	}
	return nil
}

// ProjectMemberServiceDeleteRequest is the request payload to delete a project member
type ProjectMemberServiceDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the project member to delete
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceDeleteRequest) Reset() {
	*x = ProjectMemberServiceDeleteRequest{}
	mi := &file_api_v1_project_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceDeleteRequest) ProtoMessage() {}

func (x *ProjectMemberServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_member_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectMemberServiceDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ProjectMemberServiceGetRequest is the request payload to get a project member
type ProjectMemberServiceGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the project member to get
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceGetRequest) Reset() {
	*x = ProjectMemberServiceGetRequest{}
	mi := &file_api_v1_project_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceGetRequest) ProtoMessage() {}

func (x *ProjectMemberServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceGetRequest.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_member_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectMemberServiceGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ProjectMemberServiceFindRequest is the request payload to find project members
type ProjectMemberServiceFindRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectId of project members to find
	ProjectId *string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	// TenantId of project members to find
	TenantId *string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// Annotations of project members to find
	Annotations map[string]string `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Namespace of project members to find
	Namespace     string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberServiceFindRequest) Reset() {
	*x = ProjectMemberServiceFindRequest{}
	mi := &file_api_v1_project_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberServiceFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberServiceFindRequest) ProtoMessage() {}

func (x *ProjectMemberServiceFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberServiceFindRequest.ProtoReflect.Descriptor instead.
func (*ProjectMemberServiceFindRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_member_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectMemberServiceFindRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *ProjectMemberServiceFindRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *ProjectMemberServiceFindRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ProjectMemberServiceFindRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// ProjectMemberResponse contains the project member
type ProjectMemberResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectMember is the response
	ProjectMember *ProjectMember `protobuf:"bytes,1,opt,name=project_member,json=projectMember,proto3" json:"project_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMemberResponse) Reset() {
	*x = ProjectMemberResponse{}
	mi := &file_api_v1_project_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberResponse) ProtoMessage() {}

func (x *ProjectMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberResponse.ProtoReflect.Descriptor instead.
func (*ProjectMemberResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_project_member_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectMemberResponse) GetProjectMember() *ProjectMember {
	if x != nil {
		return x.ProjectMember
	}
	return nil
}

// ProjectMemberListResponse contains the project members
type ProjectMemberListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProjectMembers is the response
	ProjectMembers []*ProjectMember `protobuf:"bytes,1,rep,name=project_members,json=projectMembers,proto3" json:"project_members,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectMemberListResponse) Reset() {
	*x = ProjectMemberListResponse{}
	mi := &file_api_v1_project_member_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMemberListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMemberListResponse) ProtoMessage() {}

func (x *ProjectMemberListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_member_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMemberListResponse.ProtoReflect.Descriptor instead.
func (*ProjectMemberListResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_project_member_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectMemberListResponse) GetProjectMembers() []*ProjectMember {
	if x != nil {
		return x.ProjectMembers
	}
	return nil
}

var File_api_v1_project_member_proto protoreflect.FileDescriptor

const file_api_v1_project_member_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/v1/project_member.proto\x12\x06api.v1\x1a\x11api/v1/meta.proto\"\x8b\x01\n" +
	"\rProjectMember\x12 \n" +
	"\x04meta\x18\x01 \x01(\v2\f.api.v1.MetaR\x04meta\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"a\n" +
	"!ProjectMemberServiceCreateRequest\x12<\n" +
	"\x0eproject_member\x18\x01 \x01(\v2\x15.api.v1.ProjectMemberR\rprojectMember\"a\n" +
	"!ProjectMemberServiceUpdateRequest\x12<\n" +
	"\x0eproject_member\x18\x01 \x01(\v2\x15.api.v1.ProjectMemberR\rprojectMember\"3\n" +
	"!ProjectMemberServiceDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x1eProjectMemberServiceGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbe\x02\n" +
	"\x1fProjectMemberServiceFindRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tH\x00R\tprojectId\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x02 \x01(\tH\x01R\btenantId\x88\x01\x01\x12Z\n" +
	"\vannotations\x18\x03 \x03(\v28.api.v1.ProjectMemberServiceFindRequest.AnnotationsEntryR\vannotations\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\r\n" +
	"\v_project_idB\f\n" +
	"\n" +
	"_tenant_id\"U\n" +
	"\x15ProjectMemberResponse\x12<\n" +
	"\x0eproject_member\x18\x01 \x01(\v2\x15.api.v1.ProjectMemberR\rprojectMember\"[\n" +
	"\x19ProjectMemberListResponse\x12>\n" +
	"\x0fproject_members\x18\x01 \x03(\v2\x15.api.v1.ProjectMemberR\x0eprojectMembers2\xb4\x03\n" +
	"\x14ProjectMemberService\x12R\n" +
	"\x06Create\x12).api.v1.ProjectMemberServiceCreateRequest\x1a\x1d.api.v1.ProjectMemberResponse\x12R\n" +
	"\x06Update\x12).api.v1.ProjectMemberServiceUpdateRequest\x1a\x1d.api.v1.ProjectMemberResponse\x12R\n" +
	"\x06Delete\x12).api.v1.ProjectMemberServiceDeleteRequest\x1a\x1d.api.v1.ProjectMemberResponse\x12L\n" +
	"\x03Get\x12&.api.v1.ProjectMemberServiceGetRequest\x1a\x1d.api.v1.ProjectMemberResponse\x12R\n" +
	"\x04Find\x12'.api.v1.ProjectMemberServiceFindRequest\x1a!.api.v1.ProjectMemberListResponseB\x8c\x01\n" +
	"\n" +
	"com.api.v1B\x12ProjectMemberProtoP\x01Z1github.com/metal-stack/tenant-api/go/api/v1;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var (
	file_api_v1_project_member_proto_rawDescOnce sync.Once
	file_api_v1_project_member_proto_rawDescData []byte
)

func file_api_v1_project_member_proto_rawDescGZIP() []byte {
	file_api_v1_project_member_proto_rawDescOnce.Do(func() {
		file_api_v1_project_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_project_member_proto_rawDesc), len(file_api_v1_project_member_proto_rawDesc)))
	})
	return file_api_v1_project_member_proto_rawDescData
}

var file_api_v1_project_member_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_v1_project_member_proto_goTypes = []any{
	(*ProjectMember)(nil),                     // 0: api.v1.ProjectMember
	(*ProjectMemberServiceCreateRequest)(nil), // 1: api.v1.ProjectMemberServiceCreateRequest
	(*ProjectMemberServiceUpdateRequest)(nil), // 2: api.v1.ProjectMemberServiceUpdateRequest
	(*ProjectMemberServiceDeleteRequest)(nil), // 3: api.v1.ProjectMemberServiceDeleteRequest
	(*ProjectMemberServiceGetRequest)(nil),    // 4: api.v1.ProjectMemberServiceGetRequest
	(*ProjectMemberServiceFindRequest)(nil),   // 5: api.v1.ProjectMemberServiceFindRequest
	(*ProjectMemberResponse)(nil),             // 6: api.v1.ProjectMemberResponse
	(*ProjectMemberListResponse)(nil),         // 7: api.v1.ProjectMemberListResponse
	nil,                                       // 8: api.v1.ProjectMemberServiceFindRequest.AnnotationsEntry
	(*Meta)(nil),                              // 9: api.v1.Meta
}
var file_api_v1_project_member_proto_depIdxs = []int32{
	9,  // 0: api.v1.ProjectMember.meta:type_name -> api.v1.Meta
	0,  // 1: api.v1.ProjectMemberServiceCreateRequest.project_member:type_name -> api.v1.ProjectMember
	0,  // 2: api.v1.ProjectMemberServiceUpdateRequest.project_member:type_name -> api.v1.ProjectMember
	8,  // 3: api.v1.ProjectMemberServiceFindRequest.annotations:type_name -> api.v1.ProjectMemberServiceFindRequest.AnnotationsEntry
	0,  // 4: api.v1.ProjectMemberResponse.project_member:type_name -> api.v1.ProjectMember
	0,  // 5: api.v1.ProjectMemberListResponse.project_members:type_name -> api.v1.ProjectMember
	1,  // 6: api.v1.ProjectMemberService.Create:input_type -> api.v1.ProjectMemberServiceCreateRequest
	2,  // 7: api.v1.ProjectMemberService.Update:input_type -> api.v1.ProjectMemberServiceUpdateRequest
	3,  // 8: api.v1.ProjectMemberService.Delete:input_type -> api.v1.ProjectMemberServiceDeleteRequest
	4,  // 9: api.v1.ProjectMemberService.Get:input_type -> api.v1.ProjectMemberServiceGetRequest
	5,  // 10: api.v1.ProjectMemberService.Find:input_type -> api.v1.ProjectMemberServiceFindRequest
	6,  // 11: api.v1.ProjectMemberService.Create:output_type -> api.v1.ProjectMemberResponse
	6,  // 12: api.v1.ProjectMemberService.Update:output_type -> api.v1.ProjectMemberResponse
	6,  // 13: api.v1.ProjectMemberService.Delete:output_type -> api.v1.ProjectMemberResponse
	6,  // 14: api.v1.ProjectMemberService.Get:output_type -> api.v1.ProjectMemberResponse
	7,  // 15: api.v1.ProjectMemberService.Find:output_type -> api.v1.ProjectMemberListResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_project_member_proto_init() }
func file_api_v1_project_member_proto_init() {
	if File_api_v1_project_member_proto != nil {
		return
	}
	file_api_v1_meta_proto_init()
	file_api_v1_project_member_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_project_member_proto_rawDesc), len(file_api_v1_project_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_project_member_proto_goTypes,
		DependencyIndexes: file_api_v1_project_member_proto_depIdxs,
		MessageInfos:      file_api_v1_project_member_proto_msgTypes,
	}.Build()
	File_api_v1_project_member_proto = out.File
	file_api_v1_project_member_proto_goTypes = nil
	file_api_v1_project_member_proto_depIdxs = nil
}
