// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/tenant_member.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TenantMember is the database model
type TenantMember struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Meta of the tenant member
	Meta *Meta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// TenantId is the id of the parent tenant
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// MemberId is the id of the member tenant
	MemberId string `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	// Namespace introduces the possibility to associate memberships for different applications that use the masterdata-api as a backend.
	Namespace     string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantMember) Reset() {
	*x = TenantMember{}
	mi := &file_api_v1_tenant_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMember) ProtoMessage() {}

func (x *TenantMember) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMember.ProtoReflect.Descriptor instead.
func (*TenantMember) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_member_proto_rawDescGZIP(), []int{0}
}

func (x *TenantMember) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *TenantMember) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantMember) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *TenantMember) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// TenantMemberServiceCreateRequest is the request payload to create a tenant member
type TenantMemberServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TenantMember to create
	TenantMember  *TenantMember `protobuf:"bytes,1,opt,name=tenant_member,json=tenantMember,proto3" json:"tenant_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantMemberServiceCreateRequest) Reset() {
	*x = TenantMemberServiceCreateRequest{}
	mi := &file_api_v1_tenant_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMemberServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMemberServiceCreateRequest) ProtoMessage() {}

func (x *TenantMemberServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMemberServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*TenantMemberServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_member_proto_rawDescGZIP(), []int{1}
}

func (x *TenantMemberServiceCreateRequest) GetTenantMember() *TenantMember {
	if x != nil {
		return x.TenantMember
	}
	return nil
}

// TenantMemberServiceCreateResponse is the response payload of requests
type TenantMemberServiceCreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TenantMember
	TenantMember  *TenantMember `protobuf:"bytes,1,opt,name=tenant_member,json=tenantMember,proto3" json:"tenant_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantMemberServiceCreateResponse) Reset() {
	*x = TenantMemberServiceCreateResponse{}
	mi := &file_api_v1_tenant_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMemberServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMemberServiceCreateResponse) ProtoMessage() {}

func (x *TenantMemberServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMemberServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*TenantMemberServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_member_proto_rawDescGZIP(), []int{2}
}

func (x *TenantMemberServiceCreateResponse) GetTenantMember() *TenantMember {
	if x != nil {
		return x.TenantMember
	}
	return nil
}

// TenantMemberServiceUpdateRequest is the request payload to update a tenant member
type TenantMemberServiceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TenantMember to update
	TenantMember  *TenantMember `protobuf:"bytes,1,opt,name=tenant_member,json=tenantMember,proto3" json:"tenant_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantMemberServiceUpdateRequest) Reset() {
	*x = TenantMemberServiceUpdateRequest{}
	mi := &file_api_v1_tenant_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMemberServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMemberServiceUpdateRequest) ProtoMessage() {}

func (x *TenantMemberServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMemberServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*TenantMemberServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_member_proto_rawDescGZIP(), []int{3}
}

func (x *TenantMemberServiceUpdateRequest) GetTenantMember() *TenantMember {
	if x != nil {
		return x.TenantMember
	}
	return nil
}

// TenantMemberServiceUpdateResponse is the response payload of requests
type TenantMemberServiceUpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TenantMember
	TenantMember  *TenantMember `protobuf:"bytes,1,opt,name=tenant_member,json=tenantMember,proto3" json:"tenant_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantMemberServiceUpdateResponse) Reset() {
	*x = TenantMemberServiceUpdateResponse{}
	mi := &file_api_v1_tenant_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMemberServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMemberServiceUpdateResponse) ProtoMessage() {}

func (x *TenantMemberServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMemberServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*TenantMemberServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_member_proto_rawDescGZIP(), []int{4}
}

func (x *TenantMemberServiceUpdateResponse) GetTenantMember() *TenantMember {
	if x != nil {
		return x.TenantMember
	}
	return nil
}

// TenantMemberServiceDeleteRequest is the request payload to delete a tenant member
type TenantMemberServiceDeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the tenant member to delete
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantMemberServiceDeleteRequest) Reset() {
	*x = TenantMemberServiceDeleteRequest{}
	mi := &file_api_v1_tenant_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMemberServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMemberServiceDeleteRequest) ProtoMessage() {}

func (x *TenantMemberServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMemberServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*TenantMemberServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_member_proto_rawDescGZIP(), []int{5}
}

func (x *TenantMemberServiceDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// TenantMemberServiceDeleteResponse is the response payload of requests
type TenantMemberServiceDeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TenantMember
	TenantMember  *TenantMember `protobuf:"bytes,1,opt,name=tenant_member,json=tenantMember,proto3" json:"tenant_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantMemberServiceDeleteResponse) Reset() {
	*x = TenantMemberServiceDeleteResponse{}
	mi := &file_api_v1_tenant_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMemberServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMemberServiceDeleteResponse) ProtoMessage() {}

func (x *TenantMemberServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMemberServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*TenantMemberServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_member_proto_rawDescGZIP(), []int{6}
}

func (x *TenantMemberServiceDeleteResponse) GetTenantMember() *TenantMember {
	if x != nil {
		return x.TenantMember
	}
	return nil
}

// TenantMemberServiceGetRequest is the request payload to get a tenant member
type TenantMemberServiceGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the tenant member to get
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantMemberServiceGetRequest) Reset() {
	*x = TenantMemberServiceGetRequest{}
	mi := &file_api_v1_tenant_member_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMemberServiceGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMemberServiceGetRequest) ProtoMessage() {}

func (x *TenantMemberServiceGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_member_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMemberServiceGetRequest.ProtoReflect.Descriptor instead.
func (*TenantMemberServiceGetRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_member_proto_rawDescGZIP(), []int{7}
}

func (x *TenantMemberServiceGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// TenantMemberServiceGetResponse is the response payload of requests
type TenantMemberServiceGetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TenantMember
	TenantMember  *TenantMember `protobuf:"bytes,1,opt,name=tenant_member,json=tenantMember,proto3" json:"tenant_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantMemberServiceGetResponse) Reset() {
	*x = TenantMemberServiceGetResponse{}
	mi := &file_api_v1_tenant_member_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMemberServiceGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMemberServiceGetResponse) ProtoMessage() {}

func (x *TenantMemberServiceGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_member_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMemberServiceGetResponse.ProtoReflect.Descriptor instead.
func (*TenantMemberServiceGetResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_member_proto_rawDescGZIP(), []int{8}
}

func (x *TenantMemberServiceGetResponse) GetTenantMember() *TenantMember {
	if x != nil {
		return x.TenantMember
	}
	return nil
}

// TenantMemberServiceListRequest is the request payload to list tenant members
type TenantMemberServiceListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TenantId of tenant members to list
	TenantId *string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	// MemberId of this tenant member to list
	MemberId *string `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3,oneof" json:"member_id,omitempty"`
	// Annotations of tenant members to list
	Annotations map[string]string `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Namespace
	Namespace     string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantMemberServiceListRequest) Reset() {
	*x = TenantMemberServiceListRequest{}
	mi := &file_api_v1_tenant_member_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMemberServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMemberServiceListRequest) ProtoMessage() {}

func (x *TenantMemberServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_member_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMemberServiceListRequest.ProtoReflect.Descriptor instead.
func (*TenantMemberServiceListRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_member_proto_rawDescGZIP(), []int{9}
}

func (x *TenantMemberServiceListRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *TenantMemberServiceListRequest) GetMemberId() string {
	if x != nil && x.MemberId != nil {
		return *x.MemberId
	}
	return ""
}

func (x *TenantMemberServiceListRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *TenantMemberServiceListRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// TenantMemberServiceListResponse is the response payload of list requests
type TenantMemberServiceListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TenantMembers
	TenantMembers []*TenantMember `protobuf:"bytes,1,rep,name=tenant_members,json=tenantMembers,proto3" json:"tenant_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantMemberServiceListResponse) Reset() {
	*x = TenantMemberServiceListResponse{}
	mi := &file_api_v1_tenant_member_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMemberServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMemberServiceListResponse) ProtoMessage() {}

func (x *TenantMemberServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_tenant_member_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMemberServiceListResponse.ProtoReflect.Descriptor instead.
func (*TenantMemberServiceListResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_tenant_member_proto_rawDescGZIP(), []int{10}
}

func (x *TenantMemberServiceListResponse) GetTenantMembers() []*TenantMember {
	if x != nil {
		return x.TenantMembers
	}
	return nil
}

var File_api_v1_tenant_member_proto protoreflect.FileDescriptor

const file_api_v1_tenant_member_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/v1/tenant_member.proto\x12\x06api.v1\x1a\x11api/v1/meta.proto\"\x88\x01\n" +
	"\fTenantMember\x12 \n" +
	"\x04meta\x18\x01 \x01(\v2\f.api.v1.MetaR\x04meta\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tmember_id\x18\x03 \x01(\tR\bmemberId\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\"]\n" +
	" TenantMemberServiceCreateRequest\x129\n" +
	"\rtenant_member\x18\x01 \x01(\v2\x14.api.v1.TenantMemberR\ftenantMember\"^\n" +
	"!TenantMemberServiceCreateResponse\x129\n" +
	"\rtenant_member\x18\x01 \x01(\v2\x14.api.v1.TenantMemberR\ftenantMember\"]\n" +
	" TenantMemberServiceUpdateRequest\x129\n" +
	"\rtenant_member\x18\x01 \x01(\v2\x14.api.v1.TenantMemberR\ftenantMember\"^\n" +
	"!TenantMemberServiceUpdateResponse\x129\n" +
	"\rtenant_member\x18\x01 \x01(\v2\x14.api.v1.TenantMemberR\ftenantMember\"2\n" +
	" TenantMemberServiceDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"!TenantMemberServiceDeleteResponse\x129\n" +
	"\rtenant_member\x18\x01 \x01(\v2\x14.api.v1.TenantMemberR\ftenantMember\"/\n" +
	"\x1dTenantMemberServiceGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"[\n" +
	"\x1eTenantMemberServiceGetResponse\x129\n" +
	"\rtenant_member\x18\x01 \x01(\v2\x14.api.v1.TenantMemberR\ftenantMember\"\xb9\x02\n" +
	"\x1eTenantMemberServiceListRequest\x12 \n" +
	"\ttenant_id\x18\x01 \x01(\tH\x00R\btenantId\x88\x01\x01\x12 \n" +
	"\tmember_id\x18\x02 \x01(\tH\x01R\bmemberId\x88\x01\x01\x12Y\n" +
	"\vannotations\x18\x03 \x03(\v27.api.v1.TenantMemberServiceListRequest.AnnotationsEntryR\vannotations\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\f\n" +
	"\n" +
	"_tenant_idB\f\n" +
	"\n" +
	"_member_id\"^\n" +
	"\x1fTenantMemberServiceListResponse\x12;\n" +
	"\x0etenant_members\x18\x01 \x03(\v2\x14.api.v1.TenantMemberR\rtenantMembers2\xe1\x03\n" +
	"\x13TenantMemberService\x12]\n" +
	"\x06Create\x12(.api.v1.TenantMemberServiceCreateRequest\x1a).api.v1.TenantMemberServiceCreateResponse\x12]\n" +
	"\x06Update\x12(.api.v1.TenantMemberServiceUpdateRequest\x1a).api.v1.TenantMemberServiceUpdateResponse\x12]\n" +
	"\x06Delete\x12(.api.v1.TenantMemberServiceDeleteRequest\x1a).api.v1.TenantMemberServiceDeleteResponse\x12T\n" +
	"\x03Get\x12%.api.v1.TenantMemberServiceGetRequest\x1a&.api.v1.TenantMemberServiceGetResponse\x12W\n" +
	"\x04List\x12&.api.v1.TenantMemberServiceListRequest\x1a'.api.v1.TenantMemberServiceListResponseB\x8b\x01\n" +
	"\n" +
	"com.api.v1B\x11TenantMemberProtoP\x01Z1github.com/metal-stack/tenant-api/go/api/v1;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var (
	file_api_v1_tenant_member_proto_rawDescOnce sync.Once
	file_api_v1_tenant_member_proto_rawDescData []byte
)

func file_api_v1_tenant_member_proto_rawDescGZIP() []byte {
	file_api_v1_tenant_member_proto_rawDescOnce.Do(func() {
		file_api_v1_tenant_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_tenant_member_proto_rawDesc), len(file_api_v1_tenant_member_proto_rawDesc)))
	})
	return file_api_v1_tenant_member_proto_rawDescData
}

var file_api_v1_tenant_member_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_v1_tenant_member_proto_goTypes = []any{
	(*TenantMember)(nil),                      // 0: api.v1.TenantMember
	(*TenantMemberServiceCreateRequest)(nil),  // 1: api.v1.TenantMemberServiceCreateRequest
	(*TenantMemberServiceCreateResponse)(nil), // 2: api.v1.TenantMemberServiceCreateResponse
	(*TenantMemberServiceUpdateRequest)(nil),  // 3: api.v1.TenantMemberServiceUpdateRequest
	(*TenantMemberServiceUpdateResponse)(nil), // 4: api.v1.TenantMemberServiceUpdateResponse
	(*TenantMemberServiceDeleteRequest)(nil),  // 5: api.v1.TenantMemberServiceDeleteRequest
	(*TenantMemberServiceDeleteResponse)(nil), // 6: api.v1.TenantMemberServiceDeleteResponse
	(*TenantMemberServiceGetRequest)(nil),     // 7: api.v1.TenantMemberServiceGetRequest
	(*TenantMemberServiceGetResponse)(nil),    // 8: api.v1.TenantMemberServiceGetResponse
	(*TenantMemberServiceListRequest)(nil),    // 9: api.v1.TenantMemberServiceListRequest
	(*TenantMemberServiceListResponse)(nil),   // 10: api.v1.TenantMemberServiceListResponse
	nil,                                       // 11: api.v1.TenantMemberServiceListRequest.AnnotationsEntry
	(*Meta)(nil),                              // 12: api.v1.Meta
}
var file_api_v1_tenant_member_proto_depIdxs = []int32{
	12, // 0: api.v1.TenantMember.meta:type_name -> api.v1.Meta
	0,  // 1: api.v1.TenantMemberServiceCreateRequest.tenant_member:type_name -> api.v1.TenantMember
	0,  // 2: api.v1.TenantMemberServiceCreateResponse.tenant_member:type_name -> api.v1.TenantMember
	0,  // 3: api.v1.TenantMemberServiceUpdateRequest.tenant_member:type_name -> api.v1.TenantMember
	0,  // 4: api.v1.TenantMemberServiceUpdateResponse.tenant_member:type_name -> api.v1.TenantMember
	0,  // 5: api.v1.TenantMemberServiceDeleteResponse.tenant_member:type_name -> api.v1.TenantMember
	0,  // 6: api.v1.TenantMemberServiceGetResponse.tenant_member:type_name -> api.v1.TenantMember
	11, // 7: api.v1.TenantMemberServiceListRequest.annotations:type_name -> api.v1.TenantMemberServiceListRequest.AnnotationsEntry
	0,  // 8: api.v1.TenantMemberServiceListResponse.tenant_members:type_name -> api.v1.TenantMember
	1,  // 9: api.v1.TenantMemberService.Create:input_type -> api.v1.TenantMemberServiceCreateRequest
	3,  // 10: api.v1.TenantMemberService.Update:input_type -> api.v1.TenantMemberServiceUpdateRequest
	5,  // 11: api.v1.TenantMemberService.Delete:input_type -> api.v1.TenantMemberServiceDeleteRequest
	7,  // 12: api.v1.TenantMemberService.Get:input_type -> api.v1.TenantMemberServiceGetRequest
	9,  // 13: api.v1.TenantMemberService.List:input_type -> api.v1.TenantMemberServiceListRequest
	2,  // 14: api.v1.TenantMemberService.Create:output_type -> api.v1.TenantMemberServiceCreateResponse
	4,  // 15: api.v1.TenantMemberService.Update:output_type -> api.v1.TenantMemberServiceUpdateResponse
	6,  // 16: api.v1.TenantMemberService.Delete:output_type -> api.v1.TenantMemberServiceDeleteResponse
	8,  // 17: api.v1.TenantMemberService.Get:output_type -> api.v1.TenantMemberServiceGetResponse
	10, // 18: api.v1.TenantMemberService.List:output_type -> api.v1.TenantMemberServiceListResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_v1_tenant_member_proto_init() }
func file_api_v1_tenant_member_proto_init() {
	if File_api_v1_tenant_member_proto != nil {
		return
	}
	file_api_v1_meta_proto_init()
	file_api_v1_tenant_member_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_tenant_member_proto_rawDesc), len(file_api_v1_tenant_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_tenant_member_proto_goTypes,
		DependencyIndexes: file_api_v1_tenant_member_proto_depIdxs,
		MessageInfos:      file_api_v1_tenant_member_proto_msgTypes,
	}.Build()
	File_api_v1_tenant_member_proto = out.File
	file_api_v1_tenant_member_proto_goTypes = nil
	file_api_v1_tenant_member_proto_depIdxs = nil
}
