// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv1connect

import (
	"context"

	"github.com/metal-stack/tenant-api/go/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewProjectServiceHandler creates a new instance of ProjectServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectServiceHandler {
	mock := &ProjectServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProjectServiceHandler is an autogenerated mock type for the ProjectServiceHandler type
type ProjectServiceHandler struct {
	mock.Mock
}

type ProjectServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *ProjectServiceHandler) EXPECT() *ProjectServiceHandler_Expecter {
	return &ProjectServiceHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ProjectServiceHandler
func (_mock *ProjectServiceHandler) Create(context1 context.Context, projectCreateRequest *apiv1.ProjectCreateRequest) (*apiv1.ProjectResponse, error) {
	ret := _mock.Called(context1, projectCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apiv1.ProjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectCreateRequest) (*apiv1.ProjectResponse, error)); ok {
		return returnFunc(context1, projectCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectCreateRequest) *apiv1.ProjectResponse); ok {
		r0 = returnFunc(context1, projectCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectCreateRequest) error); ok {
		r1 = returnFunc(context1, projectCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectServiceHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProjectServiceHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - projectCreateRequest *apiv1.ProjectCreateRequest
func (_e *ProjectServiceHandler_Expecter) Create(context1 interface{}, projectCreateRequest interface{}) *ProjectServiceHandler_Create_Call {
	return &ProjectServiceHandler_Create_Call{Call: _e.mock.On("Create", context1, projectCreateRequest)}
}

func (_c *ProjectServiceHandler_Create_Call) Run(run func(context1 context.Context, projectCreateRequest *apiv1.ProjectCreateRequest)) *ProjectServiceHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectServiceHandler_Create_Call) Return(projectResponse *apiv1.ProjectResponse, err error) *ProjectServiceHandler_Create_Call {
	_c.Call.Return(projectResponse, err)
	return _c
}

func (_c *ProjectServiceHandler_Create_Call) RunAndReturn(run func(context1 context.Context, projectCreateRequest *apiv1.ProjectCreateRequest) (*apiv1.ProjectResponse, error)) *ProjectServiceHandler_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ProjectServiceHandler
func (_mock *ProjectServiceHandler) Delete(context1 context.Context, projectDeleteRequest *apiv1.ProjectDeleteRequest) (*apiv1.ProjectResponse, error) {
	ret := _mock.Called(context1, projectDeleteRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *apiv1.ProjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectDeleteRequest) (*apiv1.ProjectResponse, error)); ok {
		return returnFunc(context1, projectDeleteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectDeleteRequest) *apiv1.ProjectResponse); ok {
		r0 = returnFunc(context1, projectDeleteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectDeleteRequest) error); ok {
		r1 = returnFunc(context1, projectDeleteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectServiceHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ProjectServiceHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - projectDeleteRequest *apiv1.ProjectDeleteRequest
func (_e *ProjectServiceHandler_Expecter) Delete(context1 interface{}, projectDeleteRequest interface{}) *ProjectServiceHandler_Delete_Call {
	return &ProjectServiceHandler_Delete_Call{Call: _e.mock.On("Delete", context1, projectDeleteRequest)}
}

func (_c *ProjectServiceHandler_Delete_Call) Run(run func(context1 context.Context, projectDeleteRequest *apiv1.ProjectDeleteRequest)) *ProjectServiceHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectServiceHandler_Delete_Call) Return(projectResponse *apiv1.ProjectResponse, err error) *ProjectServiceHandler_Delete_Call {
	_c.Call.Return(projectResponse, err)
	return _c
}

func (_c *ProjectServiceHandler_Delete_Call) RunAndReturn(run func(context1 context.Context, projectDeleteRequest *apiv1.ProjectDeleteRequest) (*apiv1.ProjectResponse, error)) *ProjectServiceHandler_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type ProjectServiceHandler
func (_mock *ProjectServiceHandler) Find(context1 context.Context, projectFindRequest *apiv1.ProjectFindRequest) (*apiv1.ProjectListResponse, error) {
	ret := _mock.Called(context1, projectFindRequest)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *apiv1.ProjectListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectFindRequest) (*apiv1.ProjectListResponse, error)); ok {
		return returnFunc(context1, projectFindRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectFindRequest) *apiv1.ProjectListResponse); ok {
		r0 = returnFunc(context1, projectFindRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectFindRequest) error); ok {
		r1 = returnFunc(context1, projectFindRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectServiceHandler_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type ProjectServiceHandler_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - context1 context.Context
//   - projectFindRequest *apiv1.ProjectFindRequest
func (_e *ProjectServiceHandler_Expecter) Find(context1 interface{}, projectFindRequest interface{}) *ProjectServiceHandler_Find_Call {
	return &ProjectServiceHandler_Find_Call{Call: _e.mock.On("Find", context1, projectFindRequest)}
}

func (_c *ProjectServiceHandler_Find_Call) Run(run func(context1 context.Context, projectFindRequest *apiv1.ProjectFindRequest)) *ProjectServiceHandler_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectFindRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectFindRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectServiceHandler_Find_Call) Return(projectListResponse *apiv1.ProjectListResponse, err error) *ProjectServiceHandler_Find_Call {
	_c.Call.Return(projectListResponse, err)
	return _c
}

func (_c *ProjectServiceHandler_Find_Call) RunAndReturn(run func(context1 context.Context, projectFindRequest *apiv1.ProjectFindRequest) (*apiv1.ProjectListResponse, error)) *ProjectServiceHandler_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ProjectServiceHandler
func (_mock *ProjectServiceHandler) Get(context1 context.Context, projectGetRequest *apiv1.ProjectGetRequest) (*apiv1.ProjectResponse, error) {
	ret := _mock.Called(context1, projectGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv1.ProjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectGetRequest) (*apiv1.ProjectResponse, error)); ok {
		return returnFunc(context1, projectGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectGetRequest) *apiv1.ProjectResponse); ok {
		r0 = returnFunc(context1, projectGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectGetRequest) error); ok {
		r1 = returnFunc(context1, projectGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectServiceHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ProjectServiceHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - projectGetRequest *apiv1.ProjectGetRequest
func (_e *ProjectServiceHandler_Expecter) Get(context1 interface{}, projectGetRequest interface{}) *ProjectServiceHandler_Get_Call {
	return &ProjectServiceHandler_Get_Call{Call: _e.mock.On("Get", context1, projectGetRequest)}
}

func (_c *ProjectServiceHandler_Get_Call) Run(run func(context1 context.Context, projectGetRequest *apiv1.ProjectGetRequest)) *ProjectServiceHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectGetRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectServiceHandler_Get_Call) Return(projectResponse *apiv1.ProjectResponse, err error) *ProjectServiceHandler_Get_Call {
	_c.Call.Return(projectResponse, err)
	return _c
}

func (_c *ProjectServiceHandler_Get_Call) RunAndReturn(run func(context1 context.Context, projectGetRequest *apiv1.ProjectGetRequest) (*apiv1.ProjectResponse, error)) *ProjectServiceHandler_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistory provides a mock function for the type ProjectServiceHandler
func (_mock *ProjectServiceHandler) GetHistory(context1 context.Context, projectGetHistoryRequest *apiv1.ProjectGetHistoryRequest) (*apiv1.ProjectResponse, error) {
	ret := _mock.Called(context1, projectGetHistoryRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 *apiv1.ProjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectGetHistoryRequest) (*apiv1.ProjectResponse, error)); ok {
		return returnFunc(context1, projectGetHistoryRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectGetHistoryRequest) *apiv1.ProjectResponse); ok {
		r0 = returnFunc(context1, projectGetHistoryRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectGetHistoryRequest) error); ok {
		r1 = returnFunc(context1, projectGetHistoryRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectServiceHandler_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type ProjectServiceHandler_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - context1 context.Context
//   - projectGetHistoryRequest *apiv1.ProjectGetHistoryRequest
func (_e *ProjectServiceHandler_Expecter) GetHistory(context1 interface{}, projectGetHistoryRequest interface{}) *ProjectServiceHandler_GetHistory_Call {
	return &ProjectServiceHandler_GetHistory_Call{Call: _e.mock.On("GetHistory", context1, projectGetHistoryRequest)}
}

func (_c *ProjectServiceHandler_GetHistory_Call) Run(run func(context1 context.Context, projectGetHistoryRequest *apiv1.ProjectGetHistoryRequest)) *ProjectServiceHandler_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectGetHistoryRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectGetHistoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectServiceHandler_GetHistory_Call) Return(projectResponse *apiv1.ProjectResponse, err error) *ProjectServiceHandler_GetHistory_Call {
	_c.Call.Return(projectResponse, err)
	return _c
}

func (_c *ProjectServiceHandler_GetHistory_Call) RunAndReturn(run func(context1 context.Context, projectGetHistoryRequest *apiv1.ProjectGetHistoryRequest) (*apiv1.ProjectResponse, error)) *ProjectServiceHandler_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ProjectServiceHandler
func (_mock *ProjectServiceHandler) Update(context1 context.Context, projectUpdateRequest *apiv1.ProjectUpdateRequest) (*apiv1.ProjectResponse, error) {
	ret := _mock.Called(context1, projectUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *apiv1.ProjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectUpdateRequest) (*apiv1.ProjectResponse, error)); ok {
		return returnFunc(context1, projectUpdateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectUpdateRequest) *apiv1.ProjectResponse); ok {
		r0 = returnFunc(context1, projectUpdateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectUpdateRequest) error); ok {
		r1 = returnFunc(context1, projectUpdateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectServiceHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProjectServiceHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - projectUpdateRequest *apiv1.ProjectUpdateRequest
func (_e *ProjectServiceHandler_Expecter) Update(context1 interface{}, projectUpdateRequest interface{}) *ProjectServiceHandler_Update_Call {
	return &ProjectServiceHandler_Update_Call{Call: _e.mock.On("Update", context1, projectUpdateRequest)}
}

func (_c *ProjectServiceHandler_Update_Call) Run(run func(context1 context.Context, projectUpdateRequest *apiv1.ProjectUpdateRequest)) *ProjectServiceHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectServiceHandler_Update_Call) Return(projectResponse *apiv1.ProjectResponse, err error) *ProjectServiceHandler_Update_Call {
	_c.Call.Return(projectResponse, err)
	return _c
}

func (_c *ProjectServiceHandler_Update_Call) RunAndReturn(run func(context1 context.Context, projectUpdateRequest *apiv1.ProjectUpdateRequest) (*apiv1.ProjectResponse, error)) *ProjectServiceHandler_Update_Call {
	_c.Call.Return(run)
	return _c
}
