// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv1connect

import (
	"context"

	"github.com/metal-stack/tenant-api/go/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewProjectMemberServiceClient creates a new instance of ProjectMemberServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectMemberServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectMemberServiceClient {
	mock := &ProjectMemberServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProjectMemberServiceClient is an autogenerated mock type for the ProjectMemberServiceClient type
type ProjectMemberServiceClient struct {
	mock.Mock
}

type ProjectMemberServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ProjectMemberServiceClient) EXPECT() *ProjectMemberServiceClient_Expecter {
	return &ProjectMemberServiceClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ProjectMemberServiceClient
func (_mock *ProjectMemberServiceClient) Create(context1 context.Context, projectMemberCreateRequest *apiv1.ProjectMemberCreateRequest) (*apiv1.ProjectMemberResponse, error) {
	ret := _mock.Called(context1, projectMemberCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apiv1.ProjectMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectMemberCreateRequest) (*apiv1.ProjectMemberResponse, error)); ok {
		return returnFunc(context1, projectMemberCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectMemberCreateRequest) *apiv1.ProjectMemberResponse); ok {
		r0 = returnFunc(context1, projectMemberCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectMemberCreateRequest) error); ok {
		r1 = returnFunc(context1, projectMemberCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectMemberServiceClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProjectMemberServiceClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - projectMemberCreateRequest *apiv1.ProjectMemberCreateRequest
func (_e *ProjectMemberServiceClient_Expecter) Create(context1 interface{}, projectMemberCreateRequest interface{}) *ProjectMemberServiceClient_Create_Call {
	return &ProjectMemberServiceClient_Create_Call{Call: _e.mock.On("Create", context1, projectMemberCreateRequest)}
}

func (_c *ProjectMemberServiceClient_Create_Call) Run(run func(context1 context.Context, projectMemberCreateRequest *apiv1.ProjectMemberCreateRequest)) *ProjectMemberServiceClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectMemberCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectMemberCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectMemberServiceClient_Create_Call) Return(projectMemberResponse *apiv1.ProjectMemberResponse, err error) *ProjectMemberServiceClient_Create_Call {
	_c.Call.Return(projectMemberResponse, err)
	return _c
}

func (_c *ProjectMemberServiceClient_Create_Call) RunAndReturn(run func(context1 context.Context, projectMemberCreateRequest *apiv1.ProjectMemberCreateRequest) (*apiv1.ProjectMemberResponse, error)) *ProjectMemberServiceClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ProjectMemberServiceClient
func (_mock *ProjectMemberServiceClient) Delete(context1 context.Context, projectMemberDeleteRequest *apiv1.ProjectMemberDeleteRequest) (*apiv1.ProjectMemberResponse, error) {
	ret := _mock.Called(context1, projectMemberDeleteRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *apiv1.ProjectMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectMemberDeleteRequest) (*apiv1.ProjectMemberResponse, error)); ok {
		return returnFunc(context1, projectMemberDeleteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectMemberDeleteRequest) *apiv1.ProjectMemberResponse); ok {
		r0 = returnFunc(context1, projectMemberDeleteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectMemberDeleteRequest) error); ok {
		r1 = returnFunc(context1, projectMemberDeleteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectMemberServiceClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ProjectMemberServiceClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - projectMemberDeleteRequest *apiv1.ProjectMemberDeleteRequest
func (_e *ProjectMemberServiceClient_Expecter) Delete(context1 interface{}, projectMemberDeleteRequest interface{}) *ProjectMemberServiceClient_Delete_Call {
	return &ProjectMemberServiceClient_Delete_Call{Call: _e.mock.On("Delete", context1, projectMemberDeleteRequest)}
}

func (_c *ProjectMemberServiceClient_Delete_Call) Run(run func(context1 context.Context, projectMemberDeleteRequest *apiv1.ProjectMemberDeleteRequest)) *ProjectMemberServiceClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectMemberDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectMemberDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectMemberServiceClient_Delete_Call) Return(projectMemberResponse *apiv1.ProjectMemberResponse, err error) *ProjectMemberServiceClient_Delete_Call {
	_c.Call.Return(projectMemberResponse, err)
	return _c
}

func (_c *ProjectMemberServiceClient_Delete_Call) RunAndReturn(run func(context1 context.Context, projectMemberDeleteRequest *apiv1.ProjectMemberDeleteRequest) (*apiv1.ProjectMemberResponse, error)) *ProjectMemberServiceClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type ProjectMemberServiceClient
func (_mock *ProjectMemberServiceClient) Find(context1 context.Context, projectMemberFindRequest *apiv1.ProjectMemberFindRequest) (*apiv1.ProjectMemberListResponse, error) {
	ret := _mock.Called(context1, projectMemberFindRequest)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *apiv1.ProjectMemberListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectMemberFindRequest) (*apiv1.ProjectMemberListResponse, error)); ok {
		return returnFunc(context1, projectMemberFindRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectMemberFindRequest) *apiv1.ProjectMemberListResponse); ok {
		r0 = returnFunc(context1, projectMemberFindRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectMemberListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectMemberFindRequest) error); ok {
		r1 = returnFunc(context1, projectMemberFindRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectMemberServiceClient_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type ProjectMemberServiceClient_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - context1 context.Context
//   - projectMemberFindRequest *apiv1.ProjectMemberFindRequest
func (_e *ProjectMemberServiceClient_Expecter) Find(context1 interface{}, projectMemberFindRequest interface{}) *ProjectMemberServiceClient_Find_Call {
	return &ProjectMemberServiceClient_Find_Call{Call: _e.mock.On("Find", context1, projectMemberFindRequest)}
}

func (_c *ProjectMemberServiceClient_Find_Call) Run(run func(context1 context.Context, projectMemberFindRequest *apiv1.ProjectMemberFindRequest)) *ProjectMemberServiceClient_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectMemberFindRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectMemberFindRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectMemberServiceClient_Find_Call) Return(projectMemberListResponse *apiv1.ProjectMemberListResponse, err error) *ProjectMemberServiceClient_Find_Call {
	_c.Call.Return(projectMemberListResponse, err)
	return _c
}

func (_c *ProjectMemberServiceClient_Find_Call) RunAndReturn(run func(context1 context.Context, projectMemberFindRequest *apiv1.ProjectMemberFindRequest) (*apiv1.ProjectMemberListResponse, error)) *ProjectMemberServiceClient_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ProjectMemberServiceClient
func (_mock *ProjectMemberServiceClient) Get(context1 context.Context, projectMemberGetRequest *apiv1.ProjectMemberGetRequest) (*apiv1.ProjectMemberResponse, error) {
	ret := _mock.Called(context1, projectMemberGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv1.ProjectMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectMemberGetRequest) (*apiv1.ProjectMemberResponse, error)); ok {
		return returnFunc(context1, projectMemberGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectMemberGetRequest) *apiv1.ProjectMemberResponse); ok {
		r0 = returnFunc(context1, projectMemberGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectMemberGetRequest) error); ok {
		r1 = returnFunc(context1, projectMemberGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectMemberServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ProjectMemberServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - projectMemberGetRequest *apiv1.ProjectMemberGetRequest
func (_e *ProjectMemberServiceClient_Expecter) Get(context1 interface{}, projectMemberGetRequest interface{}) *ProjectMemberServiceClient_Get_Call {
	return &ProjectMemberServiceClient_Get_Call{Call: _e.mock.On("Get", context1, projectMemberGetRequest)}
}

func (_c *ProjectMemberServiceClient_Get_Call) Run(run func(context1 context.Context, projectMemberGetRequest *apiv1.ProjectMemberGetRequest)) *ProjectMemberServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectMemberGetRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectMemberGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectMemberServiceClient_Get_Call) Return(projectMemberResponse *apiv1.ProjectMemberResponse, err error) *ProjectMemberServiceClient_Get_Call {
	_c.Call.Return(projectMemberResponse, err)
	return _c
}

func (_c *ProjectMemberServiceClient_Get_Call) RunAndReturn(run func(context1 context.Context, projectMemberGetRequest *apiv1.ProjectMemberGetRequest) (*apiv1.ProjectMemberResponse, error)) *ProjectMemberServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ProjectMemberServiceClient
func (_mock *ProjectMemberServiceClient) Update(context1 context.Context, projectMemberUpdateRequest *apiv1.ProjectMemberUpdateRequest) (*apiv1.ProjectMemberResponse, error) {
	ret := _mock.Called(context1, projectMemberUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *apiv1.ProjectMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectMemberUpdateRequest) (*apiv1.ProjectMemberResponse, error)); ok {
		return returnFunc(context1, projectMemberUpdateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectMemberUpdateRequest) *apiv1.ProjectMemberResponse); ok {
		r0 = returnFunc(context1, projectMemberUpdateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectMemberUpdateRequest) error); ok {
		r1 = returnFunc(context1, projectMemberUpdateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectMemberServiceClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProjectMemberServiceClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - projectMemberUpdateRequest *apiv1.ProjectMemberUpdateRequest
func (_e *ProjectMemberServiceClient_Expecter) Update(context1 interface{}, projectMemberUpdateRequest interface{}) *ProjectMemberServiceClient_Update_Call {
	return &ProjectMemberServiceClient_Update_Call{Call: _e.mock.On("Update", context1, projectMemberUpdateRequest)}
}

func (_c *ProjectMemberServiceClient_Update_Call) Run(run func(context1 context.Context, projectMemberUpdateRequest *apiv1.ProjectMemberUpdateRequest)) *ProjectMemberServiceClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectMemberUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectMemberUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectMemberServiceClient_Update_Call) Return(projectMemberResponse *apiv1.ProjectMemberResponse, err error) *ProjectMemberServiceClient_Update_Call {
	_c.Call.Return(projectMemberResponse, err)
	return _c
}

func (_c *ProjectMemberServiceClient_Update_Call) RunAndReturn(run func(context1 context.Context, projectMemberUpdateRequest *apiv1.ProjectMemberUpdateRequest) (*apiv1.ProjectMemberResponse, error)) *ProjectMemberServiceClient_Update_Call {
	_c.Call.Return(run)
	return _c
}
