// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv1connect

import (
	"context"

	"github.com/metal-stack/tenant-api/go/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewProjectServiceClient creates a new instance of ProjectServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectServiceClient {
	mock := &ProjectServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProjectServiceClient is an autogenerated mock type for the ProjectServiceClient type
type ProjectServiceClient struct {
	mock.Mock
}

type ProjectServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ProjectServiceClient) EXPECT() *ProjectServiceClient_Expecter {
	return &ProjectServiceClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ProjectServiceClient
func (_mock *ProjectServiceClient) Create(context1 context.Context, projectServiceCreateRequest *apiv1.ProjectServiceCreateRequest) (*apiv1.ProjectServiceCreateResponse, error) {
	ret := _mock.Called(context1, projectServiceCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apiv1.ProjectServiceCreateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectServiceCreateRequest) (*apiv1.ProjectServiceCreateResponse, error)); ok {
		return returnFunc(context1, projectServiceCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectServiceCreateRequest) *apiv1.ProjectServiceCreateResponse); ok {
		r0 = returnFunc(context1, projectServiceCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectServiceCreateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectServiceCreateRequest) error); ok {
		r1 = returnFunc(context1, projectServiceCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectServiceClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProjectServiceClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - projectServiceCreateRequest *apiv1.ProjectServiceCreateRequest
func (_e *ProjectServiceClient_Expecter) Create(context1 interface{}, projectServiceCreateRequest interface{}) *ProjectServiceClient_Create_Call {
	return &ProjectServiceClient_Create_Call{Call: _e.mock.On("Create", context1, projectServiceCreateRequest)}
}

func (_c *ProjectServiceClient_Create_Call) Run(run func(context1 context.Context, projectServiceCreateRequest *apiv1.ProjectServiceCreateRequest)) *ProjectServiceClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectServiceCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectServiceCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectServiceClient_Create_Call) Return(projectServiceCreateResponse *apiv1.ProjectServiceCreateResponse, err error) *ProjectServiceClient_Create_Call {
	_c.Call.Return(projectServiceCreateResponse, err)
	return _c
}

func (_c *ProjectServiceClient_Create_Call) RunAndReturn(run func(context1 context.Context, projectServiceCreateRequest *apiv1.ProjectServiceCreateRequest) (*apiv1.ProjectServiceCreateResponse, error)) *ProjectServiceClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ProjectServiceClient
func (_mock *ProjectServiceClient) Delete(context1 context.Context, projectServiceDeleteRequest *apiv1.ProjectServiceDeleteRequest) (*apiv1.ProjectServiceDeleteResponse, error) {
	ret := _mock.Called(context1, projectServiceDeleteRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *apiv1.ProjectServiceDeleteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectServiceDeleteRequest) (*apiv1.ProjectServiceDeleteResponse, error)); ok {
		return returnFunc(context1, projectServiceDeleteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectServiceDeleteRequest) *apiv1.ProjectServiceDeleteResponse); ok {
		r0 = returnFunc(context1, projectServiceDeleteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectServiceDeleteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectServiceDeleteRequest) error); ok {
		r1 = returnFunc(context1, projectServiceDeleteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectServiceClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ProjectServiceClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - projectServiceDeleteRequest *apiv1.ProjectServiceDeleteRequest
func (_e *ProjectServiceClient_Expecter) Delete(context1 interface{}, projectServiceDeleteRequest interface{}) *ProjectServiceClient_Delete_Call {
	return &ProjectServiceClient_Delete_Call{Call: _e.mock.On("Delete", context1, projectServiceDeleteRequest)}
}

func (_c *ProjectServiceClient_Delete_Call) Run(run func(context1 context.Context, projectServiceDeleteRequest *apiv1.ProjectServiceDeleteRequest)) *ProjectServiceClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectServiceDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectServiceDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectServiceClient_Delete_Call) Return(projectServiceDeleteResponse *apiv1.ProjectServiceDeleteResponse, err error) *ProjectServiceClient_Delete_Call {
	_c.Call.Return(projectServiceDeleteResponse, err)
	return _c
}

func (_c *ProjectServiceClient_Delete_Call) RunAndReturn(run func(context1 context.Context, projectServiceDeleteRequest *apiv1.ProjectServiceDeleteRequest) (*apiv1.ProjectServiceDeleteResponse, error)) *ProjectServiceClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ProjectServiceClient
func (_mock *ProjectServiceClient) Get(context1 context.Context, projectServiceGetRequest *apiv1.ProjectServiceGetRequest) (*apiv1.ProjectServiceGetResponse, error) {
	ret := _mock.Called(context1, projectServiceGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv1.ProjectServiceGetResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectServiceGetRequest) (*apiv1.ProjectServiceGetResponse, error)); ok {
		return returnFunc(context1, projectServiceGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectServiceGetRequest) *apiv1.ProjectServiceGetResponse); ok {
		r0 = returnFunc(context1, projectServiceGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectServiceGetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectServiceGetRequest) error); ok {
		r1 = returnFunc(context1, projectServiceGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ProjectServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - projectServiceGetRequest *apiv1.ProjectServiceGetRequest
func (_e *ProjectServiceClient_Expecter) Get(context1 interface{}, projectServiceGetRequest interface{}) *ProjectServiceClient_Get_Call {
	return &ProjectServiceClient_Get_Call{Call: _e.mock.On("Get", context1, projectServiceGetRequest)}
}

func (_c *ProjectServiceClient_Get_Call) Run(run func(context1 context.Context, projectServiceGetRequest *apiv1.ProjectServiceGetRequest)) *ProjectServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectServiceGetRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectServiceGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectServiceClient_Get_Call) Return(projectServiceGetResponse *apiv1.ProjectServiceGetResponse, err error) *ProjectServiceClient_Get_Call {
	_c.Call.Return(projectServiceGetResponse, err)
	return _c
}

func (_c *ProjectServiceClient_Get_Call) RunAndReturn(run func(context1 context.Context, projectServiceGetRequest *apiv1.ProjectServiceGetRequest) (*apiv1.ProjectServiceGetResponse, error)) *ProjectServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistory provides a mock function for the type ProjectServiceClient
func (_mock *ProjectServiceClient) GetHistory(context1 context.Context, projectServiceGetHistoryRequest *apiv1.ProjectServiceGetHistoryRequest) (*apiv1.ProjectServiceGetHistoryResponse, error) {
	ret := _mock.Called(context1, projectServiceGetHistoryRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 *apiv1.ProjectServiceGetHistoryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectServiceGetHistoryRequest) (*apiv1.ProjectServiceGetHistoryResponse, error)); ok {
		return returnFunc(context1, projectServiceGetHistoryRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectServiceGetHistoryRequest) *apiv1.ProjectServiceGetHistoryResponse); ok {
		r0 = returnFunc(context1, projectServiceGetHistoryRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectServiceGetHistoryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectServiceGetHistoryRequest) error); ok {
		r1 = returnFunc(context1, projectServiceGetHistoryRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectServiceClient_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type ProjectServiceClient_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - context1 context.Context
//   - projectServiceGetHistoryRequest *apiv1.ProjectServiceGetHistoryRequest
func (_e *ProjectServiceClient_Expecter) GetHistory(context1 interface{}, projectServiceGetHistoryRequest interface{}) *ProjectServiceClient_GetHistory_Call {
	return &ProjectServiceClient_GetHistory_Call{Call: _e.mock.On("GetHistory", context1, projectServiceGetHistoryRequest)}
}

func (_c *ProjectServiceClient_GetHistory_Call) Run(run func(context1 context.Context, projectServiceGetHistoryRequest *apiv1.ProjectServiceGetHistoryRequest)) *ProjectServiceClient_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectServiceGetHistoryRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectServiceGetHistoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectServiceClient_GetHistory_Call) Return(projectServiceGetHistoryResponse *apiv1.ProjectServiceGetHistoryResponse, err error) *ProjectServiceClient_GetHistory_Call {
	_c.Call.Return(projectServiceGetHistoryResponse, err)
	return _c
}

func (_c *ProjectServiceClient_GetHistory_Call) RunAndReturn(run func(context1 context.Context, projectServiceGetHistoryRequest *apiv1.ProjectServiceGetHistoryRequest) (*apiv1.ProjectServiceGetHistoryResponse, error)) *ProjectServiceClient_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type ProjectServiceClient
func (_mock *ProjectServiceClient) List(context1 context.Context, projectServiceListRequest *apiv1.ProjectServiceListRequest) (*apiv1.ProjectServiceListResponse, error) {
	ret := _mock.Called(context1, projectServiceListRequest)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *apiv1.ProjectServiceListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectServiceListRequest) (*apiv1.ProjectServiceListResponse, error)); ok {
		return returnFunc(context1, projectServiceListRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectServiceListRequest) *apiv1.ProjectServiceListResponse); ok {
		r0 = returnFunc(context1, projectServiceListRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectServiceListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectServiceListRequest) error); ok {
		r1 = returnFunc(context1, projectServiceListRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectServiceClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ProjectServiceClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - projectServiceListRequest *apiv1.ProjectServiceListRequest
func (_e *ProjectServiceClient_Expecter) List(context1 interface{}, projectServiceListRequest interface{}) *ProjectServiceClient_List_Call {
	return &ProjectServiceClient_List_Call{Call: _e.mock.On("List", context1, projectServiceListRequest)}
}

func (_c *ProjectServiceClient_List_Call) Run(run func(context1 context.Context, projectServiceListRequest *apiv1.ProjectServiceListRequest)) *ProjectServiceClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectServiceListRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectServiceListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectServiceClient_List_Call) Return(projectServiceListResponse *apiv1.ProjectServiceListResponse, err error) *ProjectServiceClient_List_Call {
	_c.Call.Return(projectServiceListResponse, err)
	return _c
}

func (_c *ProjectServiceClient_List_Call) RunAndReturn(run func(context1 context.Context, projectServiceListRequest *apiv1.ProjectServiceListRequest) (*apiv1.ProjectServiceListResponse, error)) *ProjectServiceClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ProjectServiceClient
func (_mock *ProjectServiceClient) Update(context1 context.Context, projectServiceUpdateRequest *apiv1.ProjectServiceUpdateRequest) (*apiv1.ProjectServiceUpdateResponse, error) {
	ret := _mock.Called(context1, projectServiceUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *apiv1.ProjectServiceUpdateResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectServiceUpdateRequest) (*apiv1.ProjectServiceUpdateResponse, error)); ok {
		return returnFunc(context1, projectServiceUpdateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ProjectServiceUpdateRequest) *apiv1.ProjectServiceUpdateResponse); ok {
		r0 = returnFunc(context1, projectServiceUpdateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ProjectServiceUpdateResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ProjectServiceUpdateRequest) error); ok {
		r1 = returnFunc(context1, projectServiceUpdateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProjectServiceClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProjectServiceClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - projectServiceUpdateRequest *apiv1.ProjectServiceUpdateRequest
func (_e *ProjectServiceClient_Expecter) Update(context1 interface{}, projectServiceUpdateRequest interface{}) *ProjectServiceClient_Update_Call {
	return &ProjectServiceClient_Update_Call{Call: _e.mock.On("Update", context1, projectServiceUpdateRequest)}
}

func (_c *ProjectServiceClient_Update_Call) Run(run func(context1 context.Context, projectServiceUpdateRequest *apiv1.ProjectServiceUpdateRequest)) *ProjectServiceClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ProjectServiceUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ProjectServiceUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectServiceClient_Update_Call) Return(projectServiceUpdateResponse *apiv1.ProjectServiceUpdateResponse, err error) *ProjectServiceClient_Update_Call {
	_c.Call.Return(projectServiceUpdateResponse, err)
	return _c
}

func (_c *ProjectServiceClient_Update_Call) RunAndReturn(run func(context1 context.Context, projectServiceUpdateRequest *apiv1.ProjectServiceUpdateRequest) (*apiv1.ProjectServiceUpdateResponse, error)) *ProjectServiceClient_Update_Call {
	_c.Call.Return(run)
	return _c
}
