// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv1connect

import (
	"context"

	"github.com/metal-stack/tenant-api/go/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewTenantServiceClient creates a new instance of TenantServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTenantServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenantServiceClient {
	mock := &TenantServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TenantServiceClient is an autogenerated mock type for the TenantServiceClient type
type TenantServiceClient struct {
	mock.Mock
}

type TenantServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TenantServiceClient) EXPECT() *TenantServiceClient_Expecter {
	return &TenantServiceClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) Create(context1 context.Context, tenantServiceCreateRequest *apiv1.TenantServiceCreateRequest) (*apiv1.TenantResponse, error) {
	ret := _mock.Called(context1, tenantServiceCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apiv1.TenantResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceCreateRequest) (*apiv1.TenantResponse, error)); ok {
		return returnFunc(context1, tenantServiceCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceCreateRequest) *apiv1.TenantResponse); ok {
		r0 = returnFunc(context1, tenantServiceCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceCreateRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TenantServiceClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceCreateRequest *apiv1.TenantServiceCreateRequest
func (_e *TenantServiceClient_Expecter) Create(context1 interface{}, tenantServiceCreateRequest interface{}) *TenantServiceClient_Create_Call {
	return &TenantServiceClient_Create_Call{Call: _e.mock.On("Create", context1, tenantServiceCreateRequest)}
}

func (_c *TenantServiceClient_Create_Call) Run(run func(context1 context.Context, tenantServiceCreateRequest *apiv1.TenantServiceCreateRequest)) *TenantServiceClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_Create_Call) Return(tenantResponse *apiv1.TenantResponse, err error) *TenantServiceClient_Create_Call {
	_c.Call.Return(tenantResponse, err)
	return _c
}

func (_c *TenantServiceClient_Create_Call) RunAndReturn(run func(context1 context.Context, tenantServiceCreateRequest *apiv1.TenantServiceCreateRequest) (*apiv1.TenantResponse, error)) *TenantServiceClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) Delete(context1 context.Context, tenantServiceDeleteRequest *apiv1.TenantServiceDeleteRequest) (*apiv1.TenantResponse, error) {
	ret := _mock.Called(context1, tenantServiceDeleteRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *apiv1.TenantResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceDeleteRequest) (*apiv1.TenantResponse, error)); ok {
		return returnFunc(context1, tenantServiceDeleteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceDeleteRequest) *apiv1.TenantResponse); ok {
		r0 = returnFunc(context1, tenantServiceDeleteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceDeleteRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceDeleteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TenantServiceClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceDeleteRequest *apiv1.TenantServiceDeleteRequest
func (_e *TenantServiceClient_Expecter) Delete(context1 interface{}, tenantServiceDeleteRequest interface{}) *TenantServiceClient_Delete_Call {
	return &TenantServiceClient_Delete_Call{Call: _e.mock.On("Delete", context1, tenantServiceDeleteRequest)}
}

func (_c *TenantServiceClient_Delete_Call) Run(run func(context1 context.Context, tenantServiceDeleteRequest *apiv1.TenantServiceDeleteRequest)) *TenantServiceClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_Delete_Call) Return(tenantResponse *apiv1.TenantResponse, err error) *TenantServiceClient_Delete_Call {
	_c.Call.Return(tenantResponse, err)
	return _c
}

func (_c *TenantServiceClient_Delete_Call) RunAndReturn(run func(context1 context.Context, tenantServiceDeleteRequest *apiv1.TenantServiceDeleteRequest) (*apiv1.TenantResponse, error)) *TenantServiceClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) Find(context1 context.Context, tenantServiceFindRequest *apiv1.TenantServiceFindRequest) (*apiv1.TenantListResponse, error) {
	ret := _mock.Called(context1, tenantServiceFindRequest)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *apiv1.TenantListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceFindRequest) (*apiv1.TenantListResponse, error)); ok {
		return returnFunc(context1, tenantServiceFindRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceFindRequest) *apiv1.TenantListResponse); ok {
		r0 = returnFunc(context1, tenantServiceFindRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceFindRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceFindRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type TenantServiceClient_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceFindRequest *apiv1.TenantServiceFindRequest
func (_e *TenantServiceClient_Expecter) Find(context1 interface{}, tenantServiceFindRequest interface{}) *TenantServiceClient_Find_Call {
	return &TenantServiceClient_Find_Call{Call: _e.mock.On("Find", context1, tenantServiceFindRequest)}
}

func (_c *TenantServiceClient_Find_Call) Run(run func(context1 context.Context, tenantServiceFindRequest *apiv1.TenantServiceFindRequest)) *TenantServiceClient_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceFindRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceFindRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_Find_Call) Return(tenantListResponse *apiv1.TenantListResponse, err error) *TenantServiceClient_Find_Call {
	_c.Call.Return(tenantListResponse, err)
	return _c
}

func (_c *TenantServiceClient_Find_Call) RunAndReturn(run func(context1 context.Context, tenantServiceFindRequest *apiv1.TenantServiceFindRequest) (*apiv1.TenantListResponse, error)) *TenantServiceClient_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindParticipatingProjects provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) FindParticipatingProjects(context1 context.Context, tenantServiceFindParticipatingProjectsRequest *apiv1.TenantServiceFindParticipatingProjectsRequest) (*apiv1.FindParticipatingProjectsResponse, error) {
	ret := _mock.Called(context1, tenantServiceFindParticipatingProjectsRequest)

	if len(ret) == 0 {
		panic("no return value specified for FindParticipatingProjects")
	}

	var r0 *apiv1.FindParticipatingProjectsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceFindParticipatingProjectsRequest) (*apiv1.FindParticipatingProjectsResponse, error)); ok {
		return returnFunc(context1, tenantServiceFindParticipatingProjectsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceFindParticipatingProjectsRequest) *apiv1.FindParticipatingProjectsResponse); ok {
		r0 = returnFunc(context1, tenantServiceFindParticipatingProjectsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.FindParticipatingProjectsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceFindParticipatingProjectsRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceFindParticipatingProjectsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_FindParticipatingProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindParticipatingProjects'
type TenantServiceClient_FindParticipatingProjects_Call struct {
	*mock.Call
}

// FindParticipatingProjects is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceFindParticipatingProjectsRequest *apiv1.TenantServiceFindParticipatingProjectsRequest
func (_e *TenantServiceClient_Expecter) FindParticipatingProjects(context1 interface{}, tenantServiceFindParticipatingProjectsRequest interface{}) *TenantServiceClient_FindParticipatingProjects_Call {
	return &TenantServiceClient_FindParticipatingProjects_Call{Call: _e.mock.On("FindParticipatingProjects", context1, tenantServiceFindParticipatingProjectsRequest)}
}

func (_c *TenantServiceClient_FindParticipatingProjects_Call) Run(run func(context1 context.Context, tenantServiceFindParticipatingProjectsRequest *apiv1.TenantServiceFindParticipatingProjectsRequest)) *TenantServiceClient_FindParticipatingProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceFindParticipatingProjectsRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceFindParticipatingProjectsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_FindParticipatingProjects_Call) Return(findParticipatingProjectsResponse *apiv1.FindParticipatingProjectsResponse, err error) *TenantServiceClient_FindParticipatingProjects_Call {
	_c.Call.Return(findParticipatingProjectsResponse, err)
	return _c
}

func (_c *TenantServiceClient_FindParticipatingProjects_Call) RunAndReturn(run func(context1 context.Context, tenantServiceFindParticipatingProjectsRequest *apiv1.TenantServiceFindParticipatingProjectsRequest) (*apiv1.FindParticipatingProjectsResponse, error)) *TenantServiceClient_FindParticipatingProjects_Call {
	_c.Call.Return(run)
	return _c
}

// FindParticipatingTenants provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) FindParticipatingTenants(context1 context.Context, tenantServiceFindParticipatingTenantsRequest *apiv1.TenantServiceFindParticipatingTenantsRequest) (*apiv1.FindParticipatingTenantsResponse, error) {
	ret := _mock.Called(context1, tenantServiceFindParticipatingTenantsRequest)

	if len(ret) == 0 {
		panic("no return value specified for FindParticipatingTenants")
	}

	var r0 *apiv1.FindParticipatingTenantsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceFindParticipatingTenantsRequest) (*apiv1.FindParticipatingTenantsResponse, error)); ok {
		return returnFunc(context1, tenantServiceFindParticipatingTenantsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceFindParticipatingTenantsRequest) *apiv1.FindParticipatingTenantsResponse); ok {
		r0 = returnFunc(context1, tenantServiceFindParticipatingTenantsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.FindParticipatingTenantsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceFindParticipatingTenantsRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceFindParticipatingTenantsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_FindParticipatingTenants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindParticipatingTenants'
type TenantServiceClient_FindParticipatingTenants_Call struct {
	*mock.Call
}

// FindParticipatingTenants is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceFindParticipatingTenantsRequest *apiv1.TenantServiceFindParticipatingTenantsRequest
func (_e *TenantServiceClient_Expecter) FindParticipatingTenants(context1 interface{}, tenantServiceFindParticipatingTenantsRequest interface{}) *TenantServiceClient_FindParticipatingTenants_Call {
	return &TenantServiceClient_FindParticipatingTenants_Call{Call: _e.mock.On("FindParticipatingTenants", context1, tenantServiceFindParticipatingTenantsRequest)}
}

func (_c *TenantServiceClient_FindParticipatingTenants_Call) Run(run func(context1 context.Context, tenantServiceFindParticipatingTenantsRequest *apiv1.TenantServiceFindParticipatingTenantsRequest)) *TenantServiceClient_FindParticipatingTenants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceFindParticipatingTenantsRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceFindParticipatingTenantsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_FindParticipatingTenants_Call) Return(findParticipatingTenantsResponse *apiv1.FindParticipatingTenantsResponse, err error) *TenantServiceClient_FindParticipatingTenants_Call {
	_c.Call.Return(findParticipatingTenantsResponse, err)
	return _c
}

func (_c *TenantServiceClient_FindParticipatingTenants_Call) RunAndReturn(run func(context1 context.Context, tenantServiceFindParticipatingTenantsRequest *apiv1.TenantServiceFindParticipatingTenantsRequest) (*apiv1.FindParticipatingTenantsResponse, error)) *TenantServiceClient_FindParticipatingTenants_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) Get(context1 context.Context, tenantServiceGetRequest *apiv1.TenantServiceGetRequest) (*apiv1.TenantResponse, error) {
	ret := _mock.Called(context1, tenantServiceGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv1.TenantResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceGetRequest) (*apiv1.TenantResponse, error)); ok {
		return returnFunc(context1, tenantServiceGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceGetRequest) *apiv1.TenantResponse); ok {
		r0 = returnFunc(context1, tenantServiceGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceGetRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TenantServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceGetRequest *apiv1.TenantServiceGetRequest
func (_e *TenantServiceClient_Expecter) Get(context1 interface{}, tenantServiceGetRequest interface{}) *TenantServiceClient_Get_Call {
	return &TenantServiceClient_Get_Call{Call: _e.mock.On("Get", context1, tenantServiceGetRequest)}
}

func (_c *TenantServiceClient_Get_Call) Run(run func(context1 context.Context, tenantServiceGetRequest *apiv1.TenantServiceGetRequest)) *TenantServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceGetRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_Get_Call) Return(tenantResponse *apiv1.TenantResponse, err error) *TenantServiceClient_Get_Call {
	_c.Call.Return(tenantResponse, err)
	return _c
}

func (_c *TenantServiceClient_Get_Call) RunAndReturn(run func(context1 context.Context, tenantServiceGetRequest *apiv1.TenantServiceGetRequest) (*apiv1.TenantResponse, error)) *TenantServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistory provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) GetHistory(context1 context.Context, tenantServiceGetHistoryRequest *apiv1.TenantServiceGetHistoryRequest) (*apiv1.TenantResponse, error) {
	ret := _mock.Called(context1, tenantServiceGetHistoryRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 *apiv1.TenantResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceGetHistoryRequest) (*apiv1.TenantResponse, error)); ok {
		return returnFunc(context1, tenantServiceGetHistoryRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceGetHistoryRequest) *apiv1.TenantResponse); ok {
		r0 = returnFunc(context1, tenantServiceGetHistoryRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceGetHistoryRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceGetHistoryRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type TenantServiceClient_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceGetHistoryRequest *apiv1.TenantServiceGetHistoryRequest
func (_e *TenantServiceClient_Expecter) GetHistory(context1 interface{}, tenantServiceGetHistoryRequest interface{}) *TenantServiceClient_GetHistory_Call {
	return &TenantServiceClient_GetHistory_Call{Call: _e.mock.On("GetHistory", context1, tenantServiceGetHistoryRequest)}
}

func (_c *TenantServiceClient_GetHistory_Call) Run(run func(context1 context.Context, tenantServiceGetHistoryRequest *apiv1.TenantServiceGetHistoryRequest)) *TenantServiceClient_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceGetHistoryRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceGetHistoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_GetHistory_Call) Return(tenantResponse *apiv1.TenantResponse, err error) *TenantServiceClient_GetHistory_Call {
	_c.Call.Return(tenantResponse, err)
	return _c
}

func (_c *TenantServiceClient_GetHistory_Call) RunAndReturn(run func(context1 context.Context, tenantServiceGetHistoryRequest *apiv1.TenantServiceGetHistoryRequest) (*apiv1.TenantResponse, error)) *TenantServiceClient_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListTenantMembers provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) ListTenantMembers(context1 context.Context, tenantServiceListTenantMembersRequest *apiv1.TenantServiceListTenantMembersRequest) (*apiv1.ListTenantMembersResponse, error) {
	ret := _mock.Called(context1, tenantServiceListTenantMembersRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListTenantMembers")
	}

	var r0 *apiv1.ListTenantMembersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceListTenantMembersRequest) (*apiv1.ListTenantMembersResponse, error)); ok {
		return returnFunc(context1, tenantServiceListTenantMembersRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceListTenantMembersRequest) *apiv1.ListTenantMembersResponse); ok {
		r0 = returnFunc(context1, tenantServiceListTenantMembersRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ListTenantMembersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceListTenantMembersRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceListTenantMembersRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_ListTenantMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTenantMembers'
type TenantServiceClient_ListTenantMembers_Call struct {
	*mock.Call
}

// ListTenantMembers is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceListTenantMembersRequest *apiv1.TenantServiceListTenantMembersRequest
func (_e *TenantServiceClient_Expecter) ListTenantMembers(context1 interface{}, tenantServiceListTenantMembersRequest interface{}) *TenantServiceClient_ListTenantMembers_Call {
	return &TenantServiceClient_ListTenantMembers_Call{Call: _e.mock.On("ListTenantMembers", context1, tenantServiceListTenantMembersRequest)}
}

func (_c *TenantServiceClient_ListTenantMembers_Call) Run(run func(context1 context.Context, tenantServiceListTenantMembersRequest *apiv1.TenantServiceListTenantMembersRequest)) *TenantServiceClient_ListTenantMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceListTenantMembersRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceListTenantMembersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_ListTenantMembers_Call) Return(listTenantMembersResponse *apiv1.ListTenantMembersResponse, err error) *TenantServiceClient_ListTenantMembers_Call {
	_c.Call.Return(listTenantMembersResponse, err)
	return _c
}

func (_c *TenantServiceClient_ListTenantMembers_Call) RunAndReturn(run func(context1 context.Context, tenantServiceListTenantMembersRequest *apiv1.TenantServiceListTenantMembersRequest) (*apiv1.ListTenantMembersResponse, error)) *TenantServiceClient_ListTenantMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TenantServiceClient
func (_mock *TenantServiceClient) Update(context1 context.Context, tenantServiceUpdateRequest *apiv1.TenantServiceUpdateRequest) (*apiv1.TenantResponse, error) {
	ret := _mock.Called(context1, tenantServiceUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *apiv1.TenantResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceUpdateRequest) (*apiv1.TenantResponse, error)); ok {
		return returnFunc(context1, tenantServiceUpdateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantServiceUpdateRequest) *apiv1.TenantResponse); ok {
		r0 = returnFunc(context1, tenantServiceUpdateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantServiceUpdateRequest) error); ok {
		r1 = returnFunc(context1, tenantServiceUpdateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TenantServiceClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantServiceUpdateRequest *apiv1.TenantServiceUpdateRequest
func (_e *TenantServiceClient_Expecter) Update(context1 interface{}, tenantServiceUpdateRequest interface{}) *TenantServiceClient_Update_Call {
	return &TenantServiceClient_Update_Call{Call: _e.mock.On("Update", context1, tenantServiceUpdateRequest)}
}

func (_c *TenantServiceClient_Update_Call) Run(run func(context1 context.Context, tenantServiceUpdateRequest *apiv1.TenantServiceUpdateRequest)) *TenantServiceClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantServiceUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantServiceUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceClient_Update_Call) Return(tenantResponse *apiv1.TenantResponse, err error) *TenantServiceClient_Update_Call {
	_c.Call.Return(tenantResponse, err)
	return _c
}

func (_c *TenantServiceClient_Update_Call) RunAndReturn(run func(context1 context.Context, tenantServiceUpdateRequest *apiv1.TenantServiceUpdateRequest) (*apiv1.TenantResponse, error)) *TenantServiceClient_Update_Call {
	_c.Call.Return(run)
	return _c
}
