// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv1connect

import (
	"context"

	"github.com/metal-stack/tenant-api/go/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewTenantServiceHandler creates a new instance of TenantServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTenantServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenantServiceHandler {
	mock := &TenantServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TenantServiceHandler is an autogenerated mock type for the TenantServiceHandler type
type TenantServiceHandler struct {
	mock.Mock
}

type TenantServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *TenantServiceHandler) EXPECT() *TenantServiceHandler_Expecter {
	return &TenantServiceHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TenantServiceHandler
func (_mock *TenantServiceHandler) Create(context1 context.Context, tenantCreateRequest *apiv1.TenantCreateRequest) (*apiv1.TenantResponse, error) {
	ret := _mock.Called(context1, tenantCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apiv1.TenantResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantCreateRequest) (*apiv1.TenantResponse, error)); ok {
		return returnFunc(context1, tenantCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantCreateRequest) *apiv1.TenantResponse); ok {
		r0 = returnFunc(context1, tenantCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantCreateRequest) error); ok {
		r1 = returnFunc(context1, tenantCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TenantServiceHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantCreateRequest *apiv1.TenantCreateRequest
func (_e *TenantServiceHandler_Expecter) Create(context1 interface{}, tenantCreateRequest interface{}) *TenantServiceHandler_Create_Call {
	return &TenantServiceHandler_Create_Call{Call: _e.mock.On("Create", context1, tenantCreateRequest)}
}

func (_c *TenantServiceHandler_Create_Call) Run(run func(context1 context.Context, tenantCreateRequest *apiv1.TenantCreateRequest)) *TenantServiceHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceHandler_Create_Call) Return(tenantResponse *apiv1.TenantResponse, err error) *TenantServiceHandler_Create_Call {
	_c.Call.Return(tenantResponse, err)
	return _c
}

func (_c *TenantServiceHandler_Create_Call) RunAndReturn(run func(context1 context.Context, tenantCreateRequest *apiv1.TenantCreateRequest) (*apiv1.TenantResponse, error)) *TenantServiceHandler_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TenantServiceHandler
func (_mock *TenantServiceHandler) Delete(context1 context.Context, tenantDeleteRequest *apiv1.TenantDeleteRequest) (*apiv1.TenantResponse, error) {
	ret := _mock.Called(context1, tenantDeleteRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *apiv1.TenantResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantDeleteRequest) (*apiv1.TenantResponse, error)); ok {
		return returnFunc(context1, tenantDeleteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantDeleteRequest) *apiv1.TenantResponse); ok {
		r0 = returnFunc(context1, tenantDeleteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantDeleteRequest) error); ok {
		r1 = returnFunc(context1, tenantDeleteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TenantServiceHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantDeleteRequest *apiv1.TenantDeleteRequest
func (_e *TenantServiceHandler_Expecter) Delete(context1 interface{}, tenantDeleteRequest interface{}) *TenantServiceHandler_Delete_Call {
	return &TenantServiceHandler_Delete_Call{Call: _e.mock.On("Delete", context1, tenantDeleteRequest)}
}

func (_c *TenantServiceHandler_Delete_Call) Run(run func(context1 context.Context, tenantDeleteRequest *apiv1.TenantDeleteRequest)) *TenantServiceHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceHandler_Delete_Call) Return(tenantResponse *apiv1.TenantResponse, err error) *TenantServiceHandler_Delete_Call {
	_c.Call.Return(tenantResponse, err)
	return _c
}

func (_c *TenantServiceHandler_Delete_Call) RunAndReturn(run func(context1 context.Context, tenantDeleteRequest *apiv1.TenantDeleteRequest) (*apiv1.TenantResponse, error)) *TenantServiceHandler_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type TenantServiceHandler
func (_mock *TenantServiceHandler) Find(context1 context.Context, tenantFindRequest *apiv1.TenantFindRequest) (*apiv1.TenantListResponse, error) {
	ret := _mock.Called(context1, tenantFindRequest)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *apiv1.TenantListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantFindRequest) (*apiv1.TenantListResponse, error)); ok {
		return returnFunc(context1, tenantFindRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantFindRequest) *apiv1.TenantListResponse); ok {
		r0 = returnFunc(context1, tenantFindRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantFindRequest) error); ok {
		r1 = returnFunc(context1, tenantFindRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceHandler_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type TenantServiceHandler_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantFindRequest *apiv1.TenantFindRequest
func (_e *TenantServiceHandler_Expecter) Find(context1 interface{}, tenantFindRequest interface{}) *TenantServiceHandler_Find_Call {
	return &TenantServiceHandler_Find_Call{Call: _e.mock.On("Find", context1, tenantFindRequest)}
}

func (_c *TenantServiceHandler_Find_Call) Run(run func(context1 context.Context, tenantFindRequest *apiv1.TenantFindRequest)) *TenantServiceHandler_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantFindRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantFindRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceHandler_Find_Call) Return(tenantListResponse *apiv1.TenantListResponse, err error) *TenantServiceHandler_Find_Call {
	_c.Call.Return(tenantListResponse, err)
	return _c
}

func (_c *TenantServiceHandler_Find_Call) RunAndReturn(run func(context1 context.Context, tenantFindRequest *apiv1.TenantFindRequest) (*apiv1.TenantListResponse, error)) *TenantServiceHandler_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindParticipatingProjects provides a mock function for the type TenantServiceHandler
func (_mock *TenantServiceHandler) FindParticipatingProjects(context1 context.Context, findParticipatingProjectsRequest *apiv1.FindParticipatingProjectsRequest) (*apiv1.FindParticipatingProjectsResponse, error) {
	ret := _mock.Called(context1, findParticipatingProjectsRequest)

	if len(ret) == 0 {
		panic("no return value specified for FindParticipatingProjects")
	}

	var r0 *apiv1.FindParticipatingProjectsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.FindParticipatingProjectsRequest) (*apiv1.FindParticipatingProjectsResponse, error)); ok {
		return returnFunc(context1, findParticipatingProjectsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.FindParticipatingProjectsRequest) *apiv1.FindParticipatingProjectsResponse); ok {
		r0 = returnFunc(context1, findParticipatingProjectsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.FindParticipatingProjectsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.FindParticipatingProjectsRequest) error); ok {
		r1 = returnFunc(context1, findParticipatingProjectsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceHandler_FindParticipatingProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindParticipatingProjects'
type TenantServiceHandler_FindParticipatingProjects_Call struct {
	*mock.Call
}

// FindParticipatingProjects is a helper method to define mock.On call
//   - context1 context.Context
//   - findParticipatingProjectsRequest *apiv1.FindParticipatingProjectsRequest
func (_e *TenantServiceHandler_Expecter) FindParticipatingProjects(context1 interface{}, findParticipatingProjectsRequest interface{}) *TenantServiceHandler_FindParticipatingProjects_Call {
	return &TenantServiceHandler_FindParticipatingProjects_Call{Call: _e.mock.On("FindParticipatingProjects", context1, findParticipatingProjectsRequest)}
}

func (_c *TenantServiceHandler_FindParticipatingProjects_Call) Run(run func(context1 context.Context, findParticipatingProjectsRequest *apiv1.FindParticipatingProjectsRequest)) *TenantServiceHandler_FindParticipatingProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.FindParticipatingProjectsRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.FindParticipatingProjectsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceHandler_FindParticipatingProjects_Call) Return(findParticipatingProjectsResponse *apiv1.FindParticipatingProjectsResponse, err error) *TenantServiceHandler_FindParticipatingProjects_Call {
	_c.Call.Return(findParticipatingProjectsResponse, err)
	return _c
}

func (_c *TenantServiceHandler_FindParticipatingProjects_Call) RunAndReturn(run func(context1 context.Context, findParticipatingProjectsRequest *apiv1.FindParticipatingProjectsRequest) (*apiv1.FindParticipatingProjectsResponse, error)) *TenantServiceHandler_FindParticipatingProjects_Call {
	_c.Call.Return(run)
	return _c
}

// FindParticipatingTenants provides a mock function for the type TenantServiceHandler
func (_mock *TenantServiceHandler) FindParticipatingTenants(context1 context.Context, findParticipatingTenantsRequest *apiv1.FindParticipatingTenantsRequest) (*apiv1.FindParticipatingTenantsResponse, error) {
	ret := _mock.Called(context1, findParticipatingTenantsRequest)

	if len(ret) == 0 {
		panic("no return value specified for FindParticipatingTenants")
	}

	var r0 *apiv1.FindParticipatingTenantsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.FindParticipatingTenantsRequest) (*apiv1.FindParticipatingTenantsResponse, error)); ok {
		return returnFunc(context1, findParticipatingTenantsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.FindParticipatingTenantsRequest) *apiv1.FindParticipatingTenantsResponse); ok {
		r0 = returnFunc(context1, findParticipatingTenantsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.FindParticipatingTenantsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.FindParticipatingTenantsRequest) error); ok {
		r1 = returnFunc(context1, findParticipatingTenantsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceHandler_FindParticipatingTenants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindParticipatingTenants'
type TenantServiceHandler_FindParticipatingTenants_Call struct {
	*mock.Call
}

// FindParticipatingTenants is a helper method to define mock.On call
//   - context1 context.Context
//   - findParticipatingTenantsRequest *apiv1.FindParticipatingTenantsRequest
func (_e *TenantServiceHandler_Expecter) FindParticipatingTenants(context1 interface{}, findParticipatingTenantsRequest interface{}) *TenantServiceHandler_FindParticipatingTenants_Call {
	return &TenantServiceHandler_FindParticipatingTenants_Call{Call: _e.mock.On("FindParticipatingTenants", context1, findParticipatingTenantsRequest)}
}

func (_c *TenantServiceHandler_FindParticipatingTenants_Call) Run(run func(context1 context.Context, findParticipatingTenantsRequest *apiv1.FindParticipatingTenantsRequest)) *TenantServiceHandler_FindParticipatingTenants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.FindParticipatingTenantsRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.FindParticipatingTenantsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceHandler_FindParticipatingTenants_Call) Return(findParticipatingTenantsResponse *apiv1.FindParticipatingTenantsResponse, err error) *TenantServiceHandler_FindParticipatingTenants_Call {
	_c.Call.Return(findParticipatingTenantsResponse, err)
	return _c
}

func (_c *TenantServiceHandler_FindParticipatingTenants_Call) RunAndReturn(run func(context1 context.Context, findParticipatingTenantsRequest *apiv1.FindParticipatingTenantsRequest) (*apiv1.FindParticipatingTenantsResponse, error)) *TenantServiceHandler_FindParticipatingTenants_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TenantServiceHandler
func (_mock *TenantServiceHandler) Get(context1 context.Context, tenantGetRequest *apiv1.TenantGetRequest) (*apiv1.TenantResponse, error) {
	ret := _mock.Called(context1, tenantGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv1.TenantResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantGetRequest) (*apiv1.TenantResponse, error)); ok {
		return returnFunc(context1, tenantGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantGetRequest) *apiv1.TenantResponse); ok {
		r0 = returnFunc(context1, tenantGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantGetRequest) error); ok {
		r1 = returnFunc(context1, tenantGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TenantServiceHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantGetRequest *apiv1.TenantGetRequest
func (_e *TenantServiceHandler_Expecter) Get(context1 interface{}, tenantGetRequest interface{}) *TenantServiceHandler_Get_Call {
	return &TenantServiceHandler_Get_Call{Call: _e.mock.On("Get", context1, tenantGetRequest)}
}

func (_c *TenantServiceHandler_Get_Call) Run(run func(context1 context.Context, tenantGetRequest *apiv1.TenantGetRequest)) *TenantServiceHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantGetRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceHandler_Get_Call) Return(tenantResponse *apiv1.TenantResponse, err error) *TenantServiceHandler_Get_Call {
	_c.Call.Return(tenantResponse, err)
	return _c
}

func (_c *TenantServiceHandler_Get_Call) RunAndReturn(run func(context1 context.Context, tenantGetRequest *apiv1.TenantGetRequest) (*apiv1.TenantResponse, error)) *TenantServiceHandler_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetHistory provides a mock function for the type TenantServiceHandler
func (_mock *TenantServiceHandler) GetHistory(context1 context.Context, tenantGetHistoryRequest *apiv1.TenantGetHistoryRequest) (*apiv1.TenantResponse, error) {
	ret := _mock.Called(context1, tenantGetHistoryRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 *apiv1.TenantResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantGetHistoryRequest) (*apiv1.TenantResponse, error)); ok {
		return returnFunc(context1, tenantGetHistoryRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantGetHistoryRequest) *apiv1.TenantResponse); ok {
		r0 = returnFunc(context1, tenantGetHistoryRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantGetHistoryRequest) error); ok {
		r1 = returnFunc(context1, tenantGetHistoryRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceHandler_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type TenantServiceHandler_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantGetHistoryRequest *apiv1.TenantGetHistoryRequest
func (_e *TenantServiceHandler_Expecter) GetHistory(context1 interface{}, tenantGetHistoryRequest interface{}) *TenantServiceHandler_GetHistory_Call {
	return &TenantServiceHandler_GetHistory_Call{Call: _e.mock.On("GetHistory", context1, tenantGetHistoryRequest)}
}

func (_c *TenantServiceHandler_GetHistory_Call) Run(run func(context1 context.Context, tenantGetHistoryRequest *apiv1.TenantGetHistoryRequest)) *TenantServiceHandler_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantGetHistoryRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantGetHistoryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceHandler_GetHistory_Call) Return(tenantResponse *apiv1.TenantResponse, err error) *TenantServiceHandler_GetHistory_Call {
	_c.Call.Return(tenantResponse, err)
	return _c
}

func (_c *TenantServiceHandler_GetHistory_Call) RunAndReturn(run func(context1 context.Context, tenantGetHistoryRequest *apiv1.TenantGetHistoryRequest) (*apiv1.TenantResponse, error)) *TenantServiceHandler_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// ListTenantMembers provides a mock function for the type TenantServiceHandler
func (_mock *TenantServiceHandler) ListTenantMembers(context1 context.Context, listTenantMembersRequest *apiv1.ListTenantMembersRequest) (*apiv1.ListTenantMembersResponse, error) {
	ret := _mock.Called(context1, listTenantMembersRequest)

	if len(ret) == 0 {
		panic("no return value specified for ListTenantMembers")
	}

	var r0 *apiv1.ListTenantMembersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ListTenantMembersRequest) (*apiv1.ListTenantMembersResponse, error)); ok {
		return returnFunc(context1, listTenantMembersRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.ListTenantMembersRequest) *apiv1.ListTenantMembersResponse); ok {
		r0 = returnFunc(context1, listTenantMembersRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.ListTenantMembersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.ListTenantMembersRequest) error); ok {
		r1 = returnFunc(context1, listTenantMembersRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceHandler_ListTenantMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTenantMembers'
type TenantServiceHandler_ListTenantMembers_Call struct {
	*mock.Call
}

// ListTenantMembers is a helper method to define mock.On call
//   - context1 context.Context
//   - listTenantMembersRequest *apiv1.ListTenantMembersRequest
func (_e *TenantServiceHandler_Expecter) ListTenantMembers(context1 interface{}, listTenantMembersRequest interface{}) *TenantServiceHandler_ListTenantMembers_Call {
	return &TenantServiceHandler_ListTenantMembers_Call{Call: _e.mock.On("ListTenantMembers", context1, listTenantMembersRequest)}
}

func (_c *TenantServiceHandler_ListTenantMembers_Call) Run(run func(context1 context.Context, listTenantMembersRequest *apiv1.ListTenantMembersRequest)) *TenantServiceHandler_ListTenantMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.ListTenantMembersRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.ListTenantMembersRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceHandler_ListTenantMembers_Call) Return(listTenantMembersResponse *apiv1.ListTenantMembersResponse, err error) *TenantServiceHandler_ListTenantMembers_Call {
	_c.Call.Return(listTenantMembersResponse, err)
	return _c
}

func (_c *TenantServiceHandler_ListTenantMembers_Call) RunAndReturn(run func(context1 context.Context, listTenantMembersRequest *apiv1.ListTenantMembersRequest) (*apiv1.ListTenantMembersResponse, error)) *TenantServiceHandler_ListTenantMembers_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TenantServiceHandler
func (_mock *TenantServiceHandler) Update(context1 context.Context, tenantUpdateRequest *apiv1.TenantUpdateRequest) (*apiv1.TenantResponse, error) {
	ret := _mock.Called(context1, tenantUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *apiv1.TenantResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantUpdateRequest) (*apiv1.TenantResponse, error)); ok {
		return returnFunc(context1, tenantUpdateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantUpdateRequest) *apiv1.TenantResponse); ok {
		r0 = returnFunc(context1, tenantUpdateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantUpdateRequest) error); ok {
		r1 = returnFunc(context1, tenantUpdateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantServiceHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TenantServiceHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantUpdateRequest *apiv1.TenantUpdateRequest
func (_e *TenantServiceHandler_Expecter) Update(context1 interface{}, tenantUpdateRequest interface{}) *TenantServiceHandler_Update_Call {
	return &TenantServiceHandler_Update_Call{Call: _e.mock.On("Update", context1, tenantUpdateRequest)}
}

func (_c *TenantServiceHandler_Update_Call) Run(run func(context1 context.Context, tenantUpdateRequest *apiv1.TenantUpdateRequest)) *TenantServiceHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantServiceHandler_Update_Call) Return(tenantResponse *apiv1.TenantResponse, err error) *TenantServiceHandler_Update_Call {
	_c.Call.Return(tenantResponse, err)
	return _c
}

func (_c *TenantServiceHandler_Update_Call) RunAndReturn(run func(context1 context.Context, tenantUpdateRequest *apiv1.TenantUpdateRequest) (*apiv1.TenantResponse, error)) *TenantServiceHandler_Update_Call {
	_c.Call.Return(run)
	return _c
}
