// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv1connect

import (
	"context"

	"github.com/metal-stack/tenant-api/go/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewTenantMemberServiceHandler creates a new instance of TenantMemberServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTenantMemberServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenantMemberServiceHandler {
	mock := &TenantMemberServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TenantMemberServiceHandler is an autogenerated mock type for the TenantMemberServiceHandler type
type TenantMemberServiceHandler struct {
	mock.Mock
}

type TenantMemberServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *TenantMemberServiceHandler) EXPECT() *TenantMemberServiceHandler_Expecter {
	return &TenantMemberServiceHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TenantMemberServiceHandler
func (_mock *TenantMemberServiceHandler) Create(context1 context.Context, tenantMemberServiceCreateRequest *apiv1.TenantMemberServiceCreateRequest) (*apiv1.TenantMemberResponse, error) {
	ret := _mock.Called(context1, tenantMemberServiceCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apiv1.TenantMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceCreateRequest) (*apiv1.TenantMemberResponse, error)); ok {
		return returnFunc(context1, tenantMemberServiceCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceCreateRequest) *apiv1.TenantMemberResponse); ok {
		r0 = returnFunc(context1, tenantMemberServiceCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberServiceCreateRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberServiceCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TenantMemberServiceHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberServiceCreateRequest *apiv1.TenantMemberServiceCreateRequest
func (_e *TenantMemberServiceHandler_Expecter) Create(context1 interface{}, tenantMemberServiceCreateRequest interface{}) *TenantMemberServiceHandler_Create_Call {
	return &TenantMemberServiceHandler_Create_Call{Call: _e.mock.On("Create", context1, tenantMemberServiceCreateRequest)}
}

func (_c *TenantMemberServiceHandler_Create_Call) Run(run func(context1 context.Context, tenantMemberServiceCreateRequest *apiv1.TenantMemberServiceCreateRequest)) *TenantMemberServiceHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberServiceCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberServiceCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceHandler_Create_Call) Return(tenantMemberResponse *apiv1.TenantMemberResponse, err error) *TenantMemberServiceHandler_Create_Call {
	_c.Call.Return(tenantMemberResponse, err)
	return _c
}

func (_c *TenantMemberServiceHandler_Create_Call) RunAndReturn(run func(context1 context.Context, tenantMemberServiceCreateRequest *apiv1.TenantMemberServiceCreateRequest) (*apiv1.TenantMemberResponse, error)) *TenantMemberServiceHandler_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TenantMemberServiceHandler
func (_mock *TenantMemberServiceHandler) Delete(context1 context.Context, tenantMemberServiceDeleteRequest *apiv1.TenantMemberServiceDeleteRequest) (*apiv1.TenantMemberResponse, error) {
	ret := _mock.Called(context1, tenantMemberServiceDeleteRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *apiv1.TenantMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceDeleteRequest) (*apiv1.TenantMemberResponse, error)); ok {
		return returnFunc(context1, tenantMemberServiceDeleteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceDeleteRequest) *apiv1.TenantMemberResponse); ok {
		r0 = returnFunc(context1, tenantMemberServiceDeleteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberServiceDeleteRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberServiceDeleteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TenantMemberServiceHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberServiceDeleteRequest *apiv1.TenantMemberServiceDeleteRequest
func (_e *TenantMemberServiceHandler_Expecter) Delete(context1 interface{}, tenantMemberServiceDeleteRequest interface{}) *TenantMemberServiceHandler_Delete_Call {
	return &TenantMemberServiceHandler_Delete_Call{Call: _e.mock.On("Delete", context1, tenantMemberServiceDeleteRequest)}
}

func (_c *TenantMemberServiceHandler_Delete_Call) Run(run func(context1 context.Context, tenantMemberServiceDeleteRequest *apiv1.TenantMemberServiceDeleteRequest)) *TenantMemberServiceHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberServiceDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberServiceDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceHandler_Delete_Call) Return(tenantMemberResponse *apiv1.TenantMemberResponse, err error) *TenantMemberServiceHandler_Delete_Call {
	_c.Call.Return(tenantMemberResponse, err)
	return _c
}

func (_c *TenantMemberServiceHandler_Delete_Call) RunAndReturn(run func(context1 context.Context, tenantMemberServiceDeleteRequest *apiv1.TenantMemberServiceDeleteRequest) (*apiv1.TenantMemberResponse, error)) *TenantMemberServiceHandler_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type TenantMemberServiceHandler
func (_mock *TenantMemberServiceHandler) Find(context1 context.Context, tenantMemberServiceFindRequest *apiv1.TenantMemberServiceFindRequest) (*apiv1.TenantMemberListResponse, error) {
	ret := _mock.Called(context1, tenantMemberServiceFindRequest)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *apiv1.TenantMemberListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceFindRequest) (*apiv1.TenantMemberListResponse, error)); ok {
		return returnFunc(context1, tenantMemberServiceFindRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceFindRequest) *apiv1.TenantMemberListResponse); ok {
		r0 = returnFunc(context1, tenantMemberServiceFindRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberServiceFindRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberServiceFindRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceHandler_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type TenantMemberServiceHandler_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberServiceFindRequest *apiv1.TenantMemberServiceFindRequest
func (_e *TenantMemberServiceHandler_Expecter) Find(context1 interface{}, tenantMemberServiceFindRequest interface{}) *TenantMemberServiceHandler_Find_Call {
	return &TenantMemberServiceHandler_Find_Call{Call: _e.mock.On("Find", context1, tenantMemberServiceFindRequest)}
}

func (_c *TenantMemberServiceHandler_Find_Call) Run(run func(context1 context.Context, tenantMemberServiceFindRequest *apiv1.TenantMemberServiceFindRequest)) *TenantMemberServiceHandler_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberServiceFindRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberServiceFindRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceHandler_Find_Call) Return(tenantMemberListResponse *apiv1.TenantMemberListResponse, err error) *TenantMemberServiceHandler_Find_Call {
	_c.Call.Return(tenantMemberListResponse, err)
	return _c
}

func (_c *TenantMemberServiceHandler_Find_Call) RunAndReturn(run func(context1 context.Context, tenantMemberServiceFindRequest *apiv1.TenantMemberServiceFindRequest) (*apiv1.TenantMemberListResponse, error)) *TenantMemberServiceHandler_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TenantMemberServiceHandler
func (_mock *TenantMemberServiceHandler) Get(context1 context.Context, tenantMemberServiceGetRequest *apiv1.TenantMemberServiceGetRequest) (*apiv1.TenantMemberResponse, error) {
	ret := _mock.Called(context1, tenantMemberServiceGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv1.TenantMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceGetRequest) (*apiv1.TenantMemberResponse, error)); ok {
		return returnFunc(context1, tenantMemberServiceGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceGetRequest) *apiv1.TenantMemberResponse); ok {
		r0 = returnFunc(context1, tenantMemberServiceGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberServiceGetRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberServiceGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TenantMemberServiceHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberServiceGetRequest *apiv1.TenantMemberServiceGetRequest
func (_e *TenantMemberServiceHandler_Expecter) Get(context1 interface{}, tenantMemberServiceGetRequest interface{}) *TenantMemberServiceHandler_Get_Call {
	return &TenantMemberServiceHandler_Get_Call{Call: _e.mock.On("Get", context1, tenantMemberServiceGetRequest)}
}

func (_c *TenantMemberServiceHandler_Get_Call) Run(run func(context1 context.Context, tenantMemberServiceGetRequest *apiv1.TenantMemberServiceGetRequest)) *TenantMemberServiceHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberServiceGetRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberServiceGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceHandler_Get_Call) Return(tenantMemberResponse *apiv1.TenantMemberResponse, err error) *TenantMemberServiceHandler_Get_Call {
	_c.Call.Return(tenantMemberResponse, err)
	return _c
}

func (_c *TenantMemberServiceHandler_Get_Call) RunAndReturn(run func(context1 context.Context, tenantMemberServiceGetRequest *apiv1.TenantMemberServiceGetRequest) (*apiv1.TenantMemberResponse, error)) *TenantMemberServiceHandler_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TenantMemberServiceHandler
func (_mock *TenantMemberServiceHandler) Update(context1 context.Context, tenantMemberServiceUpdateRequest *apiv1.TenantMemberServiceUpdateRequest) (*apiv1.TenantMemberResponse, error) {
	ret := _mock.Called(context1, tenantMemberServiceUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *apiv1.TenantMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceUpdateRequest) (*apiv1.TenantMemberResponse, error)); ok {
		return returnFunc(context1, tenantMemberServiceUpdateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberServiceUpdateRequest) *apiv1.TenantMemberResponse); ok {
		r0 = returnFunc(context1, tenantMemberServiceUpdateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberServiceUpdateRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberServiceUpdateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TenantMemberServiceHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberServiceUpdateRequest *apiv1.TenantMemberServiceUpdateRequest
func (_e *TenantMemberServiceHandler_Expecter) Update(context1 interface{}, tenantMemberServiceUpdateRequest interface{}) *TenantMemberServiceHandler_Update_Call {
	return &TenantMemberServiceHandler_Update_Call{Call: _e.mock.On("Update", context1, tenantMemberServiceUpdateRequest)}
}

func (_c *TenantMemberServiceHandler_Update_Call) Run(run func(context1 context.Context, tenantMemberServiceUpdateRequest *apiv1.TenantMemberServiceUpdateRequest)) *TenantMemberServiceHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberServiceUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberServiceUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceHandler_Update_Call) Return(tenantMemberResponse *apiv1.TenantMemberResponse, err error) *TenantMemberServiceHandler_Update_Call {
	_c.Call.Return(tenantMemberResponse, err)
	return _c
}

func (_c *TenantMemberServiceHandler_Update_Call) RunAndReturn(run func(context1 context.Context, tenantMemberServiceUpdateRequest *apiv1.TenantMemberServiceUpdateRequest) (*apiv1.TenantMemberResponse, error)) *TenantMemberServiceHandler_Update_Call {
	_c.Call.Return(run)
	return _c
}
