// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package apiv1connect

import (
	"context"

	"github.com/metal-stack/tenant-api/go/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// NewTenantMemberServiceClient creates a new instance of TenantMemberServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTenantMemberServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenantMemberServiceClient {
	mock := &TenantMemberServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TenantMemberServiceClient is an autogenerated mock type for the TenantMemberServiceClient type
type TenantMemberServiceClient struct {
	mock.Mock
}

type TenantMemberServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TenantMemberServiceClient) EXPECT() *TenantMemberServiceClient_Expecter {
	return &TenantMemberServiceClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TenantMemberServiceClient
func (_mock *TenantMemberServiceClient) Create(context1 context.Context, tenantMemberCreateRequest *apiv1.TenantMemberCreateRequest) (*apiv1.TenantMemberResponse, error) {
	ret := _mock.Called(context1, tenantMemberCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *apiv1.TenantMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberCreateRequest) (*apiv1.TenantMemberResponse, error)); ok {
		return returnFunc(context1, tenantMemberCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberCreateRequest) *apiv1.TenantMemberResponse); ok {
		r0 = returnFunc(context1, tenantMemberCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberCreateRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TenantMemberServiceClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberCreateRequest *apiv1.TenantMemberCreateRequest
func (_e *TenantMemberServiceClient_Expecter) Create(context1 interface{}, tenantMemberCreateRequest interface{}) *TenantMemberServiceClient_Create_Call {
	return &TenantMemberServiceClient_Create_Call{Call: _e.mock.On("Create", context1, tenantMemberCreateRequest)}
}

func (_c *TenantMemberServiceClient_Create_Call) Run(run func(context1 context.Context, tenantMemberCreateRequest *apiv1.TenantMemberCreateRequest)) *TenantMemberServiceClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceClient_Create_Call) Return(tenantMemberResponse *apiv1.TenantMemberResponse, err error) *TenantMemberServiceClient_Create_Call {
	_c.Call.Return(tenantMemberResponse, err)
	return _c
}

func (_c *TenantMemberServiceClient_Create_Call) RunAndReturn(run func(context1 context.Context, tenantMemberCreateRequest *apiv1.TenantMemberCreateRequest) (*apiv1.TenantMemberResponse, error)) *TenantMemberServiceClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TenantMemberServiceClient
func (_mock *TenantMemberServiceClient) Delete(context1 context.Context, tenantMemberDeleteRequest *apiv1.TenantMemberDeleteRequest) (*apiv1.TenantMemberResponse, error) {
	ret := _mock.Called(context1, tenantMemberDeleteRequest)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *apiv1.TenantMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberDeleteRequest) (*apiv1.TenantMemberResponse, error)); ok {
		return returnFunc(context1, tenantMemberDeleteRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberDeleteRequest) *apiv1.TenantMemberResponse); ok {
		r0 = returnFunc(context1, tenantMemberDeleteRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberDeleteRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberDeleteRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TenantMemberServiceClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberDeleteRequest *apiv1.TenantMemberDeleteRequest
func (_e *TenantMemberServiceClient_Expecter) Delete(context1 interface{}, tenantMemberDeleteRequest interface{}) *TenantMemberServiceClient_Delete_Call {
	return &TenantMemberServiceClient_Delete_Call{Call: _e.mock.On("Delete", context1, tenantMemberDeleteRequest)}
}

func (_c *TenantMemberServiceClient_Delete_Call) Run(run func(context1 context.Context, tenantMemberDeleteRequest *apiv1.TenantMemberDeleteRequest)) *TenantMemberServiceClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberDeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceClient_Delete_Call) Return(tenantMemberResponse *apiv1.TenantMemberResponse, err error) *TenantMemberServiceClient_Delete_Call {
	_c.Call.Return(tenantMemberResponse, err)
	return _c
}

func (_c *TenantMemberServiceClient_Delete_Call) RunAndReturn(run func(context1 context.Context, tenantMemberDeleteRequest *apiv1.TenantMemberDeleteRequest) (*apiv1.TenantMemberResponse, error)) *TenantMemberServiceClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type TenantMemberServiceClient
func (_mock *TenantMemberServiceClient) Find(context1 context.Context, tenantMemberFindRequest *apiv1.TenantMemberFindRequest) (*apiv1.TenantMemberListResponse, error) {
	ret := _mock.Called(context1, tenantMemberFindRequest)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *apiv1.TenantMemberListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberFindRequest) (*apiv1.TenantMemberListResponse, error)); ok {
		return returnFunc(context1, tenantMemberFindRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberFindRequest) *apiv1.TenantMemberListResponse); ok {
		r0 = returnFunc(context1, tenantMemberFindRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberFindRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberFindRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceClient_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type TenantMemberServiceClient_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberFindRequest *apiv1.TenantMemberFindRequest
func (_e *TenantMemberServiceClient_Expecter) Find(context1 interface{}, tenantMemberFindRequest interface{}) *TenantMemberServiceClient_Find_Call {
	return &TenantMemberServiceClient_Find_Call{Call: _e.mock.On("Find", context1, tenantMemberFindRequest)}
}

func (_c *TenantMemberServiceClient_Find_Call) Run(run func(context1 context.Context, tenantMemberFindRequest *apiv1.TenantMemberFindRequest)) *TenantMemberServiceClient_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberFindRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberFindRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceClient_Find_Call) Return(tenantMemberListResponse *apiv1.TenantMemberListResponse, err error) *TenantMemberServiceClient_Find_Call {
	_c.Call.Return(tenantMemberListResponse, err)
	return _c
}

func (_c *TenantMemberServiceClient_Find_Call) RunAndReturn(run func(context1 context.Context, tenantMemberFindRequest *apiv1.TenantMemberFindRequest) (*apiv1.TenantMemberListResponse, error)) *TenantMemberServiceClient_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TenantMemberServiceClient
func (_mock *TenantMemberServiceClient) Get(context1 context.Context, tenantMemberGetRequest *apiv1.TenantMemberGetRequest) (*apiv1.TenantMemberResponse, error) {
	ret := _mock.Called(context1, tenantMemberGetRequest)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv1.TenantMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberGetRequest) (*apiv1.TenantMemberResponse, error)); ok {
		return returnFunc(context1, tenantMemberGetRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberGetRequest) *apiv1.TenantMemberResponse); ok {
		r0 = returnFunc(context1, tenantMemberGetRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberGetRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberGetRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TenantMemberServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberGetRequest *apiv1.TenantMemberGetRequest
func (_e *TenantMemberServiceClient_Expecter) Get(context1 interface{}, tenantMemberGetRequest interface{}) *TenantMemberServiceClient_Get_Call {
	return &TenantMemberServiceClient_Get_Call{Call: _e.mock.On("Get", context1, tenantMemberGetRequest)}
}

func (_c *TenantMemberServiceClient_Get_Call) Run(run func(context1 context.Context, tenantMemberGetRequest *apiv1.TenantMemberGetRequest)) *TenantMemberServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberGetRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceClient_Get_Call) Return(tenantMemberResponse *apiv1.TenantMemberResponse, err error) *TenantMemberServiceClient_Get_Call {
	_c.Call.Return(tenantMemberResponse, err)
	return _c
}

func (_c *TenantMemberServiceClient_Get_Call) RunAndReturn(run func(context1 context.Context, tenantMemberGetRequest *apiv1.TenantMemberGetRequest) (*apiv1.TenantMemberResponse, error)) *TenantMemberServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type TenantMemberServiceClient
func (_mock *TenantMemberServiceClient) Update(context1 context.Context, tenantMemberUpdateRequest *apiv1.TenantMemberUpdateRequest) (*apiv1.TenantMemberResponse, error) {
	ret := _mock.Called(context1, tenantMemberUpdateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *apiv1.TenantMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberUpdateRequest) (*apiv1.TenantMemberResponse, error)); ok {
		return returnFunc(context1, tenantMemberUpdateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apiv1.TenantMemberUpdateRequest) *apiv1.TenantMemberResponse); ok {
		r0 = returnFunc(context1, tenantMemberUpdateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.TenantMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apiv1.TenantMemberUpdateRequest) error); ok {
		r1 = returnFunc(context1, tenantMemberUpdateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TenantMemberServiceClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type TenantMemberServiceClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - tenantMemberUpdateRequest *apiv1.TenantMemberUpdateRequest
func (_e *TenantMemberServiceClient_Expecter) Update(context1 interface{}, tenantMemberUpdateRequest interface{}) *TenantMemberServiceClient_Update_Call {
	return &TenantMemberServiceClient_Update_Call{Call: _e.mock.On("Update", context1, tenantMemberUpdateRequest)}
}

func (_c *TenantMemberServiceClient_Update_Call) Run(run func(context1 context.Context, tenantMemberUpdateRequest *apiv1.TenantMemberUpdateRequest)) *TenantMemberServiceClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apiv1.TenantMemberUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*apiv1.TenantMemberUpdateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TenantMemberServiceClient_Update_Call) Return(tenantMemberResponse *apiv1.TenantMemberResponse, err error) *TenantMemberServiceClient_Update_Call {
	_c.Call.Return(tenantMemberResponse, err)
	return _c
}

func (_c *TenantMemberServiceClient_Update_Call) RunAndReturn(run func(context1 context.Context, tenantMemberUpdateRequest *apiv1.TenantMemberUpdateRequest) (*apiv1.TenantMemberResponse, error)) *TenantMemberServiceClient_Update_Call {
	_c.Call.Return(run)
	return _c
}
