name: build

on:
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version-file: 'go.mod'
        cache: false

    - name: Generate
      run: make proto generate

    - name: Ensure Git is clean
      run: |
        git diff --exit-code --compact-summary

  go-build:
    uses: metal-stack/actions-common/.github/workflows/go-build.yaml@v1
    secrets: inherit
    with:
      build: false
      test: true
      test-command: make test
      lint: true

  spell-check:
    uses: metal-stack/actions-common/.github/workflows/spell-check.yaml@v1

  draft:
    uses: metal-stack/actions-common/.github/workflows/release-drafter.yaml@v1
